{
 "title": "Azure Asset Inventory",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "subscription_ids",
    "query": "select distinct(subscription_id) from azure_resources"
   },
   {
    "name": "locations",
    "query": "select distinct(location) from azure_resources;"
   },
   {
    "name": "cq_tables",
    "query": "select distinct(_cq_table) from azure_resources;"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Resources",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from azure_resources where subscription_id in (${subscription_ids}) and location in (${locations}) and cq_table in (${cq_tables}) ;"
    }
   ]
  },
  {
   "title": "Total Resource by Subscription",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select subscription_id, count(*) from azure_resources where location in (${locations}) and cq_table in (${cq_tables}) group by subscription_id order by count desc;"
    }
   ]
  },
  {
   "title": "Resources by Location",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "select location, count(*) from azure_resources where subscription_id in (${subscription_ids}) group by location order by count desc;"
    }
   ]
  },
  {
   "title": "Azure Resources",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select _cq_id, _cq_table, subscription_id, location, id, _cq_sync_time from azure_resources where subscription_id in (${subscription_ids}) and location in (${locations}) and _cq_table in (${cq_tables}) ;"
    }
   ]
  },
  {
   "title": "Count by Resource Type",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "select _cq_table, count(*) from azure_resources where subscription_id in (${subscription_ids}) and location in (${locations}) group by _cq_table order by count desc;"
    }
   ]
  },
  {
   "title": "Resources by location",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 6, "y": 21 },
   "targets": [
    {
     "rawSql": "select location, count(*) from azure_resources where subscription_id in (${subscription_ids}) group by location order by count desc;"
    }
   ]
  }
 ]
}