{
 "title": "AWS Asset Inventory",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_ids",
    "query": "select distinct(account_id) from aws_resources"
   },
   {
    "name": "regions",
    "query": "select distinct(region) from aws_resources;"
   },
   {
    "name": "cq_tables",
    "query": "select distinct(_cq_table) from aws_resources;"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Resources",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_resources where account_id in (${account_ids}) and region in (${regions}) and _cq_table in (${cq_tables}) ;"
    }
   ]
  },
  {
   "title": "Total Resource by Account",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_resources where region in (${regions}) and _cq_table in (${cq_tables}) group by account_id order by count desc;"
    }
   ]
  },
  {
   "title": "Resources by Region",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "select region, count(*) from aws_resources where account_id in (${account_ids}) group by region order by count desc;"
    }
   ]
  },
  {
   "title": "AWS Resources",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select _cq_id, _cq_table, account_id, region, arn, _cq_sync_time from aws_resources where account_id in (${account_ids}) and region in (${regions}) and _cq_table in (${cq_tables}) ;"
    }
   ]
  },
  {
   "title": "Count by Resource Type",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "select _cq_table, count(*) from aws_resources where account_id in (${account_ids}) and region in (${regions}) group by _cq_table order by count desc;"
    }
   ]
  },
  {
   "title": "Resources by Region",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 6, "y": 21 },
   "targets": [
    {
     "rawSql": "select region, count(*) from aws_resources where account_id in (${account_ids}) group by region order by count desc;"
    }
   ]
  }
 ]
}