{
 "title": "VPC Details",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "VPCs",
    "label": "VPC",
    "query": "select distinct vpc_id from aws_ec2_vpcs"
   },
   {
    "name": "Subnets",
    "label": "Subnet",
    "query": "select distinct subnet_id from aws_ec2_subnets where vpc_id in (${VPCs})"
   },
   {
    "name": "Region",
    "label": "Region",
    "query": "select distinct region from aws_ec2_vpcs where vpc_id in (${VPCs})"
   }
  ]
 },
 "panels": [
  {
   "title": "Public Instances",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  (Tags->>'Name') as Name,\n  subnet_id,\n  instance_id,\n  region,\n  private_ip_address,\n  public_ip_address\nFROM aws_ec2_instances where (aws_ec2_instances.subnet_id in (${Subnets}) and aws_ec2_instances.region in (${Region}) and aws_ec2_instances.public_ip_address is not null)"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as \"Public Instances\"\nFROM aws_ec2_instances where (aws_ec2_instances.subnet_id in (${Subnets}) and aws_ec2_instances.region in (${Region}) and aws_ec2_instances.public_ip_address is not null)"
    },
    {
     "rawSql": "SELECT\n  count(*) as \"Privatee Instances\"\nFROM aws_ec2_instances where (aws_ec2_instances.subnet_id in (${Subnets}) and aws_ec2_instances.region in (${Region}) and aws_ec2_instances.public_ip_address is null)"
    }
   ]
  },
  {
   "title": "Private Instances",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  (Tags->>'Name') as Name,\n  subnet_id,\n  instance_id,\n  region,\n  private_ip_address\nFROM aws_ec2_instances where (aws_ec2_instances.subnet_id in (${Subnets}) and region in (${Region}) and aws_ec2_instances.public_ip_address is null)"
    }
   ]
  },
  {
   "title": "Active Routing Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT r.value->>'DestinationCidrBlock' AS destination,\n                r.value->>'GatewayId' AS gateway_id,\n                r.value->>'InstanceId' AS instance_id,\n                r.value->>'NatGatewayId' AS nat_gateway_id,\n                r.value->>'State' AS state\nFROM aws_ec2_route_tables,\njsonb_array_elements(aws_ec2_route_tables.routes) r,\njsonb_array_elements(associations) as a\nWHERE a->>'SubnetId' in (${Subnets})"
    }
   ]
  }
 ]
}