// Code generated by codegen; DO NOT EDIT.

package cloudformation

import (
	"github.com/cloudquery/cloudquery/plugins/source/aws/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func StackResources() *schema.Table {
	return &schema.Table{
		Name:        "aws_cloudformation_stack_resources",
		Description: `https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_StackResourceSummary.html`,
		Resolver:    fetchCloudformationStackResources,
		Multiplex:   client.ServiceAccountRegionMultiplexer("cloudformation"),
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
			},
			{
				Name:     "region",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSRegion,
			},
			{
				Name:     "last_updated_timestamp",
				Type:     schema.TypeTimestamp,
				Resolver: schema.PathResolver("LastUpdatedTimestamp"),
			},
			{
				Name:     "logical_resource_id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("LogicalResourceId"),
			},
			{
				Name:     "resource_status",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ResourceStatus"),
			},
			{
				Name:     "resource_type",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ResourceType"),
			},
			{
				Name:     "drift_information",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("DriftInformation"),
			},
			{
				Name:     "module_info",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("ModuleInfo"),
			},
			{
				Name:     "physical_resource_id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("PhysicalResourceId"),
			},
			{
				Name:     "resource_status_reason",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ResourceStatusReason"),
			},
		},
	}
}
