package plugin

import (
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/accounts"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/apple_pay_domains"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/application_fees"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/balance"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/billing_portal"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/charges"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/checkout"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/country_specs"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/coupons"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/credit_notes"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/customers"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/disputes"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/events"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/file_links"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/files"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/identity"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/invoices"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/issuing"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/payment"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/payouts"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/plans"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/prices"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/products"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/promotion_codes"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/quotes"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/radar"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/refunds"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/reporting"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/reviews"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/shipping_rates"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/sigma"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/subscription"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/tax"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/terminal"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/topups"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/transfers"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/treasury"
	"github.com/cloudquery/cloudquery/plugins/source/stripe/resources/services/webhook_endpoints"
	"github.com/cloudquery/plugin-sdk/v4/schema"
)

func rawTables() []*schema.Table {
	return []*schema.Table{
		accounts.Accounts(),
		apple_pay_domains.ApplePayDomains(),
		application_fees.ApplicationFees(),
		balance.Balance(),
		balance.BalanceTransactions(),
		billing_portal.BillingPortalConfigurations(),
		charges.Charges(),
		checkout.CheckoutSessions(),
		country_specs.CountrySpecs(),
		coupons.Coupons(),
		credit_notes.CreditNotes(),
		customers.Customers(),
		disputes.Disputes(),
		events.Events(),
		file_links.FileLinks(),
		files.Files(),
		identity.IdentityVerificationReports(),
		invoices.Invoices(),
		invoices.InvoiceItems(),
		issuing.IssuingAuthorizations(),
		issuing.IssuingCardholders(),
		issuing.IssuingCards(),
		issuing.IssuingDisputes(),
		issuing.IssuingTransactions(),
		payment.PaymentIntents(),
		payment.PaymentLinks(),
		payment.PaymentMethods(),
		payouts.Payouts(),
		plans.Plans(),
		prices.Prices(),
		products.Products(),
		promotion_codes.PromotionCodes(),
		quotes.Quotes(),
		radar.RadarEarlyFraudWarnings(),
		refunds.Refunds(),
		reporting.ReportingReportRuns(),
		reporting.ReportingReportTypes(),
		reviews.Reviews(),
		shipping_rates.ShippingRates(),
		sigma.SigmaScheduledQueryRuns(),
		subscription.Subscriptions(),
		subscription.SubscriptionSchedules(),
		tax.TaxCodes(),
		tax.TaxRates(),
		terminal.TerminalConfigurations(),
		terminal.TerminalLocations(),
		terminal.TerminalReaders(),
		topups.Topups(),
		transfers.Transfers(),
		treasury.TreasuryFinancialAccounts(),
		webhook_endpoints.WebhookEndpoints(),
	}
}
