package models

type StatsWrapper struct {
	ServiceID string `json:"service_id"`
	Region    string `json:"region"`
	StartTime uint64 `json:"start_time"` // unix timestamp
	By        string `json:"by"`         // e.g. "hour"

	// Stats
	AttackRequestHeaderBytes  uint64      `json:"attack_req_header_bytes"`
	AttackRequestBodyBytes    uint64      `json:"attack_req_body_bytes"`
	AttackResponseSynthBytes  uint64      `json:"attack_resp_synth_bytes"`
	BERequestBodyBytes        uint64      `json:"bereq_body_bytes"`
	BERequestHeaderbytes      uint64      `json:"bereq_header_bytes"`
	Bandwidth                 uint64      `json:"bandwidth"`
	BilledBodyBytes           uint64      `json:"billed_body_bytes"`
	BilledHeaderBytes         uint64      `json:"billed_header_bytes"`
	Errors                    uint64      `json:"errors"`
	HTTP2                     uint64      `json:"http2"`
	HitRatio                  float64     `json:"hit_ratio"`
	Hits                      uint64      `json:"hits"`
	HitsTime                  float64     `json:"hits_time"`
	IPv6                      uint64      `json:"ipv6"`
	ImageOptimizer            uint64      `json:"imgopto"`
	Log                       uint64      `json:"log"`
	Miss                      uint64      `json:"miss"`
	MissHistogram             map[int]int `json:"miss_histogram"`
	MissTime                  float64     `json:"miss_time"`
	OTFP                      uint64      `json:"otfp"`
	ObjectSize100k            uint64      `json:"object_size_100k"`
	ObjectSize100m            uint64      `json:"object_size_100m"`
	ObjectSize10k             uint64      `json:"object_size_10k"`
	ObjectSize10m             uint64      `json:"object_size_10m"`
	ObjectSize1g              uint64      `json:"object_size_1g"`
	ObjectSize1k              uint64      `json:"object_size_1k"`
	ObjectSize1m              uint64      `json:"object_size_1m"`
	PCI                       uint64      `json:"pci"`
	Pass                      uint64      `json:"pass"`
	PassTime                  float64     `json:"pass_time"`
	Pipe                      uint64      `json:"pipe"`
	RequestBodyBytes          uint64      `json:"req_body_bytes"`
	RequestHeaderBytes        uint64      `json:"req_header_bytes"`
	Requests                  uint64      `json:"requests"`
	ResponseBodyBytes         uint64      `json:"resp_body_bytes"`
	ResponseHeaderBytes       uint64      `json:"resp_header_bytes"`
	Restarts                  uint64      `json:"restarts"`
	Shield                    uint64      `json:"shield"`
	ShieldResponseBodyBytes   uint64      `json:"shield_resp_body_bytes"`
	ShieldResponseHeaderBytes uint64      `json:"shield_resp_header_bytes"`
	Status1xx                 uint64      `json:"status_1xx"`
	Status200                 uint64      `json:"status_200"`
	Status204                 uint64      `json:"status_204"`
	Status206                 uint64      `json:"status_206"`
	Status2xx                 uint64      `json:"status_2xx"`
	Status301                 uint64      `json:"status_301"`
	Status302                 uint64      `json:"status_302"`
	Status304                 uint64      `json:"status_304"`
	Status3xx                 uint64      `json:"status_3xx"`
	Status400                 uint64      `json:"status_400"`
	Status401                 uint64      `json:"status_401"`
	Status403                 uint64      `json:"status_403"`
	Status404                 uint64      `json:"status_404"`
	Status416                 uint64      `json:"status_416"`
	Status4xx                 uint64      `json:"status_4xx"`
	Status500                 uint64      `json:"status_500"`
	Status501                 uint64      `json:"status_501"`
	Status502                 uint64      `json:"status_502"`
	Status503                 uint64      `json:"status_503"`
	Status504                 uint64      `json:"status_504"`
	Status505                 uint64      `json:"status_505"`
	Status5xx                 uint64      `json:"status_5xx"`
	Synth                     uint64      `json:"synth"`
	TLS                       uint64      `json:"tls"`
	TLSv10                    uint64      `json:"tls_v10"`
	TLSv11                    uint64      `json:"tls_v11"`
	TLSv12                    uint64      `json:"tls_v12"`
	TLSv13                    uint64      `json:"tls_v13"`
	Uncachable                uint64      `json:"uncachable"`
	Video                     uint64      `json:"video"`
	WAFBlocked                uint64      `json:"waf_blocked"`
	WAFLogged                 uint64      `json:"waf_logged"`
	WAFPassed                 uint64      `json:"waf_passed"`

	// Not currently present in fastly-go SDK:
	ComputeBereqBodyBytes           uint64 `json:"compute_bereq_body_bytes"`
	ComputeBereqErrors              uint64 `json:"compute_bereq_errors"`
	ComputeBereqHeaderBytes         uint64 `json:"compute_bereq_header_bytes"`
	ComputeBereqs                   uint64 `json:"compute_bereqs"`
	ComputeBerespBodyBytes          uint64 `json:"compute_beresp_body_bytes"`
	ComputeBerespHeaderBytes        uint64 `json:"compute_beresp_header_bytes"`
	ComputeExecutionTimeMs          uint64 `json:"compute_execution_time_ms"`
	ComputeGlobalsLimitExceeded     uint64 `json:"compute_globals_limit_exceeded"`
	ComputeGuestErrors              uint64 `json:"compute_guest_errors"`
	ComputeHeapLimitExceeded        uint64 `json:"compute_heap_limit_exceeded"`
	ComputeRamUsed                  uint64 `json:"compute_ram_used"`
	ComputeReqBodyBytes             uint64 `json:"compute_req_body_bytes"`
	ComputeReqHeaderBytes           uint64 `json:"compute_req_header_bytes"`
	ComputeRequestTimeMs            uint64 `json:"compute_request_time_ms"`
	ComputeRequests                 uint64 `json:"compute_requests"`
	ComputeResourceLimitExceeded    uint64 `json:"compute_resource_limit_exceeded"`
	ComputeRespBodyBytes            uint64 `json:"compute_resp_body_bytes"`
	ComputeRespHeaderBytes          uint64 `json:"compute_resp_header_bytes"`
	ComputeRespStatus1xx            uint64 `json:"compute_resp_status_1xx"`
	ComputeRespStatus2xx            uint64 `json:"compute_resp_status_2xx"`
	ComputeRespStatus3xx            uint64 `json:"compute_resp_status_3xx"`
	ComputeRespStatus4xx            uint64 `json:"compute_resp_status_4xx"`
	ComputeRespStatus5xx            uint64 `json:"compute_resp_status_5xx"`
	ComputeRuntimeErrors            uint64 `json:"compute_runtime_errors"`
	ComputeStackLimitExceeded       uint64 `json:"compute_stack_limit_exceeded"`
	EdgeHitRequests                 uint64 `json:"edge_hit_requests"`
	EdgeHitRespBodyBytes            uint64 `json:"edge_hit_resp_body_bytes"`
	EdgeHitRespHeaderBytes          uint64 `json:"edge_hit_resp_header_bytes"`
	EdgeMissRequests                uint64 `json:"edge_miss_requests"`
	EdgeMissRespBodyBytes           uint64 `json:"edge_miss_resp_body_bytes"`
	EdgeMissRespHeaderBytes         uint64 `json:"edge_miss_resp_header_bytes"`
	EdgeRequests                    uint64 `json:"edge_requests"`
	EdgeRespBodyBytes               uint64 `json:"edge_resp_body_bytes"`
	EdgeRespHeaderBytes             uint64 `json:"edge_resp_header_bytes"`
	OriginCacheFetchRespBodyBytes   uint64 `json:"origin_cache_fetch_resp_body_bytes"`
	OriginCacheFetchRespHeaderBytes uint64 `json:"origin_cache_fetch_resp_header_bytes"`
	OriginCacheFetches              uint64 `json:"origin_cache_fetches"`
	OriginFetchBodyBytes            uint64 `json:"origin_fetch_body_bytes"`
	OriginFetchHeaderBytes          uint64 `json:"origin_fetch_header_bytes"`
	OriginFetchRespBodyBytes        uint64 `json:"origin_fetch_resp_body_bytes"`
	OriginFetchRespHeaderBytes      uint64 `json:"origin_fetch_resp_header_bytes"`
	OriginFetches                   uint64 `json:"origin_fetches"`
	FanoutBereqBodyBytes            uint64 `json:"fanout_bereq_body_bytes"`
	FanoutBereqHeaderBytes          uint64 `json:"fanout_bereq_header_bytes"`
	FanoutBerespBodyBytes           uint64 `json:"fanout_beresp_body_bytes"`
	FanoutBerespHeaderBytes         uint64 `json:"fanout_beresp_header_bytes"`
	FanoutConnTimeMs                uint64 `json:"fanout_conn_time_ms"`
	FanoutRecvPublishes             uint64 `json:"fanout_recv_publishes"`
	FanoutReqBodyBytes              uint64 `json:"fanout_req_body_bytes"`
	FanoutReqHeaderBytes            uint64 `json:"fanout_req_header_bytes"`
	FanoutRespBodyBytes             uint64 `json:"fanout_resp_body_bytes"`
	FanoutRespHeaderBytes           uint64 `json:"fanout_resp_header_bytes"`
	FanoutSendPublishes             uint64 `json:"fanout_send_publishes"`
}
