package client

import (
	"context"

	heroku "github.com/heroku/heroku-go/v5"
)

//go:generate mockgen -package=mocks -destination=./mocks/mock_heroku.go . HerokuService
type HerokuService interface {
	AccountFeatureList(ctx context.Context, lr *heroku.ListRange) (heroku.AccountFeatureListResult, error)
	AddOnList(ctx context.Context, lr *heroku.ListRange) (heroku.AddOnListResult, error)
	AddOnAttachmentList(ctx context.Context, lr *heroku.ListRange) (heroku.AddOnAttachmentListResult, error)
	AddOnConfigList(ctx context.Context, addOnIdentity string, lr *heroku.ListRange) (heroku.AddOnConfigListResult, error)
	AddOnRegionCapabilityList(ctx context.Context, lr *heroku.ListRange) (heroku.AddOnRegionCapabilityListResult, error)
	AddOnServiceList(ctx context.Context, lr *heroku.ListRange) (heroku.AddOnServiceListResult, error)
	AddOnWebhookList(ctx context.Context, addOnIdentity string, lr *heroku.ListRange) (heroku.AddOnWebhookListResult, error)
	AddOnWebhookDeliveryList(ctx context.Context, addOnIdentity string, lr *heroku.ListRange) (heroku.AddOnWebhookDeliveryListResult, error)
	AddOnWebhookEventList(ctx context.Context, addOnIdentity string, lr *heroku.ListRange) (heroku.AddOnWebhookEventListResult, error)
	AppList(ctx context.Context, lr *heroku.ListRange) (heroku.AppListResult, error)
	AppFeatureList(ctx context.Context, appIdentity string, lr *heroku.ListRange) (heroku.AppFeatureListResult, error)
	AppTransferList(ctx context.Context, lr *heroku.ListRange) (heroku.AppTransferListResult, error)
	AppWebhookList(ctx context.Context, appIdentity string, lr *heroku.ListRange) (heroku.AppWebhookListResult, error)
	AppWebhookDeliveryList(ctx context.Context, appIdentity string, lr *heroku.ListRange) (heroku.AppWebhookDeliveryListResult, error)
	AppWebhookEventList(ctx context.Context, appIdentity string, lr *heroku.ListRange) (heroku.AppWebhookEventListResult, error)
	ArchiveList(ctx context.Context, enterpriseAccountIdentity string, lr *heroku.ListRange) (*heroku.Archive, error)
	AuditTrailEventList(ctx context.Context, enterpriseAccountIdentity string, lr *heroku.ListRange) (*heroku.AuditTrailEvent, error)
	BuildList(ctx context.Context, appIdentity string, lr *heroku.ListRange) (heroku.BuildListResult, error)
	BuildpackInstallationList(ctx context.Context, appIdentity string, lr *heroku.ListRange) (heroku.BuildpackInstallationListResult, error)
	CollaboratorList(ctx context.Context, appIdentity string, lr *heroku.ListRange) (heroku.CollaboratorListResult, error)
	CreditList(ctx context.Context, lr *heroku.ListRange) (heroku.CreditListResult, error)
	DomainList(ctx context.Context, appIdentity string, lr *heroku.ListRange) (heroku.DomainListResult, error)
	DynoList(ctx context.Context, appIdentity string, lr *heroku.ListRange) (heroku.DynoListResult, error)
	DynoSizeList(ctx context.Context, lr *heroku.ListRange) (heroku.DynoSizeListResult, error)
	EnterpriseAccountList(ctx context.Context, lr *heroku.ListRange) (heroku.EnterpriseAccountListResult, error)
	EnterpriseAccountMemberList(ctx context.Context, enterpriseAccountIdentity string, lr *heroku.ListRange) (heroku.EnterpriseAccountMemberListResult, error)
	FormationList(ctx context.Context, appIdentity string, lr *heroku.ListRange) (heroku.FormationListResult, error)
	InboundRulesetList(ctx context.Context, spaceIdentity string, lr *heroku.ListRange) (heroku.InboundRulesetListResult, error)
	InvoiceList(ctx context.Context, lr *heroku.ListRange) (heroku.InvoiceListResult, error)
	KeyList(ctx context.Context, lr *heroku.ListRange) (heroku.KeyListResult, error)
	LogDrainList(ctx context.Context, appIdentity string, lr *heroku.ListRange) (heroku.LogDrainListResult, error)
	OAuthAuthorizationList(ctx context.Context, lr *heroku.ListRange) (heroku.OAuthAuthorizationListResult, error)
	OAuthClientList(ctx context.Context, lr *heroku.ListRange) (heroku.OAuthClientListResult, error)
	OutboundRulesetList(ctx context.Context, spaceIdentity string, lr *heroku.ListRange) (heroku.OutboundRulesetListResult, error)
	PeeringList(ctx context.Context, spaceIdentity string, lr *heroku.ListRange) (heroku.PeeringListResult, error)
	PermissionEntityList(ctx context.Context, teamIdentity string, lr *heroku.ListRange) (heroku.PermissionEntityListResult, error)
	PipelineList(ctx context.Context, lr *heroku.ListRange) (heroku.PipelineListResult, error)
	PipelineBuildList(ctx context.Context, pipelineID string, lr *heroku.ListRange) (heroku.PipelineBuildListResult, error)
	PipelineCouplingList(ctx context.Context, lr *heroku.ListRange) (heroku.PipelineCouplingListResult, error)
	PipelineDeploymentList(ctx context.Context, pipelineID string, lr *heroku.ListRange) (heroku.PipelineDeploymentListResult, error)
	PipelinePromotionTargetList(ctx context.Context, pipelinePromotionID string, lr *heroku.ListRange) (heroku.PipelinePromotionTargetListResult, error)
	PipelineReleaseList(ctx context.Context, pipelineID string, lr *heroku.ListRange) (heroku.PipelineReleaseListResult, error)
	RegionList(ctx context.Context, lr *heroku.ListRange) (heroku.RegionListResult, error)
	ReleaseList(ctx context.Context, appIdentity string, lr *heroku.ListRange) (heroku.ReleaseListResult, error)
	ReviewAppList(ctx context.Context, pipelineID string, lr *heroku.ListRange) (heroku.ReviewAppListResult, error)
	SniEndpointList(ctx context.Context, appIdentity string, lr *heroku.ListRange) (heroku.SniEndpointListResult, error)
	SpaceList(ctx context.Context, lr *heroku.ListRange) (heroku.SpaceListResult, error)
	SpaceAppAccessList(ctx context.Context, spaceIdentity string, lr *heroku.ListRange) (heroku.SpaceAppAccessListResult, error)
	SSLEndpointList(ctx context.Context, appIdentity string, lr *heroku.ListRange) (heroku.SSLEndpointListResult, error)
	StackList(ctx context.Context, lr *heroku.ListRange) (heroku.StackListResult, error)
	TeamList(ctx context.Context, lr *heroku.ListRange) (heroku.TeamListResult, error)
	TeamAppCollaboratorList(ctx context.Context, teamAppIdentity string, lr *heroku.ListRange) (heroku.TeamAppCollaboratorListResult, error)
	TeamAppPermissionList(ctx context.Context, lr *heroku.ListRange) (heroku.TeamAppPermissionListResult, error)
	TeamFeatureList(ctx context.Context, teamIdentity string, lr *heroku.ListRange) (heroku.TeamFeatureListResult, error)
	TeamInvitationList(ctx context.Context, teamName string, lr *heroku.ListRange) (heroku.TeamInvitationListResult, error)
	TeamInvoiceList(ctx context.Context, teamIdentity string, lr *heroku.ListRange) (heroku.TeamInvoiceListResult, error)
	TeamMemberList(ctx context.Context, teamIdentity string, lr *heroku.ListRange) (heroku.TeamMemberListResult, error)
	TeamPreferencesList(ctx context.Context, teamPreferencesIdentity string) (*heroku.TeamPreferences, error)
	TeamSpaceList(ctx context.Context, teamIdentity string, lr *heroku.ListRange) (heroku.TeamSpaceListResult, error)
	TestCaseList(ctx context.Context, testRunID string, lr *heroku.ListRange) error
	TestNodeList(ctx context.Context, testRunIdentity string, lr *heroku.ListRange) error
	TestRunList(ctx context.Context, pipelineID string, lr *heroku.ListRange) error
	UserPreferencesList(ctx context.Context, userPreferencesIdentity string) (*heroku.UserPreferences, error)
	VPNConnectionList(ctx context.Context, spaceIdentity string, lr *heroku.ListRange) (heroku.VPNConnectionListResult, error)
}
