package codegen

import (
	"github.com/cloudquery/cloudquery/plugins/source/digitalocean/resources/services/droplets"
	"github.com/cloudquery/plugin-sdk/codegen"
	"github.com/cloudquery/plugin-sdk/schema"
	"github.com/digitalocean/godo"
)

var emptyString = ""

var Resources = []*Resource{
	{
		Service:      "account",
		Template:     "resource_get",
		MockTemplate: "resource_get_mock",
		Struct:       godo.Account{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		ChildTable:   false,
		SkipMock:     false,
	},
	{
		Service:      "cdn",
		Template:     "resource_list",
		MockTemplate: "resource_list_mock",
		Struct:       godo.CDN{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		ChildTable:   false,
	},
	{
		Service:      "billing_history",
		Template:     "resource_list",
		MockTemplate: "resource_list_mock",
		ResponsePath: ".BillingHistory",
		Struct:       godo.BillingHistoryEntry{},
		MockStruct:   godo.BillingHistory{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		ChildTable:   false,
		MockWrapper:  true,
	},
	{
		Service:      "monitoring",
		Template:     "resource_list",
		MockTemplate: "resource_list_mock",
		SubService:   "alert_policies",
		Struct:       godo.AlertPolicy{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		ChildTable:   false,
	},

	{
		Service:      "balance",
		Template:     "resource_get",
		MockTemplate: "resource_get_mock",
		Struct:       godo.Balance{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		ChildTable:   false,
	},
	{
		Service:      "certificates",
		Template:     "resource_list",
		MockTemplate: "resource_list_mock",
		Struct:       godo.Certificate{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		ChildTable:   false,
	},
	{
		Service:     "databases",
		Template:    "resource_list",
		Struct:      godo.Database{},
		NewFunction: godo.NewClient,
		Multiplex:   &emptyString,
		ChildTable:  false,
		Relations:   []string{"Backups", "Replicas", "FirewallRules"},
		SkipMock:    true,
	},
	{
		Service:      "databases",
		SubService:   "backups",
		Template:     "resource_list",
		Struct:       godo.DatabaseBackup{},
		ParentStruct: godo.Database{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		ChildTable:   true,
		SkipMock:     true,
	},
	{
		Service:      "databases",
		SubService:   "replicas",
		Template:     "resource_list",
		Struct:       godo.DatabaseReplica{},
		ParentStruct: godo.Database{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		ChildTable:   true,
		SkipMock:     true,
	},
	{
		Service:      "databases",
		SubService:   "firewall_rules",
		Template:     "resource_get",
		Imports:      []string{"github.com/digitalocean/godo"},
		Struct:       godo.DatabaseFirewallRule{},
		ParentStruct: godo.Database{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		ChildTable:   true,
		SkipMock:     true,
	},
	{
		Service:     "domains",
		Template:    "resource_list",
		Struct:      godo.Domain{},
		NewFunction: godo.NewClient,
		Multiplex:   &emptyString,
		SkipMock:    false,
		Relations:   []string{"Records"},
	},
	{
		Service:      "domains",
		SubService:   "records",
		Template:     "resource_list",
		MockTemplate: "resource_list_child_mock",
		Args:         ", p.Name",
		Struct:       godo.DomainRecord{},
		ParentStruct: godo.Domain{},
		FunctionName: "Records",
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		SkipMock:     false,
	},
	{
		Service:     "droplets",
		Template:    "resource_list",
		Struct:      godo.Droplet{},
		NewFunction: godo.NewClient,
		Multiplex:   &emptyString,
		SkipMock:    false,
		Relations:   []string{"Neighbors"},
	},
	{
		Service:      "droplets",
		SubService:   "neighbors",
		Template:     "resource_list",
		MockTemplate: "resource_list_child_mock",
		FunctionName: "Neighbors",
		Struct:       &droplets.NeighborWrapper{},
		ParentStruct: &godo.Droplet{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		SkipMock:     true,
		SkipFetch:    true,
	},
	{
		Service:     "firewalls",
		Template:    "resource_list",
		Struct:      godo.Firewall{},
		NewFunction: godo.NewClient,
		Multiplex:   &emptyString,
		SkipMock:    false,
		OverrideColumns: []codegen.ColumnDefinition{
			{
				Name:     "droplet_i_ds",
				Type:     schema.TypeStringArray,
				Resolver: `schema.PathResolver("DropletIDs")`,
			},
		},
	},

	{
		Service:     "floating_ips",
		Template:    "resource_list",
		Struct:      godo.FloatingIP{},
		NewFunction: godo.NewClient,
		Multiplex:   &emptyString,
		SkipMock:    false,
	},
	{
		Service:     "images",
		Template:    "resource_list",
		Struct:      godo.Image{},
		NewFunction: godo.NewClient,
		Multiplex:   &emptyString,
		SkipMock:    false,
	},
	{
		Service:     "keys",
		Template:    "resource_list",
		Struct:      godo.Key{},
		NewFunction: godo.NewClient,
		Multiplex:   &emptyString,
		SkipMock:    false,
	},
	{
		Service:     "projects",
		Template:    "resource_list",
		Struct:      godo.Project{},
		NewFunction: godo.NewClient,
		Multiplex:   &emptyString,
		SkipMock:    false,
		Relations:   []string{"Resources"},
	},
	{
		Service:      "projects",
		SubService:   "resources",
		Template:     "resource_list",
		MockTemplate: "resource_list_child_mock",
		Struct:       godo.ProjectResource{},
		ParentStruct: godo.Project{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		SkipMock:     false,
		ChildTable:   true,
	},
	{
		Service:      "registry",
		Template:     "resource_get",
		MockTemplate: "resource_get_mock",
		Struct:       &godo.Registry{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		ChildTable:   false,
		SkipMock:     false,
		Relations:    []string{"Repositories"},
	},
	{
		Service:      "registry",
		SubService:   "repositories",
		Args:         ", p.Name",
		Template:     "resource_list",
		MockTemplate: "resource_list_child_mock",
		Struct:       &godo.Repository{},
		ParentStruct: &godo.Registry{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		ChildTable:   true,
	},
	{
		Service:      "sizes",
		Template:     "resource_list",
		MockTemplate: "resource_list_mock",
		Struct:       godo.Size{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
	},
	{
		Service:      "snapshots",
		Template:     "resource_list",
		MockTemplate: "resource_list_mock",
		Struct:       godo.Snapshot{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
	},
	{
		Service:      "storage",
		SubService:   "volumes",
		Template:     "resource_list",
		MockTemplate: "resource_list_mock",
		Struct:       godo.Volume{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		SkipFetch:    true,
	},
	{
		Service:      "vpcs",
		Template:     "resource_list",
		MockTemplate: "resource_list_mock",
		Struct:       &godo.VPC{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		Relations:    []string{"Members"},
	},
	{
		Service:    "vpcs",
		SubService: "members",
		Args:       ", p.ID, nil",
		Template:   "resource_list",
		//MockTemplate: "resource_list_child_mock",
		Struct:       &godo.VPCMember{},
		ParentStruct: &godo.VPC{},
		NewFunction:  godo.NewClient,
		Multiplex:    &emptyString,
		ChildTable:   true,
		SkipMock:     true,
	},
}
