// Configuration AutoGenerated by CloudQuery CLI
cloudquery {
  plugin_directory = "."

  provider "test" {
    source  = "cloudquery/cq-provider-test"
    version = "latest"
  }

  connection {
    dsn = "host=localhost user=postgres password=pass DB.name=postgres port=5432"
  }
}

// All Provider Configurations

provider "test" {

  configuration {
    account "1" {
      regions   = ["asdas"]
      resources = ["ab", "c"]
    }

    regions = ["adsa"]
  }
  resources = ["very_slow_resource", "error_resource", "slow_resource"]
}
