// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudquery/cloudquery/plugins/source/digitalocean/client (interfaces: RegionsService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	godo "github.com/digitalocean/godo"
	gomock "github.com/golang/mock/gomock"
)

// MockRegionsService is a mock of RegionsService interface.
type MockRegionsService struct {
	ctrl     *gomock.Controller
	recorder *MockRegionsServiceMockRecorder
}

// MockRegionsServiceMockRecorder is the mock recorder for MockRegionsService.
type MockRegionsServiceMockRecorder struct {
	mock *MockRegionsService
}

// NewMockRegionsService creates a new mock instance.
func NewMockRegionsService(ctrl *gomock.Controller) *MockRegionsService {
	mock := &MockRegionsService{ctrl: ctrl}
	mock.recorder = &MockRegionsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegionsService) EXPECT() *MockRegionsServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockRegionsService) List(arg0 context.Context, arg1 *godo.ListOptions) ([]godo.Region, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]godo.Region)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRegionsServiceMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRegionsService)(nil).List), arg0, arg1)
}
