// Code generated by codegen; DO NOT EDIT.
package storage

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage"
)

type StorageClient struct {
	AccountsClient       AccountsClient
	BlobContainersClient BlobContainersClient
	BlobServicesClient   BlobServicesClient
}

func NewStorageClient(subscriptionID string, credentials azcore.TokenCredential, options *arm.ClientOptions) (*StorageClient, error) {
	var client StorageClient
	var err error

	client.AccountsClient, err = armstorage.NewAccountsClient(subscriptionID, credentials, options)
	if err != nil {
		return nil, err
	}

	client.BlobContainersClient, err = armstorage.NewBlobContainersClient(subscriptionID, credentials, options)
	if err != nil {
		return nil, err
	}

	client.BlobServicesClient, err = armstorage.NewBlobServicesClient(subscriptionID, credentials, options)
	if err != nil {
		return nil, err
	}

	return &client, nil
}
