ALTER TABLE aws_apigateway_api_keys DROP COLUMN arn;
ALTER TABLE aws_apigateway_client_certificates DROP COLUMN arn;
ALTER TABLE aws_apigateway_domain_names DROP COLUMN arn;
ALTER TABLE aws_apigateway_domain_name_base_path_mappings DROP COLUMN arn;
ALTER TABLE aws_apigateway_rest_apis DROP COLUMN arn;
ALTER TABLE aws_apigateway_rest_api_authorizers DROP COLUMN arn;
ALTER TABLE aws_apigateway_rest_api_deployments DROP COLUMN arn;
ALTER TABLE aws_apigateway_rest_api_documentation_parts DROP COLUMN arn;
ALTER TABLE aws_apigateway_rest_api_documentation_versions DROP COLUMN arn;
ALTER TABLE aws_apigateway_rest_api_gateway_responses DROP COLUMN arn;
ALTER TABLE aws_apigateway_rest_api_models DROP COLUMN arn;
ALTER TABLE aws_apigateway_rest_api_request_validators DROP COLUMN arn;
ALTER TABLE aws_apigateway_rest_api_resources DROP COLUMN arn;
ALTER TABLE aws_apigateway_rest_api_stages DROP COLUMN arn;
ALTER TABLE aws_apigateway_usage_plans DROP COLUMN arn;
ALTER TABLE aws_apigateway_usage_plan_keys DROP COLUMN arn;
ALTER TABLE aws_apigateway_vpc_links DROP COLUMN arn;
ALTER TABLE aws_apigatewayv2_apis DROP COLUMN arn;
ALTER TABLE aws_apigatewayv2_api_authorizers DROP COLUMN arn;
ALTER TABLE aws_apigatewayv2_api_deployments DROP COLUMN arn;
ALTER TABLE aws_apigatewayv2_api_integrations DROP COLUMN arn;
ALTER TABLE aws_apigatewayv2_api_integration_responses DROP COLUMN arn;
ALTER TABLE aws_apigatewayv2_api_models DROP COLUMN arn;
ALTER TABLE aws_apigatewayv2_api_routes DROP COLUMN arn;
ALTER TABLE aws_apigatewayv2_api_route_responses DROP COLUMN arn;
ALTER TABLE aws_apigatewayv2_api_stages DROP COLUMN arn;
ALTER TABLE aws_apigatewayv2_domain_name_rest_api_mappings DROP COLUMN arn TEXT;
ALTER TABLE aws_apigatewayv2_domain_names DROP COLUMN arn TEXT;
ALTER TABLE aws_apigatewayv2_vpc_links DROP COLUMN arn TEXT;
ALTER TABLE aws_cloudfront_cache_policies DROP COLUMN arn TEXT;
ALTER TABLE aws_cognito_identity_pools DROP COLUMN arn TEXT;
ALTER TABLE aws_directconnect_connections DROP COLUMN arn TEXT;
ALTER TABLE aws_directconnect_gateways DROP COLUMN arn TEXT;
ALTER TABLE aws_directconnect_lags DROP COLUMN arn TEXT;
ALTER TABLE aws_directconnect_virtual_interfaces DROP COLUMN arn TEXT;
ALTER TABLE aws_ec2_flow_logs DROP COLUMN arn TEXT;
ALTER TABLE aws_ec2_images DROP COLUMN arn TEXT;
ALTER TABLE aws_ec2_instance_network_interfaces DROP COLUMN arn TEXT;
ALTER TABLE aws_ec2_instances DROP COLUMN arn TEXT;
ALTER TABLE aws_ec2_internet_gateways DROP COLUMN arn TEXT;
ALTER TABLE aws_ec2_nat_gateways DROP COLUMN arn TEXT;
ALTER TABLE aws_ec2_network_acls DROP COLUMN arn TEXT;
ALTER TABLE aws_ec2_route_tables DROP COLUMN arn TEXT;
ALTER TABLE aws_ec2_transit_gateways RENAME COLUMN arn TO transit_gateway_arn;
ALTER TABLE aws_ec2_vpc_endpoints DROP COLUMN arn TEXT;
ALTER TABLE aws_ec2_vpc_peering_connections DROP COLUMN arn TEXT;
ALTER TABLE aws_ec2_vpcs DROP COLUMN arn TEXT;
ALTER TABLE aws_ec2_vpn_gateways DROP COLUMN arn TEXT;
ALTER TABLE aws_efs_filesystems RENAME COLUMN arn TO file_system_arn;
ALTER TABLE aws_elbv1_load_balancers DROP COLUMN arn TEXT;
ALTER TABLE aws_rds_clusters RENAME COLUMN arn TO db_cluster_arn;
ALTER TABLE aws_redshift_clusters DROP COLUMN arn TEXT;
ALTER TABLE aws_redshift_subnet_groups DROP COLUMN arn TEXT;
ALTER TABLE aws_guardduty_detectors DROP COLUMN arn TEXT;
