{
 "title": "Kubernetes Asset Inventory",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "contexts",
    "query": "select distinct(context) from k8s_resources"
   },
   {
    "name": "cq_tables",
    "query": "select distinct(_cq_table) from k8s_resources;"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Resources",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from k8s_resources where context in (${contexts}) and _cq_table in (${cq_tables}) ;"
    }
   ]
  },
  {
   "title": "Total Resources by Context",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select context, count(*) from k8s_resources where _cq_table in (${cq_tables}) group by context order by count desc;"
    }
   ]
  },
  {
   "title": "Kubernetes Resources",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select _cq_id, _cq_table, context, uid, _cq_sync_time from k8s_resources where context in (${contexts}) and _cq_table in (${cq_tables}) ;"
    }
   ]
  },
  {
   "title": "Count by Resource Type",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "select _cq_table, count(*) from k8s_resources where context in (${contexts}) group by _cq_table order by count desc;"
    }
   ]
  }
 ]
}