{
 "title": "Kubernetes Compliance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "contexts",
    "query": "SELECT context FROM k8s_policy_results"
   },
   {
    "name": "framework",
    "query": "SELECT framework FROM k8s_policy_results"
   },
   {
    "name": "status",
    "query": "select status from k8s_policy_results"
   }
  ]
 },
 "panels": [
  { "title": "CloudQuery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Source",
   "type": "stat",
   "description": "This panel will show OK if the k8s_resources view has been created and is accessible to the current Postgres user.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'k8s_policy_results'"
    }
   ]
  },
  {
   "title": "Last Sync",
   "type": "stat",
   "description": "Time since the most recent CloudQuery sync happened.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT _cq_sync_time AS time, 1 FROM k8s_core_pods ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Last Policy Execution",
   "type": "stat",
   "description": "Time since the most recent policy execution happened.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT execution_time AS time, 1 FROM k8s_policy_results ORDER BY execution_time DESC LIMIT 1;"
    }
   ]
  },
  { "title": "Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Policy Pass/Fail Distribution",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT framework, COUNT(CASE WHEN status = 'fail' THEN 1 ELSE NULL END) AS fail, COUNT(CASE WHEN status = 'pass' THEN 1 ELSE NULL END) AS pass from k8s_policy_results WHERE context IN (${contexts}) AND framework IN (${framework}) GROUP BY framework;"
    }
   ]
  },
  {
   "title": "Failed Checks",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT execution_time AS time, COUNT(*) FROM k8s_policy_results WHERE context IN (${contexts}) AND framework IN (${framework}) AND status = 'fail' AND $__timeFilter(execution_time) GROUP BY execution_time;"
    }
   ]
  },
  {
   "title": "Passed Checks",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT execution_time AS time, COUNT(*) FROM k8s_policy_results WHERE context IN (${contexts}) AND framework IN (${framework}) AND status = 'pass' AND $__timeFilter(execution_time) GROUP BY execution_time;"
    }
   ]
  },
  {
   "title": "Policy Results",
   "type": "table",
   "description": "All policies, benchmarks results.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT * FROM k8s_policy_results WHERE context IN (${contexts}) AND framework IN (${framework}) AND status IN (${status});"
    }
   ]
  }
 ]
}