// Code generated by codegen; DO NOT EDIT.
package packages

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute"

func Armcompute() []*Table {
	tables := []*Table{
		{
			NewFunc: armcompute.NewRestorePointCollectionsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/restorePointCollections",
		},
		{
			NewFunc: armcompute.NewUsageClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/usages",
		},
		{
			NewFunc: armcompute.NewCloudServicesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/cloudServices",
		},
		{
			NewFunc: armcompute.NewImagesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/images",
		},
		{
			NewFunc: armcompute.NewDisksClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/disks",
		},
		{
			NewFunc: armcompute.NewVirtualMachineImagesEdgeZoneClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/edgeZones/{edgeZone}/publishers/{publisherName}/artifacttypes/vmimage/offers/{offer}/skus/{skus}/versions",
		},
		{
			NewFunc: armcompute.NewVirtualMachineSizesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/vmSizes",
		},
		{
			NewFunc: armcompute.NewDiskEncryptionSetsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/diskEncryptionSets",
		},
		{
			NewFunc: armcompute.NewVirtualMachineImagesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmimage/offers/{offer}/skus/{skus}/versions",
		},
		{
			NewFunc: armcompute.NewDiskAccessesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/diskAccesses",
		},
		{
			NewFunc: armcompute.NewVirtualMachineScaleSetExtensionsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}/extensions",
		},
		{
			NewFunc: armcompute.NewVirtualMachineRunCommandsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/runCommands",
		},
		{
			NewFunc: armcompute.NewSharedGalleryImageVersionsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/sharedGalleries/{galleryUniqueName}/images/{galleryImageName}/versions",
		},
		{
			NewFunc: armcompute.NewGalleriesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/galleries",
		},
		{
			NewFunc: armcompute.NewVirtualMachineScaleSetsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets",
		},
		{
			NewFunc: armcompute.NewResourceSKUsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/skus",
		},
		{
			NewFunc: armcompute.NewVirtualMachineScaleSetVMExtensionsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}/virtualMachines/{instanceId}/extensions",
		},
		{
			NewFunc: armcompute.NewVirtualMachineScaleSetVMRunCommandsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}/virtualMachines/{instanceId}/runCommands",
		},
		{
			NewFunc: armcompute.NewCloudServiceRolesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/cloudServices/{cloudServiceName}/roles",
		},
		{
			NewFunc: armcompute.NewVirtualMachineExtensionsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/extensions",
		},
		{
			NewFunc: armcompute.NewVirtualMachineScaleSetVMsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{virtualMachineScaleSetName}/virtualMachines",
		},
		{
			NewFunc: armcompute.NewSnapshotsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/snapshots",
		},
		{
			NewFunc: armcompute.NewSharedGalleryImagesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/sharedGalleries/{galleryUniqueName}/images",
		},
		{
			NewFunc: armcompute.NewCloudServiceRoleInstancesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/cloudServices/{cloudServiceName}/roleInstances",
		},
		{
			NewFunc: armcompute.NewAvailabilitySetsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/availabilitySets",
		},
		{
			NewFunc: armcompute.NewVirtualMachinesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines",
		},
		{
			NewFunc: armcompute.NewSharedGalleriesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/sharedGalleries",
		},
	}
	return tables
}

func init() {
	Tables = append(Tables, Armcompute())
}