// Code generated by codegen; DO NOT EDIT.
package packages

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/commerce/armcommerce"

func Armcommerce() []*Table {
	tables := []*Table{
		{
			NewFunc: armcommerce.NewUsageAggregatesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/commerce/armcommerce",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.Commerce/UsageAggregates",
		},
	}
	return tables
}

func init() {
	Tables = append(Tables, Armcommerce())
}