// Code generated by codegen; DO NOT EDIT.
package packages

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/datafactory/armdatafactory"

func Armdatafactory() []*Table {
	tables := []*Table{
		{
			NewFunc: armdatafactory.NewFactoriesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/datafactory/armdatafactory",
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.DataFactory/factories",
		},
	}
	return tables
}

func init() {
	Tables = append(Tables, Armdatafactory())
}