export const top8Services = [
  'redis',
  'postgresql',
  'saas',
  'search',
  'security',
  'servicebus',
  'sql',
  'devops',
];

// NOTE: this is attempted logical grouping of like tables into a single service
export const serviceNameResolutions: Record<string, string> = {
  postgresqlflexibleservers: 'postgresql',
  postgresqlhsc: 'postgresql',
};

export const serviceLabelMap: Record<string, string> = {
  advisor: 'Advisor',
  analysisservices: 'Analysis Services',
  apimanagement: 'API Management',
  appcomplianceautomation: 'App Compliance Automation',
  appconfiguration: 'Appconfiguration',
  applicationinsights: 'Application Insights',
  appservice: 'App Service',
  authorization: 'Authorization',
  automation: 'Automation',
  azurearcdata: 'Arc Data',
  batch: 'Batch',
  billing: 'Billing',
  botservice: 'Botservice',
  cdn: 'Content Delivery Network (CDN)',
  cognitiveservices: 'Cognitive Services',
  compute: 'Compute',
  confluent: 'Confluent',
  connectedvmware: 'Connected VMware',
  consumption: 'Consumption',
  containerinstance: 'Container Instance',
  containerregistry: 'Container Registry',
  containerservice: 'Container Service',
  cosmos: 'Cosmos',
  costmanagement: 'Cost Management',
  customerinsights: 'Customer Insights',
  dashboard: 'Dashboard',
  databox: 'Data Box',
  databricks: 'Databricks',
  datacatalog: 'Data Catalog',
  datadog: 'Datadog',
  datafactory: 'Data Factory',
  datalakeanalytics: 'Data Lake Analytics',
  datalakestore: 'Data Lake Store',
  datamigration: 'Data Migration',
  datashare: 'Data Share',
  desktopvirtualization: 'Desktop Virtualization',
  devhub: 'Devhub',
  devops: 'DevOps',
  dns: 'DNS',
  dnsresolver: 'Resolver',
  elastic: 'Elastic',
  engagementfabric: 'Engagement Fabric',
  eventgrid: 'Event Grid',
  eventhub: 'Event Hub',
  frontdoor: 'Front Door',
  hanaonazure: 'HANA on Azure SAP Monitors',
  hdinsight: 'HDInsight',
  healthbot: 'Health Bot',
  healthcareapis: 'Healthcare APIs',
  hybridcompute: 'Hybrid Compute',
  hybriddatamanager: 'Hybrid  Manager',
  keyvault: 'Key Vault',
  kusto: 'Kusto',
  logic: 'Logic',
  machinelearningservices: 'Machine Learning Services',
  maintenance: 'Maintenance',
  managementgroups: 'Management Groups',
  mariadb: 'MariaDB',
  marketplace: 'Marketplace',
  monitor: 'Monitor',
  mysqlflexibleservers: 'MySQL Flexible Servers',
  mysql: 'MySQL',
  network: 'Network',
  networkfunction: 'Network Function',
  nginx: 'Nginx',
  notificationhubs: 'Notification Hubs',
  operationalinsights: 'Operational Insights',
  peering: 'Peering',
  policy: 'Policy',
  portal: 'Portal',
  postgresql: 'PostgreSQL',
  postgresqlflexibleservers: 'PostgreSQL Flexible Servers',
  postgresqlhsc: 'PostgreSQL Hyperscale (Citus)',
  powerbidedicated: 'Power BI Dedicated',
  privatedns: 'Private DNS',
  providerhub: 'Provider Hub',
  recoveryservices: 'Recovery Services',
  redhatopenshift: 'Red Hat OpenShift',
  redis: 'Redis',
  relay: 'Relay',
  reservations: 'Reservations',
  resources: 'Resources',
  role: 'Role',
  saas: 'Software as a Service (SaaS)',
  search: 'Search',
  security: 'Security',
  servicebus: 'Service Bus',
  sql: 'SQL',
  sqlvirtualmachine: 'SQL Virtual Machine',
  storage: 'Storage',
  storagecache: 'Storage Cache',
  storagesync: 'Storage Sync',
  streamanalytics: 'Stream Analytics',
  subscription: 'Subscription',
  support: 'Support',
  synapse: 'Synapse',
  trafficmanager: 'Traffic Manager',
  windowsiot: 'Windows IoT',
  workloads: 'Workloads',
};
