// Code generated by MockGen. DO NOT EDIT.
// Source: database_blob_auditing_policies.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armsql "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql"
	sql "github.com/cloudquery/cloudquery/plugins/source/azure/client/services/sql"
	gomock "github.com/golang/mock/gomock"
)

// MockDatabaseBlobAuditingPoliciesClient is a mock of DatabaseBlobAuditingPoliciesClient interface.
type MockDatabaseBlobAuditingPoliciesClient struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseBlobAuditingPoliciesClientMockRecorder
}

// MockDatabaseBlobAuditingPoliciesClientMockRecorder is the mock recorder for MockDatabaseBlobAuditingPoliciesClient.
type MockDatabaseBlobAuditingPoliciesClientMockRecorder struct {
	mock *MockDatabaseBlobAuditingPoliciesClient
}

// NewMockDatabaseBlobAuditingPoliciesClient creates a new mock instance.
func NewMockDatabaseBlobAuditingPoliciesClient(ctrl *gomock.Controller) *MockDatabaseBlobAuditingPoliciesClient {
	mock := &MockDatabaseBlobAuditingPoliciesClient{ctrl: ctrl}
	mock.recorder = &MockDatabaseBlobAuditingPoliciesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseBlobAuditingPoliciesClient) EXPECT() *MockDatabaseBlobAuditingPoliciesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDatabaseBlobAuditingPoliciesClient) Get(arg0 context.Context, arg1, arg2, arg3 string, arg4 *armsql.DatabaseBlobAuditingPoliciesClientGetOptions) (armsql.DatabaseBlobAuditingPoliciesClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(armsql.DatabaseBlobAuditingPoliciesClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDatabaseBlobAuditingPoliciesClientMockRecorder) Get(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDatabaseBlobAuditingPoliciesClient)(nil).Get), arg0, arg1, arg2, arg3, arg4)
}

// NewListByDatabasePager mocks base method.
func (m *MockDatabaseBlobAuditingPoliciesClient) NewListByDatabasePager(arg0, arg1, arg2 string, arg3 *armsql.DatabaseBlobAuditingPoliciesClientListByDatabaseOptions) *sql.RuntimePagerArmsqlDatabaseBlobAuditingPoliciesClientListByDatabaseResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListByDatabasePager", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*sql.RuntimePagerArmsqlDatabaseBlobAuditingPoliciesClientListByDatabaseResponse)
	return ret0
}

// NewListByDatabasePager indicates an expected call of NewListByDatabasePager.
func (mr *MockDatabaseBlobAuditingPoliciesClientMockRecorder) NewListByDatabasePager(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListByDatabasePager", reflect.TypeOf((*MockDatabaseBlobAuditingPoliciesClient)(nil).NewListByDatabasePager), arg0, arg1, arg2, arg3)
}
