// Code generated by codegen; DO NOT EDIT.

package kms

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/api/iterator"

	"github.com/cloudquery/plugin-sdk/schema"
	"github.com/cloudquery/plugins/source/gcp/client"

	pb "google.golang.org/genproto/googleapis/cloud/kms/v1"
)

func CryptoKeys() *schema.Table {
	return &schema.Table{
		Name:     "gcp_kms_crypto_keys",
		Resolver: fetchCryptoKeys,
		Columns: []schema.Column{
			{
				Name:     "project_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveProject,
			},
			{
				Name:     "name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Name"),
			},
			{
				Name:     "primary",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Primary"),
			},
			{
				Name:     "purpose",
				Type:     schema.TypeInt,
				Resolver: schema.PathResolver("Purpose"),
			},
			{
				Name:     "create_time",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("CreateTime"),
			},
			{
				Name:     "next_rotation_time",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("NextRotationTime"),
			},
			{
				Name:     "version_template",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("VersionTemplate"),
			},
			{
				Name:     "labels",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Labels"),
			},
			{
				Name:     "import_only",
				Type:     schema.TypeBool,
				Resolver: schema.PathResolver("ImportOnly"),
			},
			{
				Name:     "destroy_scheduled_duration",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("DestroyScheduledDuration"),
			},
			{
				Name:     "crypto_key_backend",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("CryptoKeyBackend"),
			},
		},
	}
}

func fetchCryptoKeys(ctx context.Context, meta schema.ClientMeta, r *schema.Resource, res chan<- interface{}) error {
	c := meta.(*client.Client)
	req := &pb.ListCryptoKeysRequest{}
	it := c.Services.KmsKeyManagementClient.ListCryptoKeys(ctx, req)
	for {
		resp, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			return errors.WithStack(err)
		}

		res <- resp

	}
	return nil
}
