// Code generated by codegen; DO NOT EDIT.

package compute

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/api/iterator"

	pb "google.golang.org/genproto/googleapis/cloud/compute/v1"

	"github.com/cloudquery/plugin-sdk/schema"
	"github.com/cloudquery/plugins/source/gcp/client"
)

func Interconnects() *schema.Table {
	return &schema.Table{
		Name:      "gcp_compute_interconnects",
		Resolver:  fetchInterconnects,
		Multiplex: client.ProjectMultiplex,
		Columns: []schema.Column{
			{
				Name:     "project_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveProject,
			},
			{
				Name: "self_link",
				Type: schema.TypeString,
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "admin_enabled",
				Type:     schema.TypeBool,
				Resolver: schema.PathResolver("AdminEnabled"),
			},
			{
				Name:     "circuit_infos",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("CircuitInfos"),
			},
			{
				Name:     "creation_timestamp",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("CreationTimestamp"),
			},
			{
				Name:     "customer_name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("CustomerName"),
			},
			{
				Name:     "description",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Description"),
			},
			{
				Name:     "expected_outages",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("ExpectedOutages"),
			},
			{
				Name:     "google_ip_address",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("GoogleIpAddress"),
			},
			{
				Name:     "google_reference_id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("GoogleReferenceId"),
			},
			{
				Name:     "id",
				Type:     schema.TypeInt,
				Resolver: schema.PathResolver("Id"),
			},
			{
				Name:     "interconnect_attachments",
				Type:     schema.TypeStringArray,
				Resolver: schema.PathResolver("InterconnectAttachments"),
			},
			{
				Name:     "interconnect_type",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("InterconnectType"),
			},
			{
				Name:     "kind",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Kind"),
			},
			{
				Name:     "link_type",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("LinkType"),
			},
			{
				Name:     "location",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Location"),
			},
			{
				Name:     "name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Name"),
			},
			{
				Name:     "noc_contact_email",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("NocContactEmail"),
			},
			{
				Name:     "operational_status",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("OperationalStatus"),
			},
			{
				Name:     "peer_ip_address",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("PeerIpAddress"),
			},
			{
				Name:     "provisioned_link_count",
				Type:     schema.TypeInt,
				Resolver: schema.PathResolver("ProvisionedLinkCount"),
			},
			{
				Name:     "requested_link_count",
				Type:     schema.TypeInt,
				Resolver: schema.PathResolver("RequestedLinkCount"),
			},
			{
				Name:     "satisfies_pzs",
				Type:     schema.TypeBool,
				Resolver: schema.PathResolver("SatisfiesPzs"),
			},
			{
				Name:     "state",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("State"),
			},
		},
	}
}

func fetchInterconnects(ctx context.Context, meta schema.ClientMeta, parent *schema.Resource, res chan<- interface{}) error {
	c := meta.(*client.Client)
	req := &pb.ListInterconnectsRequest{
		Project: c.ProjectId,
	}
	it := c.Services.ComputeInterconnectsClient.List(ctx, req)
	for {
		resp, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			return errors.WithStack(err)
		}

		res <- resp

	}
	return nil
}
