// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cognitiveservices/armcognitiveservices"

func Armcognitiveservices() []*Resource {
	resources := []*Resource{
		{
			NewFunc: armcognitiveservices.NewOperationsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cognitiveservices/armcognitiveservices",
		},
		{
			NewFunc: armcognitiveservices.NewResourceSKUsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cognitiveservices/armcognitiveservices",
		},
		{
			NewFunc: armcognitiveservices.NewAccountsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cognitiveservices/armcognitiveservices",
		},
		{
			NewFunc: armcognitiveservices.NewDeletedAccountsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cognitiveservices/armcognitiveservices",
		},
		{
			NewFunc: armcognitiveservices.NewManagementClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cognitiveservices/armcognitiveservices",
		},
		{
			NewFunc: armcognitiveservices.NewCommitmentPlansClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cognitiveservices/armcognitiveservices",
		},
		{
			NewFunc: armcognitiveservices.NewCommitmentTiersClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cognitiveservices/armcognitiveservices",
		},
		{
			NewFunc: armcognitiveservices.NewDeploymentsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cognitiveservices/armcognitiveservices",
		},
		{
			NewFunc: armcognitiveservices.NewPrivateEndpointConnectionsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cognitiveservices/armcognitiveservices",
		},
		{
			NewFunc: armcognitiveservices.NewPrivateLinkResourcesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cognitiveservices/armcognitiveservices",
		},
	}
	return resources
}

func init() {
	Resources = append(Resources, Armcognitiveservices())
}