// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption"

func Armconsumption() []*Resource {
	resources := []*Resource{
		{
			NewFunc: armconsumption.NewAggregatedCostClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewEventsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewLotsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewMarketplacesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewReservationRecommendationDetailsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewUsageDetailsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewChargesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewReservationsSummariesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewReservationTransactionsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewReservationsDetailsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewBalancesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewBudgetsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewOperationsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewPriceSheetClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewCreditsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewReservationRecommendationsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
		{
			NewFunc: armconsumption.NewTagsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption",
		},
	}
	return resources
}

func init() {
	Resources = append(Resources, Armconsumption())
}