// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dynatrace/armdynatrace"

func Armdynatrace() []*Resource {
	resources := []*Resource{
		{
			NewFunc: armdynatrace.NewOperationsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dynatrace/armdynatrace",
		},
		{
			NewFunc: armdynatrace.NewSingleSignOnClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dynatrace/armdynatrace",
		},
		{
			NewFunc: armdynatrace.NewTagRulesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dynatrace/armdynatrace",
		},
		{
			NewFunc: armdynatrace.NewMonitorsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dynatrace/armdynatrace",
		},
	}
	return resources
}

func init() {
	Resources = append(Resources, Armdynatrace())
}