// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/datalake-store/armdatalakestore"

func Armdatalakestore() []*Resource {
	resources := []*Resource{
		{
			NewFunc: armdatalakestore.NewLocationsClient,
		},
		{
			NewFunc: armdatalakestore.NewOperationsClient,
		},
		{
			NewFunc: armdatalakestore.NewTrustedIDProvidersClient,
		},
		{
			NewFunc: armdatalakestore.NewFirewallRulesClient,
		},
		{
			NewFunc: armdatalakestore.NewVirtualNetworkRulesClient,
		},
		{
			NewFunc: armdatalakestore.NewAccountsClient,
		},
	}
	return resources
}