// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/engagementfabric/armengagementfabric"

func Armengagementfabric() []*Resource {
	resources := []*Resource{
		{
			NewFunc: armengagementfabric.NewSKUsClient,
		},
		{
			NewFunc: armengagementfabric.NewAccountsClient,
		},
		{
			NewFunc: armengagementfabric.NewChannelsClient,
		},
		{
			NewFunc: armengagementfabric.NewOperationsClient,
		},
		{
			NewFunc: armengagementfabric.NewClient,
		},
	}
	return resources
}