// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/frontdoor/armfrontdoor"

func Armfrontdoor() []*Resource {
	resources := []*Resource{
    
		{
			NewFunc: armfrontdoor.NewEndpointsClient,
		},
    
		{
			NewFunc: armfrontdoor.NewManagedRuleSetsClient,
		},
    
		{
			NewFunc: armfrontdoor.NewPreconfiguredEndpointsClient,
		},
    
		{
			NewFunc: armfrontdoor.NewNameAvailabilityClient,
		},
    
		{
			NewFunc: armfrontdoor.NewNetworkExperimentProfilesClient,
		},
    
		{
			NewFunc: armfrontdoor.NewPoliciesClient,
		},
    
		{
			NewFunc: armfrontdoor.NewRulesEnginesClient,
		},
    
		{
			NewFunc: armfrontdoor.NewExperimentsClient,
		},
    
		{
			NewFunc: armfrontdoor.NewFrontDoorsClient,
		},
    
		{
			NewFunc: armfrontdoor.NewFrontendEndpointsClient,
		},
    
		{
			NewFunc: armfrontdoor.NewNameAvailabilityWithSubscriptionClient,
		},
    
		{
			NewFunc: armfrontdoor.NewReportsClient,
		},
    
	}
	return resources
}