// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/hybriddatamanager/armhybriddatamanager"

func Armhybriddatamanager() []*Resource {
	resources := []*Resource{
    
		{
			NewFunc: armhybriddatamanager.NewDataManagersClient,
		},
    
		{
			NewFunc: armhybriddatamanager.NewJobsClient,
		},
    
		{
			NewFunc: armhybriddatamanager.NewPublicKeysClient,
		},
    
		{
			NewFunc: armhybriddatamanager.NewJobDefinitionsClient,
		},
    
		{
			NewFunc: armhybriddatamanager.NewOperationsClient,
		},
    
		{
			NewFunc: armhybriddatamanager.NewDataStoreTypesClient,
		},
    
		{
			NewFunc: armhybriddatamanager.NewDataServicesClient,
		},
    
		{
			NewFunc: armhybriddatamanager.NewDataStoresClient,
		},
    
	}
	return resources
}