// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic"

func Armlogic() []*Resource {
	resources := []*Resource{
		{
			NewFunc: armlogic.NewIntegrationServiceEnvironmentSKUsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewWorkflowRunActionRepetitionsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewWorkflowRunsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewWorkflowVersionsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewIntegrationAccountMapsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewIntegrationAccountPartnersClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewWorkflowRunActionRequestHistoriesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewWorkflowRunActionsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewIntegrationAccountSessionsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewIntegrationServiceEnvironmentManagedApisClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewOperationsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewWorkflowTriggersClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewIntegrationAccountAssembliesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewIntegrationServiceEnvironmentManagedAPIOperationsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewIntegrationAccountCertificatesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewIntegrationAccountsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewWorkflowRunActionScopeRepetitionsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewIntegrationAccountBatchConfigurationsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewWorkflowTriggerHistoriesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewIntegrationServiceEnvironmentsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewWorkflowsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewIntegrationServiceEnvironmentNetworkHealthClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewWorkflowRunActionRepetitionsRequestHistoriesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewWorkflowRunOperationsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewIntegrationAccountSchemasClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewWorkflowVersionTriggersClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
		{
			NewFunc: armlogic.NewIntegrationAccountAgreementsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic",
		},
	}
	return resources
}

func init() {
	Resources = append(Resources, Armlogic())
}