// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcemover/armresourcemover"

func Armresourcemover() []*Resource {
	resources := []*Resource{
		{
			NewFunc: armresourcemover.NewMoveResourcesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcemover/armresourcemover",
		},
		{
			NewFunc: armresourcemover.NewOperationsDiscoveryClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcemover/armresourcemover",
		},
		{
			NewFunc: armresourcemover.NewMoveCollectionsClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcemover/armresourcemover",
		},
		{
			NewFunc: armresourcemover.NewUnresolvedDependenciesClient,
			PkgPath: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcemover/armresourcemover",
		},
	}
	return resources
}

func init() {
	Resources = append(Resources, Armresourcemover())
}