// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/redhatopenshift/armredhatopenshift"

func Armredhatopenshift() []*Resource {
	resources := []*Resource{
		{
			NewFunc: armredhatopenshift.NewOpenShiftClustersClient,
		},
		{
			NewFunc: armredhatopenshift.NewOperationsClient,
		},
	}
	return resources
}