// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/windowsiot/armwindowsiot"

func Armwindowsiot() []*Resource {
	resources := []*Resource{
    
		{
			NewFunc: armwindowsiot.NewOperationsClient,
		},
    
		{
			NewFunc: armwindowsiot.NewServicesClient,
		},
    
	}
	return resources
}