// Code generated by codegen; DO NOT EDIT.
package datalakeanalytics

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/datalake-analytics/armdatalakeanalytics"
)

type DatalakeanalyticsClient struct {
	AccountsClient AccountsClient
}

func NewDatalakeanalyticsClient(subscriptionID string, credentials azcore.TokenCredential, options *arm.ClientOptions) (*DatalakeanalyticsClient, error) {
	var client DatalakeanalyticsClient
	var err error

	client.AccountsClient, err = armdatalakeanalytics.NewAccountsClient(subscriptionID, credentials, options)
	if err != nil {
		return nil, err
	}

	return &client, nil
}
