-- Resource: logic.app_workflows
CREATE TABLE IF NOT EXISTS "azure_logic_app_workflows" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"cq_fetch_date" timestamp without time zone NOT NULL,
	"subscription_id" text,
	"provisioning_state" text,
	"created_time" timestamp without time zone,
	"changed_time" timestamp without time zone,
	"state" text,
	"version" text,
	"access_endpoint" text,
	"endpoints_configuration" jsonb,
	"access_control" jsonb,
	"sku_name" text,
	"sku_plan_id" text,
	"sku_plan_name" text,
	"sku_plan_type" text,
	"integration_account_id" text,
	"integration_account_name" text,
	"integration_account_type" text,
	"integration_service_environment_id" text,
	"integration_service_environment_name" text,
	"integration_service_environment_type" text,
	"definition" jsonb,
	"parameters" jsonb,
	"identity_type" text,
	"identity_tenant_id" uuid,
	"identity_principal_id" uuid,
	"identity_user_assigned_identities" jsonb,
	"id" text,
	"name" text,
	"type" text,
	"location" text,
	"tags" jsonb,
	"diagnostic_settings" jsonb,
	CONSTRAINT azure_logic_app_workflows_pk PRIMARY KEY(cq_fetch_date,subscription_id,id),
	UNIQUE(cq_fetch_date,cq_id)
);
SELECT setup_tsdb_parent('azure_logic_app_workflows');
