// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/botservice/armbotservice"

func Armbotservice() []Table {
	tables := []Table{
		{
      Name: "bot",
      Struct: &armbotservice.Bot{},
      ResponseStruct: &armbotservice.BotsClientListResponse{},
      Client: &armbotservice.BotsClient{},
      ListFunc: (&armbotservice.BotsClient{}).NewListPager,
			NewFunc: armbotservice.NewBotsClient,
		},
		{
      Name: "operation_entity",
      Struct: &armbotservice.OperationEntity{},
      ResponseStruct: &armbotservice.OperationsClientListResponse{},
      Client: &armbotservice.OperationsClient{},
      ListFunc: (&armbotservice.OperationsClient{}).NewListPager,
			NewFunc: armbotservice.NewOperationsClient,
		},
		{
      Name: "private_endpoint_connection",
      Struct: &armbotservice.PrivateEndpointConnection{},
      ResponseStruct: &armbotservice.PrivateEndpointConnectionsClientListResponse{},
      Client: &armbotservice.PrivateEndpointConnectionsClient{},
      ListFunc: (&armbotservice.PrivateEndpointConnectionsClient{}).NewListPager,
			NewFunc: armbotservice.NewPrivateEndpointConnectionsClient,
		},
	}

	for i := range tables {
		tables[i].Service = "armbotservice"
		tables[i].Template = "list"
	}
	return tables
}

func init() {
  Tables = append(Tables, Armbotservice()...)
}