// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/eventhub/armeventhub"

func Armeventhub() []Table {
	tables := []Table{
		{
      Name: "arm_disaster_recovery",
      Struct: &armeventhub.ArmDisasterRecovery{},
      ResponseStruct: &armeventhub.DisasterRecoveryConfigsClientListResponse{},
      Client: &armeventhub.DisasterRecoveryConfigsClient{},
      ListFunc: (&armeventhub.DisasterRecoveryConfigsClient{}).NewListPager,
			NewFunc: armeventhub.NewDisasterRecoveryConfigsClient,
			URL: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EventHub/namespaces/{namespaceName}/disasterRecoveryConfigs",
		},
		{
      Name: "eh_namespace",
      Struct: &armeventhub.EHNamespace{},
      ResponseStruct: &armeventhub.NamespacesClientListResponse{},
      Client: &armeventhub.NamespacesClient{},
      ListFunc: (&armeventhub.NamespacesClient{}).NewListPager,
			NewFunc: armeventhub.NewNamespacesClient,
			URL: "/subscriptions/{subscriptionId}/providers/Microsoft.EventHub/namespaces",
		},
		{
      Name: "private_endpoint_connection",
      Struct: &armeventhub.PrivateEndpointConnection{},
      ResponseStruct: &armeventhub.PrivateEndpointConnectionsClientListResponse{},
      Client: &armeventhub.PrivateEndpointConnectionsClient{},
      ListFunc: (&armeventhub.PrivateEndpointConnectionsClient{}).NewListPager,
			NewFunc: armeventhub.NewPrivateEndpointConnectionsClient,
			URL: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EventHub/namespaces/{namespaceName}/privateEndpointConnections",
		},
	}

	for i := range tables {
		tables[i].Service = "armeventhub"
		tables[i].Template = "list"
	}
	return tables
}

func init() {
  Tables = append(Tables, Armeventhub()...)
}