// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armlinks"

func Armlinks() []Table {
	tables := []Table{
		{
      Name: "operation",
      Struct: &armlinks.Operation{},
      ResponseStruct: &armlinks.OperationsClientListResponse{},
      Client: &armlinks.OperationsClient{},
      ListFunc: (&armlinks.OperationsClient{}).NewListPager,
			NewFunc: armlinks.NewOperationsClient,
		},
	}

	for i := range tables {
		tables[i].Service = "armlinks"
		tables[i].Template = "list"
	}
	return tables
}

func init() {
  Tables = append(Tables, Armlinks()...)
}