// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armpolicy"

func Armpolicy() []Table {
	tables := []Table{
		{
      Name: "set_definition",
      Struct: &armpolicy.SetDefinition{},
      ResponseStruct: &armpolicy.SetDefinitionsClientListResponse{},
      Client: &armpolicy.SetDefinitionsClient{},
      ListFunc: (&armpolicy.SetDefinitionsClient{}).NewListPager,
			NewFunc: armpolicy.NewSetDefinitionsClient,
		},
		{
      Name: "exemption",
      Struct: &armpolicy.Exemption{},
      ResponseStruct: &armpolicy.ExemptionsClientListResponse{},
      Client: &armpolicy.ExemptionsClient{},
      ListFunc: (&armpolicy.ExemptionsClient{}).NewListPager,
			NewFunc: armpolicy.NewExemptionsClient,
		},
		{
      Name: "assignment",
      Struct: &armpolicy.Assignment{},
      ResponseStruct: &armpolicy.AssignmentsClientListResponse{},
      Client: &armpolicy.AssignmentsClient{},
      ListFunc: (&armpolicy.AssignmentsClient{}).NewListPager,
			NewFunc: armpolicy.NewAssignmentsClient,
		},
		{
      Name: "data_policy_manifest",
      Struct: &armpolicy.DataPolicyManifest{},
      ResponseStruct: &armpolicy.DataPolicyManifestsClientListResponse{},
      Client: &armpolicy.DataPolicyManifestsClient{},
      ListFunc: (&armpolicy.DataPolicyManifestsClient{}).NewListPager,
			NewFunc: armpolicy.NewDataPolicyManifestsClient,
		},
		{
      Name: "definition",
      Struct: &armpolicy.Definition{},
      ResponseStruct: &armpolicy.DefinitionsClientListResponse{},
      Client: &armpolicy.DefinitionsClient{},
      ListFunc: (&armpolicy.DefinitionsClient{}).NewListPager,
			NewFunc: armpolicy.NewDefinitionsClient,
		},
	}

	for i := range tables {
		tables[i].Service = "armpolicy"
		tables[i].Template = "list"
	}
	return tables
}

func init() {
  Tables = append(Tables, Armpolicy()...)
}