// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/redisenterprise/armredisenterprise"

func Armredisenterprise() []Table {
	tables := []Table{
		{
      Name: "private_endpoint_connection",
      Struct: &armredisenterprise.PrivateEndpointConnection{},
      ResponseStruct: &armredisenterprise.PrivateEndpointConnectionsClientListResponse{},
      Client: &armredisenterprise.PrivateEndpointConnectionsClient{},
      ListFunc: (&armredisenterprise.PrivateEndpointConnectionsClient{}).NewListPager,
			NewFunc: armredisenterprise.NewPrivateEndpointConnectionsClient,
		},
		{
      Name: "cluster",
      Struct: &armredisenterprise.Cluster{},
      ResponseStruct: &armredisenterprise.ClientListResponse{},
      Client: &armredisenterprise.Client{},
      ListFunc: (&armredisenterprise.Client{}).NewListPager,
			NewFunc: armredisenterprise.NewClient,
		},
		{
      Name: "operation",
      Struct: &armredisenterprise.Operation{},
      ResponseStruct: &armredisenterprise.OperationsClientListResponse{},
      Client: &armredisenterprise.OperationsClient{},
      ListFunc: (&armredisenterprise.OperationsClient{}).NewListPager,
			NewFunc: armredisenterprise.NewOperationsClient,
		},
	}

	for i := range tables {
		tables[i].Service = "armredisenterprise"
		tables[i].Template = "list"
	}
	return tables
}

func init() {
  Tables = append(Tables, Armredisenterprise()...)
}