// Code generated by codegen; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/scvmm/armscvmm"

func Armscvmm() []Table {
	tables := []Table{
		{
      Name: "resource_provider_operation",
      Struct: &armscvmm.ResourceProviderOperation{},
      ResponseStruct: &armscvmm.OperationsClientListResponse{},
      Client: &armscvmm.OperationsClient{},
      ListFunc: (&armscvmm.OperationsClient{}).NewListPager,
			NewFunc: armscvmm.NewOperationsClient,
		},
	}

	for i := range tables {
		tables[i].Service = "armscvmm"
		tables[i].Template = "list"
	}
	return tables
}

func init() {
  Tables = append(Tables, Armscvmm()...)
}