// Code generated by codegen1; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dnsresolver/armdnsresolver"

func init() {
	tables := []Table{
		{
			Service:        "armdnsresolver",
			Name:           "dns_forwarding_rulesets",
			Struct:         &armdnsresolver.DNSForwardingRuleset{},
			ResponseStruct: &armdnsresolver.DNSForwardingRulesetsClientListResponse{},
			Client:         &armdnsresolver.DNSForwardingRulesetsClient{},
			ListFunc:       (&armdnsresolver.DNSForwardingRulesetsClient{}).NewListPager,
			NewFunc:        armdnsresolver.NewDNSForwardingRulesetsClient,
			URL:            "/subscriptions/{subscriptionId}/providers/Microsoft.Network/dnsForwardingRulesets",
			Multiplex:      `client.SubscriptionMultiplexRegisteredNamespace(client.NamespaceMicrosoft_Network)`,
			ExtraColumns:   DefaultExtraColumns,
		},
		{
			Service:        "armdnsresolver",
			Name:           "dns_resolvers",
			Struct:         &armdnsresolver.DNSResolver{},
			ResponseStruct: &armdnsresolver.DNSResolversClientListResponse{},
			Client:         &armdnsresolver.DNSResolversClient{},
			ListFunc:       (&armdnsresolver.DNSResolversClient{}).NewListPager,
			NewFunc:        armdnsresolver.NewDNSResolversClient,
			URL:            "/subscriptions/{subscriptionId}/providers/Microsoft.Network/dnsResolvers",
			Multiplex:      `client.SubscriptionMultiplexRegisteredNamespace(client.NamespaceMicrosoft_Network)`,
			ExtraColumns:   DefaultExtraColumns,
		},
	}
	Tables = append(Tables, tables...)
}
