// Code generated by codegen1; DO NOT EDIT.
package recipes

import "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/providerhub/armproviderhub"

func init() {
	tables := []Table{
		{
			Service:        "armproviderhub",
			Name:           "provider_registrations",
			Struct:         &armproviderhub.ProviderRegistration{},
			ResponseStruct: &armproviderhub.ProviderRegistrationsClientListResponse{},
			Client:         &armproviderhub.ProviderRegistrationsClient{},
			ListFunc:       (&armproviderhub.ProviderRegistrationsClient{}).NewListPager,
			NewFunc:        armproviderhub.NewProviderRegistrationsClient,
			URL:            "/subscriptions/{subscriptionId}/providers/Microsoft.ProviderHub/providerRegistrations",
			Multiplex:      `client.SubscriptionMultiplexRegisteredNamespace(client.NamespaceMicrosoft_ProviderHub)`,
			ExtraColumns:   DefaultExtraColumns,
		},
	}
	Tables = append(Tables, tables...)
}
