// Code generated by codegen; DO NOT EDIT.

package monitor

import (
	"testing"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	api "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor"
	"github.com/cloudquery/cloudquery/plugins/source/azure/client"
	mocks "github.com/cloudquery/cloudquery/plugins/source/azure/client/mocks/monitor"
	service "github.com/cloudquery/cloudquery/plugins/source/azure/client/services/monitor"
	"github.com/cloudquery/plugin-sdk/faker"
	"github.com/golang/mock/gomock"
	"github.com/stretchr/testify/require"
)

func buildActivityLogAlerts(t *testing.T, ctrl *gomock.Controller) *client.Services {
	mockActivityLogAlertsClient := mocks.NewMockActivityLogAlertsClient(ctrl)

	var response api.ActivityLogAlertsClientListBySubscriptionIDResponse
	require.NoError(t, faker.FakeObject(&response))
	// Use correct Azure ID format
	const id = "/subscriptions/test/resourceGroups/test/providers/test/test/test"
	response.Value[0].ID = to.Ptr(id)

	mockActivityLogAlertsClient.EXPECT().NewListBySubscriptionIDPager(gomock.Any()).
		Return(client.CreatePager(response)).MinTimes(1)

	monitorClient := &service.MonitorClient{
		ActivityLogAlertsClient: mockActivityLogAlertsClient,
	}

	c := &client.Services{Monitor: monitorClient}

	return c
}

func TestActivityLogAlerts(t *testing.T) {
	client.MockTestHelper(t, ActivityLogAlerts(), buildActivityLogAlerts)
}
