package services

import (
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/appservice/armappservice/v2"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/authorization/armauthorization/v2"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/batch/armbatch"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cdn/armcdn"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v4"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerregistry/armcontainerregistry"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v2"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cosmos/armcosmos/v2"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/datalake-analytics/armdatalakeanalytics"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/datalake-store/armdatalakestore"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/eventhub/armeventhub"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/frontdoor/armfrontdoor"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/iothub/armiothub"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/keyvault/armkeyvault"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/logic/armlogic"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/mariadb/armmariadb"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/mysql/armmysql"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v2"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/postgresql/armpostgresql"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/redis/armredis/v2"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armlinks"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armpolicy"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/search/armsearch"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/security/armsecurity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/servicebus/armservicebus/v2"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/streamanalytics/armstreamanalytics"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/subscription/armsubscription"
)

var constructors = []any{
	armappservice.NewWebAppsClient,
	armauthorization.NewRoleAssignmentsClient,
	armauthorization.NewRoleDefinitionsClient,
	armbatch.NewAccountClient,
	armcdn.NewCustomDomainsClient,
	armcdn.NewEndpointsClient,
	armcdn.NewProfilesClient,
	armcdn.NewRoutesClient,
	armcdn.NewRuleSetsClient,
	armcdn.NewRulesClient,
	armcdn.NewSecurityPoliciesClient,
	armcompute.NewDisksClient,
	armcompute.NewVirtualMachineScaleSetsClient,
	armcompute.NewVirtualMachinesClient,
	armcontainerregistry.NewRegistriesClient,
	armcontainerregistry.NewReplicationsClient,
	armcontainerservice.NewManagedClustersClient,
	armcosmos.NewDatabaseAccountsClient,
	armcosmos.NewMongoDBResourcesClient,
	armcosmos.NewSQLResourcesClient,
	armdatalakeanalytics.NewAccountsClient,
	armdatalakestore.NewAccountsClient,
	armeventhub.NewNamespacesClient,
	armfrontdoor.NewFrontDoorsClient,
	armiothub.NewResourceClient,
	armkeyvault.NewKeysClient,
	armkeyvault.NewManagedHsmsClient,
	armkeyvault.NewSecretsClient,
	armkeyvault.NewVaultsClient,
	armlogic.NewWorkflowsClient,
	armmariadb.NewConfigurationsClient,
	armmariadb.NewServersClient,
	armmonitor.NewActivityLogAlertsClient,
	armmonitor.NewActivityLogsClient,
	armmonitor.NewDiagnosticSettingsClient,
	armmonitor.NewLogProfilesClient,
	armmysql.NewConfigurationsClient,
	armmysql.NewServersClient,
	armnetwork.NewExpressRouteCircuitsClient,
	armnetwork.NewExpressRouteGatewaysClient,
	armnetwork.NewExpressRoutePortsClient,
	armnetwork.NewFlowLogsClient,
	armnetwork.NewInterfacesClient,
	armnetwork.NewPublicIPAddressesClient,
	armnetwork.NewRouteFiltersClient,
	armnetwork.NewRouteTablesClient,
	armnetwork.NewSecurityGroupsClient,
	armnetwork.NewVirtualNetworkGatewayConnectionsClient,
	armnetwork.NewVirtualNetworkGatewaysClient,
	armnetwork.NewVirtualNetworksClient,
	armnetwork.NewWatchersClient,
	armpostgresql.NewConfigurationsClient,
	armpostgresql.NewFirewallRulesClient,
	armpostgresql.NewServersClient,
	armredis.NewClient,
	armresources.NewClient,
	armresources.NewResourceGroupsClient,
	armlinks.NewResourceLinksClient,
	armpolicy.NewAssignmentsClient,
	armsearch.NewServicesClient,
	armsecurity.NewAssessmentsClient,
	armsecurity.NewAutoProvisioningSettingsClient,
	armsecurity.NewContactsClient,
	armsecurity.NewJitNetworkAccessPoliciesClient,
	armsecurity.NewPricingsClient,
	armsecurity.NewSettingsClient,
	armservicebus.NewNamespacesClient,
	armservicebus.NewTopicsClient,
	armsql.NewDatabaseBlobAuditingPoliciesClient,
	armsql.NewDatabaseSecurityAlertPoliciesClient,
	armsql.NewDatabaseVulnerabilityAssessmentScansClient,
	armsql.NewDatabaseVulnerabilityAssessmentsClient,
	armsql.NewDatabasesClient,
	armsql.NewEncryptionProtectorsClient,
	armsql.NewFirewallRulesClient,
	armsql.NewLongTermRetentionPoliciesClient,
	armsql.NewManagedDatabaseVulnerabilityAssessmentScansClient,
	armsql.NewManagedDatabaseVulnerabilityAssessmentsClient,
	armsql.NewManagedDatabasesClient,
	armsql.NewManagedInstanceEncryptionProtectorsClient,
	armsql.NewManagedInstanceVulnerabilityAssessmentsClient,
	armsql.NewManagedInstancesClient,
	armsql.NewServerAzureADAdministratorsClient,
	armsql.NewServerBlobAuditingPoliciesClient,
	armsql.NewServerDevOpsAuditSettingsClient,
	armsql.NewServerSecurityAlertPoliciesClient,
	armsql.NewServerVulnerabilityAssessmentsClient,
	armsql.NewServersClient,
	armsql.NewTransparentDataEncryptionsClient,
	armsql.NewVirtualNetworkRulesClient,
	armstorage.NewAccountsClient,
	armstorage.NewBlobContainersClient,
	armstorage.NewBlobServicesClient,
	armstreamanalytics.NewStreamingJobsClient,
	armsubscription.NewSubscriptionsClient,
	armsubscription.NewTenantsClient,
}
