// Code generated by codegen; DO NOT EDIT.

package services

import (
	"context"
	"github.com/cloudquery/cloudquery/plugins/source/heroku/client"
	"github.com/cloudquery/cq-provider-sdk/provider/schema"
	"github.com/pkg/errors"
)

func BuildpackInstallations() *schema.Table {
	return &schema.Table{
		Name:      "heroku_buildpack_installations",
		Resolver:  fetchBuildpackInstallations,
		Multiplex: client.NoMultiplex,
		Columns: []schema.Column{
			{
				Name:     "buildpack",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Buildpack"),
			},
			{
				Name:     "ordinal",
				Type:     schema.TypeInt,
				Resolver: schema.PathResolver("Ordinal"),
			},
		},
	}
}

func fetchBuildpackInstallations(ctx context.Context, meta schema.ClientMeta, _ *schema.Resource, res chan<- interface{}) error {
	c := meta.(*client.Client)
	items, err := c.Heroku.AppList(ctx, nil)
	if err != nil {
		return errors.WithStack(err)
	}

	for _, it := range items {
		v, err := c.Heroku.BuildpackInstallationList(ctx, it.ID, nil)
		if err != nil {
			return errors.WithStack(err)
		}
		res <- v
	}
	return nil
}
