// Code generated by codegen; DO NOT EDIT.

package appservice

import (
	"github.com/cloudquery/cloudquery/plugins/source/azure/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func functions() *schema.Table {
	return &schema.Table{
		Name:        "azure_appservice_functions",
		Description: `https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/appservice/armappservice/v2#FunctionEnvelope`,
		Resolver:    fetchFunctions,
		Columns: []schema.Column{
			{
				Name:        "subscription_id",
				Type:        schema.TypeString,
				Resolver:    client.SubscriptionIDResolver,
				Description: `Azure subscription ID`,
			},
			{
				Name:     "kind",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Kind"),
			},
			{
				Name:     "config_href",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Properties.ConfigHref"),
			},
			{
				Name:     "files",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Properties.Files"),
			},
			{
				Name:     "function_app_id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Properties.FunctionAppID"),
			},
			{
				Name:     "href",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Properties.Href"),
			},
			{
				Name:     "invoke_url_template",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Properties.InvokeURLTemplate"),
			},
			{
				Name:     "is_disabled",
				Type:     schema.TypeBool,
				Resolver: schema.PathResolver("Properties.IsDisabled"),
			},
			{
				Name:     "language",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Properties.Language"),
			},
			{
				Name:     "script_href",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Properties.ScriptHref"),
			},
			{
				Name:     "script_root_path_href",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Properties.ScriptRootPathHref"),
			},
			{
				Name:     "secrets_file_href",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Properties.SecretsFileHref"),
			},
			{
				Name:     "test_data",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Properties.TestData"),
			},
			{
				Name:     "test_data_href",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Properties.TestDataHref"),
			},
			{
				Name:     "id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ID"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Name"),
			},
			{
				Name:     "type",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Type"),
			},
			{
				Name:     "site_id",
				Type:     schema.TypeString,
				Resolver: schema.ParentColumnResolver("id"),
			},
		},
	}
}
