{
 "title": "CloudQuery Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "plugin", "label": "Plugin", "query": { "query": "label_values(exported_job)" } },
   { "name": "table", "label": "Table", "query": { "query": "label_values(sync_table_name)" } },
   { "name": "clientid", "label": "Client ID", "query": { "query": "label_values(sync_client_id)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "options": {
    "content": "<p style=\"text-align: center\">\n  <img alt=\"CloudQueryLogo\" src=\"https://docs.cloudquery.io/images/brand-logo/cloudquery_logo_png_dark_background.png\" />\n</p>\n\nUse this dashboard to get insights into CloudQuery syncs and optimize them. For more information on setting up CloudQuery with Grafana, see the [CloudQuery documentation](https://docs.cloudquery.io//docs/advanced-topics/monitoring/otel-grafana).\n\n## Links\n\n- [Home](https://www.cloudquery.io/)\n- [Download CLI](https://www.cloudquery.io/download)\n- [Register](https://www.cloudquery.io/auth/register)\n- [Pricing](https://www.cloudquery.io/pricing)"
   }
  },
  {
   "title": "Total resources by table",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum(sync_table_resources_total{exported_job=~\"cloudquery-.*$plugin.*\", sync_table_name=~\".*$table.*\", sync_client_id=~\".*$clientid.*\"}) by (sync_table_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total errors by table",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(sync_table_errors_total{exported_job=~\"cloudquery-.*$plugin.*\", sync_table_name=~\".*$table.*\", sync_client_id=~\".*$clientid.*\"}) by (sync_table_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Slowest tables over time (p95)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "filters": [
      { "id": "d894dd32", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{span.sync.client.id=~\".*$clientid.*\" && resource.service.name=~\"cloudquery-.*$plugin.*\" && name=~\"sync.table.*$table.*\"} | quantile_over_time(duration, 0.95) by (name)",
     "spss": 3,
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Tables By Sync Duration",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "filters": [
      {
       "id": "1b3d0e9e",
       "operator": "=~",
       "scope": "span",
       "tag": "sync.client.id",
       "value": [
        "\".*clientid.*\""
       ]
      },
      {
       "id": "service-name",
       "operator": "=~",
       "scope": "resource",
       "tag": "service.name",
       "value": [
        "\"cloudquery-.*$plugin.*\""
       ]
      },
      {
       "id": "span-name",
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "value": [
        "\".*$table.*\""
       ]
      }
     ],
     "limit": 20,
     "query": "{span.sync.client.id=~\".*$clientid.*\" && resource.service.name=~\"cloudquery-.*$plugin.*\" && name=~\"sync.table.*$table.*\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Sync Time Over Time For Plugin ($plugin)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "repeat": "plugin",
   "targets": [
    {
     "limit": 20,
     "query": "{resource.service.name=~\"cloudquery-.*$plugin.*\" && name=\"sync\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "{job=~\"cloudquery-.*$plugin.*\"} | json | attributes_client =~ `.*$clientid.*` | attributes_table =~ `.*$table.*`"
      }
     ]
    }
   ]
  }
 ]
}