{
 "title": "CloudQuery Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "plugin",
    "label": "Plugin",
    "query": {}
   },
   {
    "name": "table",
    "label": "Table",
    "query": {}
   },
   {
    "name": "clientid",
    "label": "Client ID",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total resources by table over time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sync_table_resources_total{exported_job=~\"cloudquery-.*$plugin.*\", sync_table_name=~\".*$table.*\", sync_client_id=~\".*$clientid.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total errors by table over time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sync_table_errors_total{exported_job=~\"cloudquery-.*$plugin.*\", sync_table_name=~\".*$table.*\", sync_client_id=~\".*$clientid.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tables By Sync Duration",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "filters": [
      {
       "id": "1b3d0e9e",
       "operator": "=~",
       "scope": "span",
       "tag": "sync.client.id",
       "value": [
        "\".*clientid.*\""
       ]
      },
      {
       "id": "service-name",
       "operator": "=~",
       "scope": "resource",
       "tag": "service.name",
       "value": [
        "\"cloudquery-.*$plugin.*\""
       ]
      },
      {
       "id": "span-name",
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "value": [
        "\".*$table.*\""
       ]
      }
     ],
     "limit": 20,
     "query": "{span.sync.client.id=~\".*$clientid.*\" && resource.service.name=~\"cloudquery-.*$plugin.*\" && name=~\"sync.table.*$table.*\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Sync Time by Plugin Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "filters": [
      { "id": "96ca625e", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{resource.service.name=~\"cloudquery-.*$plugin.*\" && name=\"sync\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "{job=~\"cloudquery-.*$plugin.*\"} | json | attributes_client =~ `.*$clientid.*` | attributes_table =~ `.*$table.*`"
      }
     ]
    }
   ]
  }
 ]
}