package client

type GcpService string

const (
	BigQueryService             GcpService = "bigquery.googleapis.com"
	CloudBillingService         GcpService = "cloudbilling.googleapis.com"
	CloudFunctionsService       GcpService = "cloudfunctions.googleapis.com"
	CloudKmsService             GcpService = "cloudkms.googleapis.com"
	CloudResourceManagerService GcpService = "cloudresourcemanager.googleapis.com"
	ComputeService              GcpService = "compute.googleapis.com"
	DnsService                  GcpService = "dns.googleapis.com"
	DomainsService              GcpService = "domains.googleapis.com"
	IamService                  GcpService = "iam.googleapis.com"
	KubernetesService           GcpService = "container.googleapis.com"
	LoggingService              GcpService = "logging.googleapis.com"
	MonitoringService           GcpService = "monitoring.googleapis.com"
	SqlAdminService             GcpService = "sqladmin.googleapis.com"
	StorageService              GcpService = "storage-api.googleapis.com"
	ContainerAnalysisService    GcpService = "containeranalysis.googleapis.com"
	RediService                 GcpService = "redis.googleapis.com"
	APIKeysService              GcpService = "apikeys.googleapis.com"
	AppEngineService            GcpService = "appengine.googleapis.com"
	ArtifactRegistryService     GcpService = "artifactregistry.googleapis.com"

	BigQueryDataTransferService      GcpService = "bigquerydatatransfer.googleapis.com"
	BigQueryMigrationService         GcpService = "bigquerymigration.googleapis.com"
	BigQueryStorageService           GcpService = "bigquerystorage.googleapis.com"
	GoogleCloudAPIService            GcpService = "cloudapis.googleapis.com"
	CloudBuildService                GcpService = "cloudbuild.googleapis.com"
	CloudDebuggerService             GcpService = "clouddebugger.googleapis.com"
	CloudKMSService                  GcpService = "cloudkms.googleapis.com"
	CloudSchedulerService            GcpService = "cloudscheduler.googleapis.com"
	CloudTraceService                GcpService = "cloudtrace.googleapis.com"
	ComputeEngineService             GcpService = "compute.googleapis.com"
	KubernetesEngineService          GcpService = "container.googleapis.com"
	ContainerFileSystemService       GcpService = "containerfilesystem.googleapis.com"
	ContainerRegistryService         GcpService = "containerregistry.googleapis.com"
	ContainerScanningService         GcpService = "containerscanning.googleapis.com"
	CloudDatastoreService            GcpService = "datastore.googleapis.com"
	LookerStudioService              GcpService = "datastudio.googleapis.com"
	CloudDeploymentManagerService    GcpService = "deploymentmanager.googleapis.com"
	CloudDNSService                  GcpService = "dns.googleapis.com"
	CloudDomainsService              GcpService = "domains.googleapis.com"
	FirebaseCloudMessagingService    GcpService = "fcm.googleapis.com"
	FirebaseManagementService        GcpService = "firebase.googleapis.com"
	FirebaseDynamicLinksService      GcpService = "firebasedynamiclinks.googleapis.com"
	FirebaseHostingService           GcpService = "firebasehosting.googleapis.com"
	FirebaseInstallationsService     GcpService = "firebaseinstallations.googleapis.com"
	FirebaseRemoteConfigService      GcpService = "firebaseremoteconfig.googleapis.com"
	FirebaseRulesService             GcpService = "firebaserules.googleapis.com"
	CloudFirestoreService            GcpService = "firestore.googleapis.com"
	CloudMessaging                   GcpService = "googlecloudmessaging.googleapis.com"
	IAMService                       GcpService = "iam.googleapis.com"
	IAMCredentialsService            GcpService = "iamcredentials.googleapis.com"
	CloudIAPService                  GcpService = "iap.googleapis.com"
	IdentityToolkitService           GcpService = "identitytoolkit.googleapis.com"
	CloudLoggingService              GcpService = "logging.googleapis.com"
	CloudMonitoringService           GcpService = "monitoring.googleapis.com"
	NetworkManagementService         GcpService = "networkmanagement.googleapis.com"
	OnDemandScanningService          GcpService = "ondemandscanning.googleapis.com"
	CloudOSLoginService              GcpService = "oslogin.googleapis.com"
	CloudPubSubService               GcpService = "pubsub.googleapis.com"
	CloudRunService                  GcpService = "run.googleapis.com"
	CloudRuntimeConfigurationService GcpService = "runtimeconfig.googleapis.com"
	SecretManagerService             GcpService = "secretmanager.googleapis.com"
	TokenServiceService              GcpService = "securetoken.googleapis.com"
	ServiceManagementService         GcpService = "servicemanagement.googleapis.com"
	ServiceNetworkingService         GcpService = "servicenetworking.googleapis.com"
	ServiceUsageService              GcpService = "serviceusage.googleapis.com"
	CloudSQLAdminService             GcpService = "sqladmin.googleapis.com"
	CloudSQLService                  GcpService = "sql-component.googleapis.com"
	CloudStorageService              GcpService = "storage.googleapis.com"
	CloudTestingAPI                  GcpService = "testing.googleapis.com"
)
