// Code generated by codegen; DO NOT EDIT.

package glue

import (
	"github.com/cloudquery/cloudquery/plugins/source/aws/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func DatacatalogEncryptionSettings() *schema.Table {
	return &schema.Table{
		Name:      "aws_glue_datacatalog_encryption_settings",
		Resolver:  fetchGlueDatacatalogEncryptionSettings,
		Multiplex: client.ServiceAccountRegionMultiplexer("glue"),
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "region",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSRegion,
			},
			{
				Name:     "connection_password_encryption",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("ConnectionPasswordEncryption"),
			},
			{
				Name:     "encryption_at_rest",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("EncryptionAtRest"),
			},
		},
	}
}
