// Code generated by codegen; DO NOT EDIT.

package lambda

import (
	"github.com/cloudquery/cloudquery/plugins/source/aws/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func Layers() *schema.Table {
	return &schema.Table{
		Name:        "aws_lambda_layers",
		Description: `https://docs.aws.amazon.com/lambda/latest/dg/API_LayersListItem.html`,
		Resolver:    fetchLambdaLayers,
		Multiplex:   client.ServiceAccountRegionMultiplexer("lambda"),
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
			},
			{
				Name:     "region",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSRegion,
			},
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("LayerArn"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "latest_matching_version",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("LatestMatchingVersion"),
			},
			{
				Name:     "layer_arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("LayerArn"),
			},
			{
				Name:     "layer_name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("LayerName"),
			},
		},

		Relations: []*schema.Table{
			LayerVersions(),
		},
	}
}
