export const INTEGRATIONS = [
  {
    title: "Alibaba Cloud",
    name: "Alibaba Cloud",
    logo: "/images/logos/plugins/alicloud.svg",
    logoDark: "/images/logos/plugins/alicloud-dark.svg",
    id: "alicloud",
  },
  {
    title: "Amazon Web Services",
    name: "AWS",
    logo: "/images/logos/plugins/aws.svg",
    logoDark: "/images/logos/plugins/aws-dark.svg",
    id: "aws",
  },
  {
    title: "Azure",
    name: "Azure",
    logo: "/images/logos/plugins/azure.svg",
    id: "azure",
  },
  {
    title: "Azure DevOps",
    name: "Azure DevOps",
    logo: "/images/logos/plugins/azuredevops.svg",
    id: "azuredevops",
  },
  {
    title: "Cloudflare",
    name: "Cloudflare",
    logo: "/images/logos/plugins/cloudflare.svg",
    id: "cloudflare",
  },
  {
    title: "Datadog",
    name: "Datadog",
    logo: "/images/logos/plugins/datadog.svg",
    logoDark: "/images/logos/plugins/datadog-dark.svg",
    id: "datadog",
  },
  {
    title: "Digital Ocean",
    name: "Digital Ocean",
    logo: "/images/logos/plugins/digitalocean.svg",
    id: "digitalocean",
  },
  {
    title: "Fastly",
    name: "Fastly",
    logo: "/images/logos/plugins/fastly.svg",
    id: "fastly",
  },
  {
    title: "Gandi",
    name: "Gandi",
    logo: "/images/logos/plugins/gandi.svg",
    logoDark: "/images/logos/plugins/gandi-dark.svg",
    id: "gandi",
  },
  {
    title: "Google Cloud Platform",
    name: "GCP",
    logo: "/images/logos/plugins/gcp.svg",
    id: "gcp",
  },
  {
    title: "GitHub",
    name: "GitHub",
    logo: "/images/logos/plugins/github.svg",
    logoDark: "/images/logos/plugins/github-dark.svg",
    id: "github",
  },
  {
    title: "GitLab",
    name: "GitLab",
    logo: "/images/logos/plugins/gitlab.svg",
    id: "gitlab",
  },
  {
    title: "Hacker News",
    name: "Hacker News",
    logo: "/images/logos/plugins/hackernews.svg",
    id: "hackernews",
  },
  {
    title: "Heroku",
    name: "Heroku",
    logo: "/images/logos/plugins/heroku.svg",
    id: "heroku",
  },
  {
    title: "HubSpot",
    name: "HubSpot",
    logo: "/images/logos/plugins/hubspot.svg",
    id: "hubspot",
  },
  {
    title: "Kubernetes",
    name: "Kubernetes",
    logo: "/images/logos/plugins/kubernetes.svg",
    id: "k8s",
  },
  {
    title: "LaunchDarkly",
    name: "LaunchDarkly",
    logo: "/images/logos/plugins/launchdarkly.svg",
    logoDark: "/images/logos/plugins/launchdarkly-dark.svg",
    id: "launchdarkly",
  },
  {
    title: "Mixpanel",
    name: "Mixpanel",
    logo: "/images/logos/plugins/mixpanel.svg",
    logoDark: "/images/logos/plugins/mixpanel-dark.svg",
    id: "mixpanel",
  },
  {
    title: "Okta",
    name: "Okta",
    logo: "/images/logos/plugins/okta.svg",
    id: "okta",
  },
  {
    title: "Oracle",
    name: "Oracle",
    logo: "/images/logos/plugins/oracle.svg",
    id: "oracle",
  },
  {
    title: "Pagerduty",
    name: "Pagerduty",
    logo: "/images/logos/plugins/pagerduty.svg",
    id: "pagerduty",
  },
  {
    title: "Plausible Analytics",
    name: "Plausible Analytics",
    logo: "/images/logos/plugins/plausibleanalytics.svg",
    id: "plausible",
  },
  {
    title: "Salesforce",
    name: "Salesforce",
    logo: "/images/logos/plugins/salesforce.svg",
    id: "salesforce",
  },
  {
    title: "Swetrix",
    name: "Swetrix",
    logo: "/images/logos/plugins/swetrix.svg",
    href: "https://github.com/swetrix/cq-source-swetrix",
    id: "swetrix",
  },
  {
    title: "Scaleway",
    name: "Scaleway",
    logo: "/images/logos/plugins/scaleway.svg",
    href: "https://github.com/scaleway/cq-source-scaleway",
    id: "scaleway",
  },
  {
    title: "Shopify",
    name: "Shopify",
    logo: "/images/logos/plugins/shopify.svg",
    id: "shopify",
  },
  {
    title: "Simple Analytics",
    name: "Simple Analytics",
    logo: "/images/logos/plugins/simpleanalytics.svg",
    href: "https://github.com/simpleanalytics/cq-source-simpleanalytics",
    id: "simpleanlaytics",
  },
  {
    title: "Slack",
    name: "Slack",
    logo: "/images/logos/plugins/slack.svg",
    id: "slack",
  },
  {
    title: "Snyk",
    name: "Snyk",
    logo: "/images/logos/plugins/snyk.svg",
    id: "snyk",
  },
  {
    title: "Stripe",
    name: "Stripe",
    logo: "/images/logos/plugins/stripe.svg",
    id: "stripe",
  },
  {
    title: "Tailscale",
    name: "Tailscale",
    logo: "/images/logos/plugins/tailscale.svg",
    logoDark: "/images/logos/plugins/tailscale-dark.svg",
    id: "tailscale",
  },
  {
    title: "Terraform",
    name: "Terraform",
    logo: "/images/logos/plugins/terraform.svg",
    id: "terraform",
  },
  {
    title: "Vercel",
    name: "Vercel",
    logo: "/images/logos/plugins/vercel.svg",
    logoDark: "/images/logos/plugins/vercel-dark.svg",
    id: "vercel",
  },
  {
    title: "Yandex Cloud",
    name: "Yandex Cloud",
    logo: "/images/logos/plugins/yandex.svg",
    id: "yandexcloud",
    href: "https://github.com/yandex-cloud/cq-source-yandex",
  },
  {
    title: "And more...",
    name: "All Plugins",
    logo: "/images/logos/plugins/more.svg",
    logoDark: "/images/logos/plugins/more-dark.svg",
    href: "/docs/plugins/overview",
  },
];
