// TODO: keep adding to this list (possibility of deduping things like is amp and amplify supposed to be the same thing?)
export const awsServiceLabelMap: Record<string, string> = {
  AWSCloudMap: 'Cloud Map',
  account: 'Account',
  accessanalyzer: 'Access Analyzer',
  acm: 'Certificate Manager (ACM)',
  acmpca: 'Private Certificate Authority',
  airflow: 'Managed Workflows for Apache Airflow',
  amplify: 'Amplify',
  amp: 'Managed Service for Prometheus',
  amplifyuibuilder: 'Amplify UI Builder',
  aoss: 'OpenSearch Serverless',
  apigateway: 'API Gateway',
  appconfig: 'AppConfig',
  appflow: 'AppFlow',
  applicationautoscaling: 'Application Auto Scaling',
  applicationsignals: 'CloudWatch Application Signals',
  appmesh: 'App Mesh',
  apprunner: 'App Runner',
  appstream: 'AppStream',
  appstream2: 'AppStream 2.0',
  availability: 'Availability',
  backupgateway: 'Backup Gateway',
  budgets: 'Budgets',
  cloudfront: 'CloudFront',
  cloudhsmv2: 'CloudHSM V2',
  cloudwatch: 'CloudWatch',
  computeoptimizer: 'Compute Optimizer',
  costexplorer: 'Cost Explorer',
  datapipeline: 'Data Pipeline',
  detective: 'Detective',
  directconnect: 'Direct Connect',
  directoryservice: 'Directory Service',
  cognito: 'Cognito',
  appsync: 'AppSync',
  aps: 'Managed Prometheus',
  athena: 'Athena',
  auditmanager: 'Audit Manager',
  autoscaling: 'EC2 Auto Scaling',
  autoscalingplans: 'Auto Scaling Plans',
  b2bi: 'B2B Data Interchange',
  backup: 'Backup',
  batch: 'Batch',
  cassandra: 'Keyspaces (for Apache Cassandra)',
  cleanrooms: 'Clean Rooms',
  cleanroomsml: 'Clean Rooms ML',
  cloud9: 'Cloud9',
  cloudformation: 'CloudFormation',
  cloudhsm: 'CloudHSM',
  cloudshell: 'CloudShell',
  cloudtrail: 'CloudTrail',
  codeartifact: 'CodeArtifact',
  codebuild: 'CodeBuild',
  codecommit: 'CodeCommit',
  codedeploy: 'CodeDeploy',
  codeguruprofiler: 'CodeGuru Profiler',
  codegurureviewer: 'CodeGuru Reviewer',
  codepipeline: 'CodePipeline',
  cognitoidentity: 'Cognito Federated Identities',
  cognitoidp: 'Cognito User Pools',
  cognitosync: 'Cognito Sync',
  comprehend: 'Comprehend',
  comprehendmedical: 'Comprehend Medical',
  config: 'Config',
  controltower: 'Control Tower',
  databrew: 'Glue DataBrew',
  dataexchange: 'Data Exchange',
  datasync: 'DataSync',
  datazone: 'DataZone',
  dax: 'DynamoDB Accelerator (DAX)',
  deadline: 'Deadline Cloud',
  dlm: 'Data Lifecycle Manager',
  dms: 'Database Migration Service (AWS DMS)',
  docdb: 'DocumentDB (with MongoDB compatibility)',
  docdbelastic: 'DocumentDB Elastic Clusters',
  drs: 'ElasticDisasterRecovery',
  ds: 'Directory Service',
  dynamodb: 'DynamoDB',
  ebs: 'Elastic Block Store (EBS)',
  ec2: 'Elastic Compute Cloud (EC2)',
  ec2ipam: 'IPAM',
  ec2fastlaunch: 'EC2 Fast Launch',
  ecr: 'Elastic Container Registry (ECR)',
  ecrpublic: 'ECR Public',
  efs: 'Elastic File System (EFS)',
  ecs: 'Elastic Container Service (ECS)',
  eks: 'Elastic Kubernetes Service (EKS)',
  elasticinference: 'Elastic Inference',
  elasticache: 'ElastiCache',
  elasticbeanstalk: 'Elastic Beanstalk',
  elasticfilesystem: 'Elastic File System (EFS)',
  elasticloadbalancing: 'Elastic Load Balancing (ELB)',
  elasticmapreduce: 'EMR',
  elasticsearch: 'Elastic Search',
  emrserverless: 'EMR Serverless',
  entityresolution: 'Entity Resolution',
  es: 'OpenSearch Service',
  events: 'EventBridge (CloudWatch Events)',
  elastictranscoder: 'Elastic Transcoder',
  elb: 'Elastic Load Balancing (ELB)',
  eventbridge: 'EventBridge',
  globalaccelerator: 'Global Accelerator',
  organizations: 'Organizations',
  organization: 'Organization',
  emr: 'Elastic MapReduce (EMR)',
  health: 'Health',
  networkmanager: 'Network Manager',
  opensearch: 'OpenSearch',
  memorydb: 'MemoryDB',
  mwaa: 'Managed Workflows for Apache Airflow (MWAA)',
  lexv2: 'Lex V2',
  keyspaces: 'Keyspaces',
  identitystore: 'Identity Store',
  iam: 'Identity and Access Management (IAM)',
  evidently: 'CloudWatch Evidently',
  fargate: 'Fargate',
  finspace: 'FinSpace',
  firehose: 'Kinesis Data Firehose',
  fis: 'Fault Injection Service (FIS)',
  fms: 'Firewall Manager',
  forecast: 'Forecast',
  frauddetector: 'Fraud Detector',
  fsx: 'FSx',
  gamelift: 'GameLift',
  geo: 'Location Service (Location)',
  glacier: 'Glacier',
  glue: 'Glue',
  grafana: 'Managed Grafana',
  greengrass: 'IoT Greengrass',
  groundstation: 'Ground Station',
  guardduty: 'GuardDuty',
  healthlake: 'HealthLake',
  imagebuilder: 'EC2 Image Builder',
  inspector: 'Inspector Classic',
  inspector2: 'Inspector',
  internetmonitor: 'CloudWatch Internet Monitor',
  iot: 'IoT',
  iot1click: 'IoT 1-Click',
  iotanalytics: 'IoT Analytics',
  iotcore: 'IoT Core',
  iotevents: 'IoT Events',
  iotsitewise: 'IoT SiteWise',
  kafka: 'Managed Streaming for Kafka (MSK)',
  kafkaconnect: 'Managed Streaming for Kafka Connect',
  kendra: 'Kendra',
  kendraranking: 'Kendra Intelligent Ranking',
  kinesis: 'Kinesis Data Streams',
  kinesisanalytics: 'Managed Service for Apache Flink',
  kinesisvideo: 'Kinesis Video Streams',
  kms: 'Key Management Service (AWS KMS)',
  lakeformation: 'Lake Formation',
  lambda: 'Lambda',
  launchwizard: 'Launch Wizard',
  licensemanager: 'License Manager',
  licensemanagerlinuxsubscriptions: 'License Manager Linux Subscriptions',
  licensemanagerusersubscriptions: 'License Manager User Subscriptions',
  lightsail: 'Lightsail',
  logs: 'CloudWatch Logs',
  lookoutmetrics: 'Lookout for Metrics',
  lookoutvision: 'Lookout for Vision',
  m2: 'Mainframe Modernization',
  macie2: 'Macie',
  mediaconnect: 'Elemental MediaConnect',
  mediaconvert: 'Elemental MediaConvert',
  medialive: 'Elemental MediaLive',
  mediapackage: 'Elemental MediaPackage',
  mediapackagev2: 'Elemental MediaPackage v2',
  mediatailor: 'Elemental MediaTailor',
  mgn: 'Application Migration',
  migrationhuborchestrator: 'Migration Hub Orchestrator',
  monitoring: 'CloudWatch',
  mq: 'MQ',
  neptune: 'Neptune',
  neptunegraph: 'Neptune Analytics',
  networkfirewall: 'Network Firewall',
  networkinsights: 'Network Insights',
  networkmonitor: 'CloudWatch Network Monitor',
  nimble: 'Nimble Studio',
  oam: 'CloudWatch Observability Access Manager',
  opsworks: 'OpsWorks Stacks',
  opsworkscm: 'OpsWorks for Chef Automate and AWS OpsWorks for Puppet Enterprise',
  outposts: 'Outposts',
  paymentcryptography: 'Payment Cryptography',
  pcaconnectorad: 'Private CA Connector for Active Directory',
  personalize: 'Personalize',
  pinpoint: 'Pinpoint',
  polly: 'Polly',
  privatenetworks: 'Private 5G',
  proton: 'Proton',
  qldb: 'QLDB',
  quicksight: 'QuickSight',
  ram: 'Resource Access Manager',
  rbin: 'Recycle Bin',
  rds: 'Relational Database Service (RDS)',
  redshift: 'Redshift',
  refactorspaces: 'Migration Hub Refactor Spaces',
  rekognition: 'Rekognition',
  resiliencehub: 'Resilience Hub',
  resourceexplorer2: 'Resource Explorer',
  resourcegroups: 'Resource Groups',
  robomaker: 'RoboMaker',
  rolesanywhere: 'IAM Roles Anywhere',
  ssoadmin: 'Single Sign-On Admin',
  servicediscovery: 'Service Discovery',
  route53: 'Route 53',
  support: 'Support',
  stepfunctions: 'Step Functions',
  route53profiles: 'Route 53 Profiles',
  route53resolver: 'Route 53 Resolver',
  rum: 'CloudWatch RUM',
  s3: 'Simple Storage Service (S3)',
  s3outposts: 'S3 Outposts',
  sagemaker: 'SageMaker',
  scheduler: 'EventBridge Scheduler',
  schemas: 'EventBridge Schema Registry',
  secretsmanager: 'Secrets Manager',
  securityhub: 'Security Hub',
  serverlessrepo: 'Serverless Application Repository',
  servicecatalog: 'Service Catalog',
  servicequotas: 'Service Quotas',
  ses: 'Simple Email Service(SES)',
  shield: 'Shield Advanced',
  signer: 'Signer',
  simspaceweaver: 'SimSpace Weaver',
  sms: 'Server Migration Service',
  snowball: 'Snow Family',
  sns: 'Simple Notification Service (SNS)',
  sqs: 'Simple Queue Service (SQS)',
  ssm: 'Systems Manager',
  savingsplans: 'Savings Plans',
  ssmcontacts: 'Systems Manager Incident Manager Contacts',
  ssmguiconnect: 'Systems Manager GUI Connect',
  ssmincidents: 'Systems Manager Incident Manager',
  ssmsap: 'Systems Manager for SAP',
  sso: 'IAM Identity Center (successor to AWS Single Sign-On)',
  states: 'Step Functions',
  storagegateway: 'Storage Gateway',
  swf: 'Simple Workflow Service',
  textract: 'Textract',
  timestream: 'Timestream',
  timestreaminfluxdb: 'Timestream for Managed Influx',
  transcribe: 'Transcribe',
  transfer: 'Transfer Family',
  translate: 'Translate',
  trustedadvisor: 'Trusted Advisor',
  ts: 'Diagnostic Tools',
  verifiedpermissions: 'Verified Permissions',
  vmimportexport: 'EC2 VM Import/Export',
  regions: 'Regions',
  vpc: 'Virtual Private Cloud (VPC)',
  workspaces: 'WorkSpaces',
  vpclattice: 'VPC Lattice',
  waf: 'Web Application Firewall (WAF)',
  wafregional: 'WAF Classic (Regional)',
  wafv2: 'WAF',
  wellarchitected: 'Well-Architected Tool',
  xray: 'X-Ray',
};
// TODO: build step will eventually provide this
// currently sourced from cloudquery-private/plugins/source/aws/client/data/partition_service_region.json
export const awsRegions = [
  'af-south-1',
  'ap-east-1',
  'ap-northeast-1',
  'ap-northeast-2',
  'ap-northeast-3',
  'ap-south-1',
  'ap-south-2',
  'ap-southeast-1',
  'ap-southeast-2',
  'ap-southeast-3',
  'ap-southeast-4',
  'ca-central-1',
  'ca-west-1',
  'eu-central-1',
  'eu-central-2',
  'eu-north-1',
  'eu-south-1',
  'eu-south-2',
  'eu-west-1',
  'eu-west-2',
  'eu-west-3',
  'il-central-1',
  'me-central-1',
  'me-south-1',
  'sa-east-1',
  'us-east-1',
  'us-east-2',
  'us-west-1',
  'us-west-2',
  'fips-us-east-1',
  'fips-us-west-2',
  'aws-global',
  'fips-ca-central-1',
  'fips-us-east-2',
  'fips-us-west-1',
  'sandbox',
  'api',
  'ca-central-1-fips',
  'ca-west-1-fips',
  'us-east-1-fips',
  'us-east-2-fips',
  'us-west-1-fips',
  'us-west-2-fips',
  'ui-ap-northeast-1',
  'ui-ap-northeast-2',
  'ui-ap-southeast-1',
  'ui-ap-southeast-2',
  'ui-ca-central-1',
  'ui-eu-central-1',
  'ui-eu-west-2',
  'ui-us-east-1',
  'ui-us-west-2',
];
