export const awsServiceLabelMap: Record<string, string> = {
  AWSCloudMap: 'AWS Cloud Map',
  'access-analyzer': 'Access Analyzer',
  acm: 'AWS Certificate Manager (ACM)',
  'acm-pca': 'AWS Private Certificate Authority',
  airflow: 'Amazon Managed Workflows for Apache Airflow',
  amplify: 'AWS Amplify',
  amplifyuibuilder: 'Amplify UI Builder',
  aoss: 'Amazon OpenSearch Serverless',
  apigateway: 'Amazon API Gateway',
  appconfig: 'AWS AppConfig',
  appflow: 'Amazon AppFlow',
  'application-autoscaling': 'Application Auto Scaling',
  'application-signals': 'Amazon CloudWatch Application Signals',
  appmesh: 'AWS App Mesh',
  apprunner: 'AWS App Runner',
  appstream2: 'Amazon AppStream 2.0',
  appsync: 'AWS AppSync',
  aps: 'Amazon Managed Prometheus',
  athena: 'Amazon Athena',
  auditmanager: 'AWS Audit Manager',
  autoscaling: 'Amazon EC2 Auto Scaling',
  'autoscaling-plans': 'AWS Auto Scaling Plans',
  b2bi: 'B2B Data Interchange',
  backup: 'AWS Backup',
  batch: 'AWS Batch',
  cassandra: 'Amazon Keyspaces (for Apache Cassandra)',
  cleanrooms: 'AWS Clean Rooms',
  'cleanrooms-ml': 'AWS Clean Rooms ML',
  cloud9: 'AWS Cloud9',
  cloudformation: 'AWS CloudFormation',
  cloudhsm: 'AWS CloudHSM',
  cloudshell: 'AWS CloudShell',
  cloudtrail: 'AWS CloudTrail',
  codeartifact: 'AWS CodeArtifact',
  codebuild: 'AWS CodeBuild',
  codecommit: 'AWS CodeCommit',
  codedeploy: 'AWS CodeDeploy',
  'codeguru-profiler': 'Amazon CodeGuru Profiler',
  'codeguru-reviewer': 'Amazon CodeGuru Reviewer',
  codepipeline: 'AWS CodePipeline',
  'cognito-identity': 'Amazon Cognito Federated Identities',
  'cognito-idp': 'Amazon Cognito User Pools',
  'cognito-sync': 'Amazon Cognito Sync',
  comprehend: 'Amazon Comprehend',
  comprehendmedical: 'Amazon Comprehend Medical',
  config: 'AWS Config',
  controltower: 'AWS Control Tower',
  databrew: 'AWS Glue DataBrew',
  dataexchange: 'AWS Data Exchange',
  datasync: 'AWS DataSync',
  datazone: 'Amazon DataZone',
  dax: 'Amazon DynamoDB Accelerator (DAX)',
  deadline: 'AWS Deadline Cloud',
  dlm: 'Amazon Data Lifecycle Manager',
  dms: 'AWS Database Migration Service (AWS DMS)',
  docdb: 'Amazon DocumentDB (with MongoDB compatibility)',
  'docdb-elastic': 'Amazon DocumentDB Elastic Clusters',
  drs: 'ElasticDisasterRecovery',
  ds: 'AWS Directory Service',
  dynamodb: 'Amazon DynamoDB',
  ebs: 'Amazon Elastic Block Store (Amazon EBS)',
  ec2: 'Amazon Elastic Compute Cloud (Amazon EC2)',
  'ec2-ipam': 'IPAM',
  ec2fastlaunch: 'EC2 Fast Launch',
  ecr: 'Amazon Elastic Container Registry (Amazon ECR)',
  ecs: 'Amazon Elastic Container Service (Amazon ECS)',
  eks: 'Amazon Elastic Kubernetes Service (Amazon EKS)',
  'elastic-inference': 'Amazon Elastic Inference',
  elasticache: 'Amazon ElastiCache',
  elasticbeanstalk: 'AWS Elastic Beanstalk',
  elasticfilesystem: 'Amazon Elastic File System (EFS)',
  elasticloadbalancing: 'Elastic Load Balancing (ELB)',
  elasticmapreduce: 'Amazon EMR',
  'emr-serverless': 'Amazon EMR Serverless',
  entityresolution: 'AWS Entity Resolution',
  es: 'Amazon OpenSearch Service',
  events: 'Amazon EventBridge (CloudWatch Events)',
  evidently: 'Amazon CloudWatch Evidently',
  fargate: 'AWS Fargate',
  finspace: 'Amazon FinSpace',
  firehose: 'Amazon Kinesis Data Firehose',
  fis: 'AWS Fault Injection Service (FIS)',
  fms: 'AWS Firewall Manager',
  forecast: 'Amazon Forecast',
  frauddetector: 'Amazon Fraud Detector',
  fsx: 'Amazon FSx',
  gamelift: 'Amazon GameLift',
  geo: 'Amazon Location Service (Amazon Location)',
  glacier: 'Amazon Glacier',
  glue: 'AWS Glue',
  grafana: 'Amazon Managed Grafana',
  greengrass: 'AWS IoT Greengrass',
  groundstation: 'AWS Ground Station',
  guardduty: 'Amazon GuardDuty',
  healthlake: 'AWS HealthLake',
  imagebuilder: 'EC2 Image Builder',
  inspector: 'Amazon Inspector Classic',
  inspector2: 'Amazon Inspector',
  internetmonitor: 'CloudWatch Internet Monitor',
  iot: 'AWS IoT',
  iot1click: 'AWS IoT 1-Click',
  iotanalytics: 'AWS IoT Analytics',
  iotcore: 'AWS IoT Core',
  iotevents: 'AWS IoT Events',
  iotsitewise: 'AWS IoT SiteWise',
  kafka: 'Amazon Managed Streaming for Kafka (MSK)',
  kafkaconnect: 'Managed Streaming for Kafka Connect',
  kendra: 'Amazon Kendra',
  'kendra-ranking': 'Amazon Kendra Intelligent Ranking',
  kinesis: 'Amazon Kinesis Data Streams',
  kinesisanalytics: 'Amazon Managed Service for Apache Flink',
  kinesisvideo: 'Amazon Kinesis Video Streams',
  kms: 'AWS Key Management Service (AWS KMS)',
  lakeformation: 'AWS Lake Formation',
  lambda: 'AWS Lambda',
  launchwizard: 'AWS Launch Wizard',
  'license-manager': 'AWS License Manager',
  'license-manager-linux-subscriptions': 'AWS License Manager Linux Subscriptions',
  'license-manager-user-subscriptions': 'AWS License Manager User Subscriptions',
  lightsail: 'Amazon Lightsail',
  logs: 'Amazon CloudWatch Logs',
  lookoutmetrics: 'Amazon Lookout for Metrics',
  lookoutvision: 'Amazon Lookout for Vision',
  m2: 'AWS Mainframe Modernization',
  macie2: 'Amazon Macie',
  mediaconnect: 'AWS Elemental MediaConnect',
  mediaconvert: 'AWS Elemental MediaConvert',
  medialive: 'AWS Elemental MediaLive',
  mediapackage: 'AWS Elemental MediaPackage',
  mediapackagev2: 'AWS Elemental MediaPackage v2',
  mediatailor: 'AWS Elemental MediaTailor',
  mgn: 'Application Migration',
  migrationhuborchestrator: 'Migration Hub Orchestrator',
  monitoring: 'Amazon CloudWatch',
  mq: 'Amazon MQ',
  neptune: 'Amazon Neptune',
  'neptune-graph': 'Amazon Neptune Analytics',
  'network-firewall': 'AWS Network Firewall',
  networkinsights: 'Network Insights',
  networkmonitor: 'Amazon CloudWatch Network Monitor',
  nimble: 'Amazon Nimble Studio',
  oam: 'Amazon CloudWatch Observability Access Manager',
  opsworks: 'AWS OpsWorks Stacks',
  'opsworks-cm': 'AWS OpsWorks for Chef Automate and AWS OpsWorks for Puppet Enterprise',
  outposts: 'AWS Outposts',
  'payment-cryptography': 'AWS Payment Cryptography',
  'pca-connector-ad': 'Private CA Connector for Active Directory',
  personalize: 'Amazon Personalize',
  pinpoint: 'Amazon Pinpoint',
  polly: 'Amazon Polly',
  'private-networks': 'AWS Private 5G',
  proton: 'AWS Proton',
  qldb: 'Amazon QLDB',
  quicksight: 'Amazon QuickSight',
  ram: 'AWS Resource Access Manager',
  rbin: 'Amazon Recycle Bin',
  rds: 'Amazon Relational Database Service (Amazon RDS)',
  redshift: 'Amazon Redshift',
  'refactor-spaces': 'AWS Migration Hub Refactor Spaces',
  rekognition: 'Amazon Rekognition',
  resiliencehub: 'AWS Resilience Hub',
  'resource-explorer-2': 'AWS Resource Explorer',
  'resource-groups': 'AWS Resource Groups',
  robomaker: 'AWS RoboMaker',
  rolesanywhere: 'IAM Roles Anywhere',
  route53profiles: 'Route 53 Profiles',
  route53resolver: 'Route 53 Resolver',
  rum: 'Amazon CloudWatch RUM',
  s3: 'Amazon Simple Storage Service (Amazon S3)',
  's3-outposts': 'AWS S3 Outposts',
  sagemaker: 'Amazon SageMaker',
  scheduler: 'Amazon EventBridge Scheduler',
  schemas: 'Amazon EventBridge Schema Registry',
  secretsmanager: 'AWS Secrets Manager',
  securityhub: 'AWS Security Hub',
  serverlessrepo: 'AWS Serverless Application Repository',
  servicecatalog: 'AWS Service Catalog',
  servicequotas: 'Service Quotas',
  ses: 'Amazon Simple Email Service(Amazon SES)',
  shield: 'AWS Shield Advanced',
  signer: 'AWS Signer',
  simspaceweaver: 'AWS SimSpace Weaver',
  sms: 'AWS Server Migration Service',
  snowball: 'AWS Snow Family',
  sns: 'Amazon Simple Notification Service (Amazon SNS)',
  sqs: 'Amazon Simple Queue Service (Amazon SQS)',
  ssm: 'AWS Systems Manager',
  'ssm-contacts': 'AWS Systems Manager Incident Manager Contacts',
  'ssm-guiconnect': 'AWS Systems Manager GUI Connect',
  'ssm-incidents': 'AWS Systems Manager Incident Manager',
  'ssm-sap': 'AWS Systems Manager for SAP',
  sso: 'AWS IAM Identity Center (successor to AWS Single Sign-On)',
  states: 'AWS Step Functions',
  storagegateway: 'AWS Storage Gateway',
  swf: 'Amazon Simple Workflow Service',
  textract: 'Amazon Textract',
  timestream: 'Amazon Timestream',
  'timestream-influxdb': 'Amazon Timestream for Managed Influx',
  transcribe: 'Amazon Transcribe',
  transfer: 'AWS Transfer Family',
  translate: 'Amazon Translate',
  trustedadvisor: 'AWS Trusted Advisor',
  ts: 'Diagnostic Tools',
  verifiedpermissions: 'Amazon Verified Permissions',
  vmimportexport: 'EC2 VM Import/Export',
  vpc: 'Amazon Virtual Private Cloud (Amazon VPC)',
  'vpc-lattice': 'VPC Lattice',
  'waf-regional': 'AWS WAF Classic (Regional)',
  wafv2: 'AWS WAF',
  wellarchitected: 'AWS Well-Architected Tool',
  xray: 'AWS X-Ray',
};

// type AWSService = {
//   name: string;
//   logo: string;
//   tables: string[];
// };
// export const awsServices: Record<string, AWSService> = {
//   accessanalyzer: {
//     name: 'accessanalyzer',
//     logo: '/icons/accessanalyzer.svg',
//     tables: [],
//   },
//   account: {
//     name: 'account',
//     logo: '/icons/account.svg',
//     tables: [],
//   },
//   acm: {
//     name: 'acm',
//     logo: '/icons/acm.svg',
//     tables: [],
//   },
//   acmpca: {
//     name: 'acmpca',
//     logo: '/icons/acmpca.svg',
//     tables: [],
//   },
//   amplify: {
//     name: 'amplify',
//     logo: '/icons/amplify.svg',
//     tables: [],
//   },
//   amp: {
//     name: 'amp',
//     logo: '/icons/amp.svg',
//     tables: [],
//   },
//   apigateway: {
//     name: 'apigateway',
//     logo: '/icons/apigateway.svg',
//     tables: [],
//   },
//   apigatewayv2: {
//     name: 'apigatewayv2',
//     logo: '/icons/apigatewayv2.svg',
//     tables: [],
//   },
//   appconfig: {
//     name: 'appconfig',
//     logo: '/icons/appconfig.svg',
//     tables: [],
//   },
//   appflow: {
//     name: 'appflow',
//     logo: '/icons/appflow.svg',
//     tables: [],
//   },
//   applicationautoscaling: {
//     name: 'applicationautoscaling',
//     logo: '/icons/applicationautoscaling.svg',
//     tables: [],
//   },
//   appmesh: {
//     name: 'appmesh',
//     logo: '/icons/appmesh.svg',
//     tables: [],
//   },
//   apprunner: {
//     name: 'apprunner',
//     logo: '/icons/apprunner.svg',
//     tables: [],
//   },
//   appstream: {
//     name: 'appstream',
//     logo: '/icons/appstream.svg',
//     tables: [],
//   },
//   appsync: {
//     name: 'appsync',
//     logo: '/icons/appsync.svg',
//     tables: [],
//   },
//   athena: {
//     name: 'athena',
//     logo: '/icons/athena.svg',
//     tables: [],
//   },
//   auditmanager: {
//     name: 'auditmanager',
//     logo: '/icons/auditmanager.svg',
//     tables: [],
//   },
//   autoscaling: {
//     name: 'autoscaling',
//     logo: '/icons/autoscaling.svg',
//     tables: [],
//   },
//   availability: {
//     name: 'availability',
//     logo: '/icons/availability.svg',
//     tables: [],
//   },
//   backupgateway: {
//     name: 'backupgateway',
//     logo: '/icons/backupgateway.svg',
//     tables: [],
//   },
//   backup: {
//     name: 'backup',
//     logo: '/icons/backup.svg',
//     tables: [],
//   },
//   batch: {
//     name: 'batch',
//     logo: '/icons/batch.svg',
//     tables: [],
//   },
//   budgets: {
//     name: 'budgets',
//     logo: '/icons/budgets.svg',
//     tables: [],
//   },
//   cloudformation: {
//     name: 'cloudformation',
//     logo: '/icons/cloudformation.svg',
//     tables: [],
//   },
//   cloudfront: {
//     name: 'cloudfront',
//     logo: '/icons/cloudfront.svg',
//     tables: [],
//   },
//   cloudhsmv2: {
//     name: 'cloudhsmv2',
//     logo: '/icons/cloudhsmv2.svg',
//     tables: [],
//   },
//   cloudtrail: {
//     name: 'cloudtrail',
//     logo: '/icons/cloudtrail.svg',
//     tables: [],
//   },
//   cloudwatch: {
//     name: 'cloudwatch',
//     logo: '/icons/cloudwatch.svg',
//     tables: [],
//   },
//   cloudwatchlogs: {
//     name: 'cloudwatchlogs',
//     logo: '/icons/cloudwatchlogs.svg',
//     tables: [],
//   },
//   codeartifact: {
//     name: 'codeartifact',
//     logo: '/icons/codeartifact.svg',
//     tables: [],
//   },
//   codebuild: {
//     name: 'codebuild',
//     logo: '/icons/codebuild.svg',
//     tables: [],
//   },
//   codecommit: {
//     name: 'codecommit',
//     logo: '/icons/codecommit.svg',
//     tables: [],
//   },
//   codedeploy: {
//     name: 'codedeploy',
//     logo: '/icons/codedeploy.svg',
//     tables: [],
//   },
//   codegurureviewer: {
//     name: 'codegurureviewer',
//     logo: '/icons/codegurureviewer.svg',
//     tables: [],
//   },
//   codepipeline: {
//     name: 'codepipeline',
//     logo: '/icons/codepipeline.svg',
//     tables: [],
//   },
//   cognito: {
//     name: 'cognito',
//     logo: '/icons/cognito.svg',
//     tables: [],
//   },
//   computeoptimizer: {
//     name: 'computeoptimizer',
//     logo: '/icons/computeoptimizer.svg',
//     tables: [],
//   },
//   config: {
//     name: 'config',
//     logo: '/icons/config.svg',
//     tables: [],
//   },
//   costexplorer: {
//     name: 'costexplorer',
//     logo: '/icons/costexplorer.svg',
//     tables: [],
//   },
//   datapipeline: {
//     name: 'datapipeline',
//     logo: '/icons/datapipeline.svg',
//     tables: [],
//   },
//   datasync: {
//     name: 'datasync',
//     logo: '/icons/datasync.svg',
//     tables: [],
//   },
//   dax: {
//     name: 'dax',
//     logo: '/icons/dax.svg',
//     tables: [],
//   },
//   detective: {
//     name: 'detective',
//     logo: '/icons/detective.svg',
//     tables: [],
//   },
//   directconnect: {
//     name: 'directconnect',
//     logo: '/icons/directconnect.svg',
//     tables: [],
//   },
//   directoryservice: {
//     name: 'directoryservice',
//     logo: '/icons/directoryservice.svg',
//     tables: [],
//   },
//   dms: {
//     name: 'dms',
//     logo: '/icons/dms.svg',
//     tables: [],
//   },
//   docdb: {
//     name: 'docdb',
//     logo: '/icons/docdb.svg',
//     tables: [],
//   },
//   dynamodb: {
//     name: 'dynamodb',
//     logo: '/icons/dynamodb.svg',
//     tables: [],
//   },
//   dynamodbstreams: {
//     name: 'dynamodbstreams',
//     logo: '/icons/dynamodbstreams.svg',
//     tables: [],
//   },
//   ebs: {
//     name: 'ebs',
//     logo: '/icons/ebs.svg',
//     tables: [],
//   },
//   ec2: {
//     name: 'ec2',
//     logo: '/icons/ec2.svg',
//     tables: [],
//   },
//   ecrpublic: {
//     name: 'ecrpublic',
//     logo: '/icons/ecrpublic.svg',
//     tables: [],
//   },
//   ecr: {
//     name: 'ecr',
//     logo: '/icons/ecr.svg',
//     tables: [],
//   },
//   ecs: {
//     name: 'ecs',
//     logo: '/icons/ecs.svg',
//     tables: [],
//   },
//   efs: {
//     name: 'efs',
//     logo: '/icons/efs.svg',
//     tables: [],
//   },
//   eks: {
//     name: 'eks',
//     logo: '/icons/eks.svg',
//     tables: [],
//   },
//   elasticache: {
//     name: 'elasticache',
//     logo: '/icons/elasticache.svg',
//     tables: [],
//   },
//   elasticbeanstalk: {
//     name: 'elasticbeanstalk',
//     logo: '/icons/elasticbeanstalk.svg',
//     tables: [],
//   },
//   elasticsearch: {
//     name: 'elasticsearch',
//     logo: '/icons/elasticsearch.svg',
//     tables: [],
//   },
//   elastictranscoder: {
//     name: 'elastictranscoder',
//     logo: '/icons/elastictranscoder.svg',
//     tables: [],
//   },
//   elbv1: {
//     name: 'elbv1',
//     logo: '/icons/elbv1.svg',
//     tables: [],
//   },
//   elbv2: {
//     name: 'elbv2',
//     logo: '/icons/elbv2.svg',
//     tables: [],
//   },
//   emr: {
//     name: 'emr',
//     logo: '/icons/emr.svg',
//     tables: [],
//   },
//   eventbridge: {
//     name: 'eventbridge',
//     logo: '/icons/eventbridge.svg',
//     tables: [],
//   },
//   firehose: {
//     name: 'firehose',
//     logo: '/icons/firehose.svg',
//     tables: [],
//   },
//   frauddetector: {
//     name: 'frauddetector',
//     logo: '/icons/frauddetector.svg',
//     tables: [],
//   },
//   fsx: {
//     name: 'fsx',
//     logo: '/icons/fsx.svg',
//     tables: [],
//   },
//   glacier: {
//     name: 'glacier',
//     logo: '/icons/glacier.svg',
//     tables: [],
//   },
//   globalaccelerator: {
//     name: 'globalaccelerator',
//     logo: '/icons/globalaccelerator.svg',
//     tables: [],
//   },
//   glue: {
//     name: 'glue',
//     logo: '/icons/glue.svg',
//     tables: [],
//   },
//   guardduty: {
//     name: 'guardduty',
//     logo: '/icons/guardduty.svg',
//     tables: [],
//   },
//   health: {
//     name: 'health',
//     logo: '/icons/health.svg',
//     tables: [],
//   },
//   healthlake: {
//     name: 'healthlake',
//     logo: '/icons/healthlake.svg',
//     tables: [],
//   },
//   iam: {
//     name: 'iam',
//     logo: '/icons/iam.svg',
//     tables: [],
//   },
//   identitystore: {
//     name: 'identitystore',
//     logo: '/icons/identitystore.svg',
//     tables: [],
//   },
//   inspector2: {
//     name: 'inspector2',
//     logo: '/icons/inspector2.svg',
//     tables: [],
//   },
//   inspector: {
//     name: 'inspector',
//     logo: '/icons/inspector.svg',
//     tables: [],
//   },
//   iot: {
//     name: 'iot',
//     logo: '/icons/iot.svg',
//     tables: [],
//   },
//   kafka: {
//     name: 'kafka',
//     logo: '/icons/kafka.svg',
//     tables: [],
//   },
//   keyspaces: {
//     name: 'keyspaces',
//     logo: '/icons/keyspaces.svg',
//     tables: [],
//   },
//   kinesis: {
//     name: 'kinesis',
//     logo: '/icons/kinesis.svg',
//     tables: [],
//   },
//   kms: {
//     name: 'kms',
//     logo: '/icons/kms.svg',
//     tables: [],
//   },
//   lambda: {
//     name: 'lambda',
//     logo: '/icons/lambda.svg',
//     tables: [],
//   },
//   lexv2: {
//     name: 'lexv2',
//     logo: '/icons/lexv2.svg',
//     tables: [],
//   },
//   lightsail: {
//     name: 'lightsail',
//     logo: '/icons/lightsail.svg',
//     tables: [],
//   },
//   memorydb: {
//     name: 'memorydb',
//     logo: '/icons/memorydb.svg',
//     tables: [],
//   },
//   mq: {
//     name: 'mq',
//     logo: '/icons/mq.svg',
//     tables: [],
//   },
//   mwaa: {
//     name: 'mwaa',
//     logo: '/icons/mwaa.svg',
//     tables: [],
//   },
//   neptune: {
//     name: 'neptune',
//     logo: '/icons/neptune.svg',
//     tables: [],
//   },
//   networkfirewall: {
//     name: 'networkfirewall',
//     logo: '/icons/networkfirewall.svg',
//     tables: [],
//   },
//   networkmanager: {
//     name: 'networkmanager',
//     logo: '/icons/networkmanager.svg',
//     tables: [],
//   },
//   opensearch: {
//     name: 'opensearch',
//     logo: '/icons/opensearch.svg',
//     tables: [],
//   },
//   organization: {
//     name: 'organization',
//     logo: '/icons/organization.svg',
//     tables: [],
//   },
//   organizations: {
//     name: 'organizations',
//     logo: '/icons/organizations.svg',
//     tables: [],
//   },
//   pinpoint: {
//     name: 'pinpoint',
//     logo: '/icons/pinpoint.svg',
//     tables: [],
//   },
//   qldb: {
//     name: 'qldb',
//     logo: '/icons/qldb.svg',
//     tables: [],
//   },
//   quicksight: {
//     name: 'quicksight',
//     logo: '/icons/quicksight.svg',
//     tables: [],
//   },
//   ram: {
//     name: 'ram',
//     logo: '/icons/ram.svg',
//     tables: [],
//   },
//   rds: {
//     name: 'rds',
//     logo: '/icons/rds.svg',
//     tables: [],
//   },
//   redshift: {
//     name: 'redshift',
//     logo: '/icons/redshift.svg',
//     tables: [],
//   },
//   regions: {
//     name: 'regions',
//     logo: '/icons/regions.svg',
//     tables: [],
//   },
//   resiliencehub: {
//     name: 'resiliencehub',
//     logo: '/icons/resiliencehub.svg',
//     tables: [],
//   },
//   resourcegroups: {
//     name: 'resourcegroups',
//     logo: '/icons/resourcegroups.svg',
//     tables: [],
//   },
//   route53: {
//     name: 'route53',
//     logo: '/icons/route53.svg',
//     tables: [],
//   },
//   route53recoverycontrolconfig: {
//     name: 'route53recoverycontrolconfig',
//     logo: '/icons/route53recoverycontrolconfig.svg',
//     tables: [],
//   },
//   route53recoveryreadiness: {
//     name: 'route53recoveryreadiness',
//     logo: '/icons/route53recoveryreadiness.svg',
//     tables: [],
//   },
//   route53resolver: {
//     name: 'route53resolver',
//     logo: '/icons/route53resolver.svg',
//     tables: [],
//   },
//   s3: {
//     name: 's3',
//     logo: '/icons/s3.svg',
//     tables: [],
//   },
//   sagemaker: {
//     name: 'sagemaker',
//     logo: '/icons/sagemaker.svg',
//     tables: [],
//   },
//   savingsplans: {
//     name: 'savingsplans',
//     logo: '/icons/savingsplans.svg',
//     tables: [],
//   },
//   scheduler: {
//     name: 'scheduler',
//     logo: '/icons/scheduler.svg',
//     tables: [],
//   },
//   secretsmanager: {
//     name: 'secretsmanager',
//     logo: '/icons/secretsmanager.svg',
//     tables: [],
//   },
//   securityhub: {
//     name: 'securityhub',
//     logo: '/icons/securityhub.svg',
//     tables: [],
//   },
//   servicecatalog: {
//     name: 'servicecatalog',
//     logo: '/icons/servicecatalog.svg',
//     tables: [],
//   },
//   servicediscovery: {
//     name: 'servicediscovery',
//     logo: '/icons/servicediscovery.svg',
//     tables: [],
//   },
//   servicequotas: {
//     name: 'servicequotas',
//     logo: '/icons/servicequotas.svg',
//     tables: [],
//   },
//   ses: {
//     name: 'ses',
//     logo: '/icons/ses.svg',
//     tables: [],
//   },
//   shield: {
//     name: 'shield',
//     logo: '/icons/shield.svg',
//     tables: [],
//   },
//   signer: {
//     name: 'signer',
//     logo: '/icons/signer.svg',
//     tables: [],
//   },
//   sns: {
//     name: 'sns',
//     logo: '/icons/sns.svg',
//     tables: [],
//   },
//   sqs: {
//     name: 'sqs',
//     logo: '/icons/sqs.svg',
//     tables: [],
//   },
//   ssm: {
//     name: 'ssm',
//     logo: '/icons/ssm.svg',
//     tables: [],
//   },
//   ssmincidents: {
//     name: 'ssmincidents',
//     logo: '/icons/ssmincidents.svg',
//     tables: [],
//   },
//   ssoadmin: {
//     name: 'ssoadmin',
//     logo: '/icons/ssoadmin.svg',
//     tables: [],
//   },
//   stepfunctions: {
//     name: 'stepfunctions',
//     logo: '/icons/stepfunctions.svg',
//     tables: [],
//   },
//   support: {
//     name: 'support',
//     logo: '/icons/support.svg',
//     tables: [],
//   },
//   timestream: {
//     name: 'timestream',
//     logo: '/icons/timestream.svg',
//     tables: [],
//   },
//   transfer: {
//     name: 'transfer',
//     logo: '/icons/transfer.svg',
//     tables: [],
//   },
//   wafregional: {
//     name: 'wafregional',
//     logo: '/icons/wafregional.svg',
//     tables: [],
//   },
//   waf: {
//     name: 'waf',
//     logo: '/icons/waf.svg',
//     tables: [],
//   },
//   wafv2: {
//     name: 'wafv2',
//     logo: '/icons/wafv2.svg',
//     tables: [],
//   },
//   wellarchitected: {
//     name: 'wellarchitected',
//     logo: '/icons/wellarchitected.svg',
//     tables: [],
//   },
//   workspaces: {
//     name: 'workspaces',
//     logo: '/icons/workspaces.svg',
//     tables: [],
//   },
//   xray: {
//     name: 'xray',
//     logo: '/icons/xray.svg',
//     tables: [],
//   },
// };

// TODO: build step will eventually provide this
// currently sourced from cloudquery-private/plugins/source/aws/client/data/partition_service_region.json
export const awsRegions = [
  'af-south-1',
  'ap-east-1',
  'ap-northeast-1',
  'ap-northeast-2',
  'ap-northeast-3',
  'ap-south-1',
  'ap-south-2',
  'ap-southeast-1',
  'ap-southeast-2',
  'ap-southeast-3',
  'ap-southeast-4',
  'ca-central-1',
  'ca-west-1',
  'eu-central-1',
  'eu-central-2',
  'eu-north-1',
  'eu-south-1',
  'eu-south-2',
  'eu-west-1',
  'eu-west-2',
  'eu-west-3',
  'il-central-1',
  'me-central-1',
  'me-south-1',
  'sa-east-1',
  'us-east-1',
  'us-east-2',
  'us-west-1',
  'us-west-2',
  'fips-us-east-1',
  'fips-us-west-2',
  'aws-global',
  'fips-ca-central-1',
  'fips-us-east-2',
  'fips-us-west-1',
  'sandbox',
  'api',
  'ca-central-1-fips',
  'ca-west-1-fips',
  'us-east-1-fips',
  'us-east-2-fips',
  'us-west-1-fips',
  'us-west-2-fips',
  'ui-ap-northeast-1',
  'ui-ap-northeast-2',
  'ui-ap-southeast-1',
  'ui-ap-southeast-2',
  'ui-ca-central-1',
  'ui-eu-central-1',
  'ui-eu-west-2',
  'ui-us-east-1',
  'ui-us-west-2',
];
