-- insert into aws_policy_results
-- select
--   :'execution_time',
--   :'framework',
--   :'check_id',
--   'Ensure credentials unused for 90 days or greater are disabled (Scored)',
--   split_part(arn, ':', 5) as account_id,
--   arn,
--   case when
--       (password_status IN ('TRUE', 'true') and password_last_used < (now() - '90 days'::INTERVAL)
--         or (last_used < (now() - '90 days'::INTERVAL)))
--       then 'fail'
--       else 'pass'
--   end
-- from aws_iam_credential_reports
-- TODO