-- Resource: redis.services
CREATE TABLE IF NOT EXISTS "azure_redis_services" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"subscription_id" text,
	"tags" jsonb,
	"location" text,
	"id" text,
	"name" text,
	"type" text,
	"provisioning_state" text,
	"hostname" text,
	"port" integer,
	"ssl_port" integer,
	"linked_server_ids" text[],
	"instances" jsonb,
	"private_endpoint_connections" jsonb,
	"sku_name" text,
	"sku_family" text,
	"sku_capacity" integer,
	"subnet_id" text,
	"static_ip" inet,
	"configuration" jsonb,
	"version" text,
	"enable_non_ssl_port" boolean,
	"replicas_per_master" integer,
	"replicas_per_primary" integer,
	"tenant_settings" jsonb,
	"shard_count" integer,
	"minimum_tls_version" text,
	"public_network_access" boolean,
	CONSTRAINT azure_redis_services_pk PRIMARY KEY(subscription_id,id),
	UNIQUE(cq_id)
);
