-- Autogenerated by migration tool on 2022-02-15 17:45:26
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: eventhub.namespaces
DROP TABLE IF EXISTS azure_eventhub_namespace_encryption_key_vault_properties;
DROP TABLE IF EXISTS azure_eventhub_namespaces;
