package plugin

import (
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/accessanalyzer"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/acm"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/apigateway"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/apigatewayv2"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/applicationautoscaling"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/appsync"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/athena"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/autoscaling"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/backup"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/cloudformation"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/cloudfront"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/cloudtrail"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/cloudwatch"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/cloudwatchlogs"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/codebuild"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/codepipeline"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/cognito"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/config"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/dax"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/directconnect"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/dms"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/dynamodb"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/ec2"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/ecr"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/ecs"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/efs"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/eks"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/elasticache"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/elasticbeanstalk"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/elasticsearch"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/elbv1"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/elbv2"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/emr"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/eventbridge"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/firehose"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/fsx"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/glue"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/guardduty"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/iam"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/inspector"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/inspector2"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/iot"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/kinesis"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/kms"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/lambda"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/lightsail"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/mq"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/organizations"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/qldb"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/rds"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/redshift"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/resourcegroups"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/route53"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/s3"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/sagemaker"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/secretsmanager"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/ses"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/shield"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/sns"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/sqs"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/ssm"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/transfer"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/waf"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/wafregional"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/wafv2"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/workspaces"
	"github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/xray"
	"github.com/cloudquery/plugin-sdk/schema"
)

func tables() []*schema.Table {
	return []*schema.Table{
		accessanalyzer.Analyzers(),
		acm.Certificates(),
		apigateway.APIKeys(),
		apigateway.ClientCertificates(),
		apigateway.DomainNames(),
		apigateway.RestApis(),
		apigateway.UsagePlans(),
		apigateway.VpcLinks(),
		apigatewayv2.Apigatewayv2Apis(),
		apigatewayv2.Apigatewayv2DomainNames(),
		apigatewayv2.Apigatewayv2VpcLinks(),
		applicationautoscaling.ApplicationautoscalingPolicies(),
		appsync.GraphqlApis(),
		athena.DataCatalogs(),
		athena.WorkGroups(),
		autoscaling.AutoscalingGroups(),
		autoscaling.AutoscalingLaunchConfigurations(),
		autoscaling.AutoscalingScheduledActions(),
		ec2.AwsRegions(),
		backup.GlobalSettings(),
		backup.Plans(),
		backup.RegionSettings(),
		backup.Vaults(),
		cloudformation.Stacks(),
		cloudfront.CloudfrontCachePolicies(),
		cloudfront.CloudfrontDistributions(),
		cloudtrail.CloudtrailTrails(),
		cloudwatch.CloudwatchAlarms(),
		cloudwatchlogs.CloudwatchlogsFilters(),
		cloudwatchlogs.LogGroups(),
		codebuild.CodebuildProjects(),
		codepipeline.Pipelines(),
		codepipeline.Webhooks(),
		cognito.CognitoIdentityPools(),
		cognito.CognitoUserPools(),
		config.ConfigConfigurationRecorders(),
		config.ConfigConformancePack(),
		dax.DaxClusters(),
		directconnect.DirectconnectConnections(),
		directconnect.DirectconnectGateways(),
		directconnect.DirectconnectLags(),
		directconnect.DirectconnectVirtualGateways(),
		directconnect.DirectconnectVirtualInterfaces(),
		dms.DmsReplicationInstances(),
		dynamodb.DynamodbTables(),
		ec2.ByoipCidrs(),
		ec2.CustomerGateways(),
		ec2.EbsSnapshots(),
		ec2.EbsVolumes(),
		ec2.EgressOnlyInternetGateways(),
		ec2.Eips(),
		ec2.FlowLogs(),
		ec2.Hosts(),
		ec2.Images(),
		ec2.InstanceStatuses(),
		ec2.InstanceTypes(),
		ec2.Instances(),
		ec2.InternetGateways(),
		ec2.KeyPairs(),
		ec2.NatGateways(),
		ec2.NetworkAcls(),
		ec2.NetworkInterfaces(),
		ec2.Ec2RegionalConfig(),
		ec2.RouteTables(),
		ec2.Ec2SecurityGroups(),
		ec2.Subnets(),
		ec2.Ec2TransitGateways(),
		ec2.VpcEndpointServiceConfigurations(),
		ec2.VpcEndpointServices(),
		ec2.VpcEndpoints(),
		ec2.VpcPeeringConnections(),
		ec2.Vpcs(),
		ec2.VpnGateways(),
		ecr.Repositories(),
		ecs.Clusters(),
		ecs.TaskDefinitions(),
		efs.Filesystems(),
		eks.Clusters(),
		elasticache.Clusters(),
		elasticache.EngineVersions(),
		elasticache.GlobalReplicationGroups(),
		elasticache.ParameterGroups(),
		elasticache.ReplicationGroups(),
		elasticache.ReservedCacheNodes(),
		elasticache.ReservedCacheNodesOfferings(),
		elasticache.ServiceUpdates(),
		elasticache.Snapshots(),
		elasticache.SubnetGroups(),
		elasticache.UserGroups(),
		elasticache.Users(),
		elasticbeanstalk.ApplicationVersions(),
		elasticbeanstalk.ElasticbeanstalkApplications(),
		elasticbeanstalk.ElasticbeanstalkEnvironments(),
		elasticsearch.ElasticsearchDomains(),
		elbv1.Elbv1LoadBalancers(),
		elbv2.Elbv2LoadBalancers(),
		elbv2.Elbv2TargetGroups(),
		emr.EmrBlockPublicAccessConfigs(),
		emr.EmrClusters(),
		eventbridge.EventBuses(),
		fsx.Backups(),
		fsx.DataRepoAssociations(),
		fsx.DataRepoTasks(),
		fsx.Filesystems(),
		fsx.Snapshots(),
		fsx.StorageVms(),
		fsx.Volumes(),
		glue.Classifiers(),
		glue.Connections(),
		glue.Crawlers(),
		glue.Databases(),
		glue.DatacatalogEncryptionSettings(),
		glue.DevEndpoints(),
		glue.Jobs(),
		glue.MlTransforms(),
		glue.Registries(),
		glue.Triggers(),
		glue.SecurityConfigurations(),
		glue.Workflows(),
		guardduty.GuarddutyDetectors(),
		iam.IamAccounts(),
		iam.IamGroups(),
		iam.IamOpenidConnectIdentityProviders(),
		iam.IamPasswordPolicies(),
		iam.IamPolicies(),
		iam.Roles(),
		iam.IamSamlIdentityProviders(),
		iam.IamServerCertificates(),
		iam.IamUsers(),
		iam.IamVirtualMfaDevices(),
		inspector.Findings(),
		inspector2.Findings(),
		iot.IotBillingGroups(),
		iot.IotCaCertificates(),
		iot.IotCertificates(),
		iot.IotPolicies(),
		iot.IotStreams(),
		iot.IotThingGroups(),
		iot.IotThingTypes(),
		iot.IotThings(),
		iot.IotTopicRules(),
		kinesis.Streams(),
		firehose.DeliveryStreams(),
		kms.Keys(),
		lambda.Functions(),
		lambda.LambdaLayers(),
		lambda.LambdaRuntimes(),
		lightsail.Alarms(),
		lightsail.Buckets(),
		lightsail.Certificates(),
		lightsail.ContainerServices(),
		lightsail.DatabaseSnapshots(),
		lightsail.Databases(),
		lightsail.Disks(),
		lightsail.Distributions(),
		lightsail.InstanceSnapshots(),
		lightsail.Instances(),
		lightsail.LoadBalancers(),
		lightsail.StaticIps(),
		mq.Brokers(),
		organizations.Accounts(),
		qldb.Ledgers(),
		rds.RdsCertificates(),
		rds.RdsClusterParameterGroups(),
		rds.RdsClusterSnapshots(),
		rds.RdsClusters(),
		rds.RdsDbParameterGroups(),
		rds.RdsDbSecurityGroups(),
		rds.RdsDbSnapshots(),
		rds.RdsSubnetGroups(),
		rds.RdsEventSubscriptions(),
		rds.RdsInstances(),
		redshift.RedshiftClusters(),
		redshift.EventSubscriptions(),
		redshift.RedshiftSubnetGroups(),
		resourcegroups.ResourceGroups(),
		route53.Route53Domains(),
		route53.Route53HealthChecks(),
		route53.Route53HostedZones(),
		route53.Route53ReusableDelegationSets(),
		route53.Route53TrafficPolicies(),
		s3.Accounts(),
		s3.Buckets(),
		sagemaker.SagemakerEndpointConfigurations(),
		sagemaker.SagemakerModels(),
		sagemaker.SagemakerNotebookInstances(),
		sagemaker.SagemakerTrainingJobs(),
		secretsmanager.SecretsmanagerSecrets(),
		ses.Templates(),
		shield.Attacks(),
		shield.ProtectionGroups(),
		shield.Protections(),
		shield.Subscriptions(),
		sns.Subscriptions(),
		sns.Topics(),
		sqs.Queues(),
		ssm.SsmDocuments(),
		ssm.SsmInstances(),
		ssm.Parameters(),
		transfer.Servers(),
		waf.WafRuleGroups(),
		waf.WafRules(),
		waf.WafSubscribedRuleGroups(),
		waf.WafWebAcls(),
		wafregional.RateBasedRules(),
		wafregional.RuleGroups(),
		wafregional.Rules(),
		wafregional.WebAcls(),
		wafv2.Ipsets(),
		wafv2.Wafv2ManagedRuleGroups(),
		wafv2.RegexPatternSets(),
		wafv2.Wafv2RuleGroups(),
		wafv2.Wafv2WebAcls(),
		workspaces.Directories(),
		workspaces.Workspaces(),
		xray.EncryptionConfigs(),
		xray.Groups(),
		xray.SamplingRules(),
	}
}