// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudquery/cloudquery/plugins/source/vercel/client (interfaces: VercelServices)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vercel "github.com/cloudquery/cloudquery/plugins/source/vercel/internal/vercel"
	gomock "github.com/golang/mock/gomock"
)

// MockVercelServices is a mock of VercelServices interface.
type MockVercelServices struct {
	ctrl     *gomock.Controller
	recorder *MockVercelServicesMockRecorder
}

// MockVercelServicesMockRecorder is the mock recorder for MockVercelServices.
type MockVercelServicesMockRecorder struct {
	mock *MockVercelServices
}

// NewMockVercelServices creates a new mock instance.
func NewMockVercelServices(ctrl *gomock.Controller) *MockVercelServices {
	mock := &MockVercelServices{ctrl: ctrl}
	mock.recorder = &MockVercelServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVercelServices) EXPECT() *MockVercelServicesMockRecorder {
	return m.recorder
}

// ListDomainRecords mocks base method.
func (m *MockVercelServices) ListDomainRecords(arg0 context.Context, arg1 string, arg2 *vercel.Paginator) ([]vercel.DomainRecord, *vercel.Paginator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDomainRecords", arg0, arg1, arg2)
	ret0, _ := ret[0].([]vercel.DomainRecord)
	ret1, _ := ret[1].(*vercel.Paginator)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDomainRecords indicates an expected call of ListDomainRecords.
func (mr *MockVercelServicesMockRecorder) ListDomainRecords(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDomainRecords", reflect.TypeOf((*MockVercelServices)(nil).ListDomainRecords), arg0, arg1, arg2)
}

// ListDomains mocks base method.
func (m *MockVercelServices) ListDomains(arg0 context.Context, arg1 *vercel.Paginator) ([]vercel.Domain, *vercel.Paginator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDomains", arg0, arg1)
	ret0, _ := ret[0].([]vercel.Domain)
	ret1, _ := ret[1].(*vercel.Paginator)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDomains indicates an expected call of ListDomains.
func (mr *MockVercelServicesMockRecorder) ListDomains(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDomains", reflect.TypeOf((*MockVercelServices)(nil).ListDomains), arg0, arg1)
}

// ListTeamMembers mocks base method.
func (m *MockVercelServices) ListTeamMembers(arg0 context.Context, arg1 string, arg2 *vercel.Paginator) ([]vercel.TeamMember, *vercel.Paginator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTeamMembers", arg0, arg1, arg2)
	ret0, _ := ret[0].([]vercel.TeamMember)
	ret1, _ := ret[1].(*vercel.Paginator)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTeamMembers indicates an expected call of ListTeamMembers.
func (mr *MockVercelServicesMockRecorder) ListTeamMembers(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTeamMembers", reflect.TypeOf((*MockVercelServices)(nil).ListTeamMembers), arg0, arg1, arg2)
}

// ListTeams mocks base method.
func (m *MockVercelServices) ListTeams(arg0 context.Context, arg1 *vercel.Paginator) ([]vercel.Team, *vercel.Paginator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTeams", arg0, arg1)
	ret0, _ := ret[0].([]vercel.Team)
	ret1, _ := ret[1].(*vercel.Paginator)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTeams indicates an expected call of ListTeams.
func (mr *MockVercelServicesMockRecorder) ListTeams(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTeams", reflect.TypeOf((*MockVercelServices)(nil).ListTeams), arg0, arg1)
}
