DROP TABLE IF EXISTS public.aws_emr_clusters;

CREATE TABLE public.aws_emr_clusters (
    cq_id uuid,
    meta jsonb,
    account_id text,
    region text,
    applications jsonb,
    auto_scaling_role text,
    auto_terminate boolean,
    arn text NOT NULL,
    configurations jsonb,
    custom_ami_id text,
    ebs_root_volume_size integer,
    ec2_instance_attribute_additional_master_security_groups text[],
    ec2_instance_attribute_additional_slave_security_groups text[],
    ec2_instance_attribute_availability_zone text,
    ec2_instance_attribute_key_name text,
    ec2_instance_attribute_subnet_id text,
    ec2_instance_attribute_emr_managed_master_security_group text,
    ec2_instance_attribute_emr_managed_slave_security_group text,
    ec2_instance_attribute_iam_instance_profile text,
    ec2_instance_attribute_requested_availability_zones text[],
    ec2_instance_attribute_requested_subnet_ids text[],
    ec2_instance_attribute_service_access_security_group text,
    id text,
    instance_collection_type text,
    kerberos_kdc_admin_password text,
    kerberos_realm text,
    kerberos_ad_domain_join_password text,
    kerberos_ad_domain_join_user text,
    kerberos_cross_realm_trust_principal_password text,
    log_encryption_kms_key_id text,
    log_uri text,
    master_public_dns_name text,
    name text,
    normalized_instance_hours integer,
    outpost_arn text,
    placement_groups jsonb,
    release_label text,
    repo_upgrade_on_boot text,
    requested_ami_version text,
    running_ami_version text,
    scale_down_behavior text,
    security_configuration text,
    service_role text,
    state text,
    state_change_reason_code text,
    state_change_reason_message text,
    creation_date_time timestamp without time zone,
    end_date_time timestamp without time zone,
    ready_date_time timestamp without time zone,
    step_concurrency_level integer,
    tags jsonb,
    termination_protected boolean,
    visible_to_all_users boolean
);

ALTER TABLE ONLY public.aws_emr_clusters
    ADD CONSTRAINT aws_emr_clusters_cq_id_key UNIQUE (cq_id);

ALTER TABLE ONLY public.aws_emr_clusters
    ADD CONSTRAINT aws_emr_clusters_pk PRIMARY KEY (arn);
