{
  "swagger": "2.0",
  "info": {
    "version": "2.0",
    "title": "Square Connect API",
    "description": "Client library for accessing the Square Connect APIs",
    "termsOfService": "https://connect.squareup.com/tos",
    "contact": {
      "name": "Square Developer Platform",
      "email": "developers@squareup.com",
      "url": "https://squareup.com/developers"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "connect.squareup.com",
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "oauth2": {
      "type": "oauth2",
      "authorizationUrl": "https://connect.squareup.com/oauth2/authorize",
      "flow": "accessCode",
      "tokenUrl": "https://connect.squareup.com/oauth2/token",
      "scopes": {
        "BANK_ACCOUNTS_READ": "__HTTP Method__: `GET`\n\nGrants read access to bank account information associated with the targeted\nSquare account. For example, to call the Connect v1 ListBankAccounts endpoint.",
        "CASH_DRAWER_READ": "__HTTP Method__: `GET`\n\nGrants read access to cash drawer shift information. For example, to call the\nListCashDrawerShifts endpoint.",
        "CUSTOMERS_READ": "__HTTP Method__: `GET`\n\nGrants read access to customer information. For example, to call the\nListCustomers endpoint.",
        "CUSTOMERS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to customer information. For example, to create and update\ncustomer profiles.",
        "DEVICE_CREDENTIAL_MANAGEMENT": "__HTTP Method__: `POST`, `GET`\n\nGrants read/write access to device credentials information. For example, to\ncall the CreateDeviceCode endpoint.",
        "EMPLOYEES_READ": "__HTTP Method__: `GET`\n\nGrants read access to employee profile information. For example, to call the\nConnect v1 Employees API.",
        "EMPLOYEES_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to employee profile information. For example, to create\nand modify employee profiles.",
        "INVENTORY_READ": "__HTTP Method__: `GET`\n\nGrants read access to inventory information. For example, to call the\nRetrieveInventoryCount endpoint.",
        "INVENTORY_WRITE": "__HTTP Method__:  `POST`, `PUT`, `DELETE`\n\nGrants write access to inventory information. For example, to call the\nBatchChangeInventory endpoint.",
        "ITEMS_READ": "__HTTP Method__: `GET`\n\nGrants read access to product catalog information. For example, to obtain objects in a product catalog.",
        "ITEMS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to product catalog information. For example, to modify or\nadd to a product catalog.",
        "LOYALTY_READ": "__HTTP Method__: `GET`\n\nGrants read access to loyalty information. For example, to call the\nListLoyaltyPrograms endpoint.",
        "LOYALTY_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to loyalty information. For example, to call the\nCreateLoyaltyAccount endpoint.",
        "MERCHANT_PROFILE_READ": "__HTTP Method__: `GET`\n\nGrants read access to business and location information. For example, to\nobtain a location ID for subsequent activity.",
        "ORDERS_READ": "__HTTP Method__: `GET`\n\nGrants read access to order information. For example, to call the\nBatchRetrieveOrders endpoint.",
        "ORDERS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to order information. For example, to call the\nCreateCheckout endpoint.",
        "PAYMENTS_READ": "__HTTP Method__: `GET`\n\nGrants read access to transaction and refund information. For example, to call\nthe RetrieveTransaction endpoint.",
        "PAYMENTS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to transaction and refunds information. For example, to\nprocess payments with the Payments or Checkout API.",
        "PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nAllow third party applications to deduct a portion of each transaction amount.\n__Required__ to use multiparty transaction functionality with the Payments\nAPI.",
        "PAYMENTS_WRITE_IN_PERSON": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to payments and refunds information. For example, to\nprocess in-person payments.",
        "SETTLEMENTS_READ": "__HTTP Method__: `GET`\n\nGrants read access to settlement (deposit) information. For example, to call\nthe Connect v1 ListSettlements endpoint.",
        "TIMECARDS_READ": "__HTTP Method__: `GET`\n\nGrants read access to employee timecard information. For example, to call the\nConnect v2 SearchShifts endpoint.",
        "TIMECARDS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to employee shift information. For example, to create\nand modify employee shifts.",
        "TIMECARDS_SETTINGS_READ": "__HTTP Method__: `GET`\n\nGrants read access to employee timecard settings information. For example, to\ncall the GetBreakType endpoint.",
        "TIMECARDS_SETTINGS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to employee timecard settings information. For example, to\ncall the UpdateBreakType endpoint.",
        "APPOINTMENTS_READ": "__HTTP Method__: `GET`, `POST`\n\nGrants read access to booking information. For example, to call the\nRetrieveBooking endpoint.",
        "APPOINTMENTS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to booking information. For example, to call the CreateBooking endpoint.",
        "APPOINTMENTS_BUSINESS_SETTINGS_READ": "__HTTP Method__: `GET`\n\nGrants read access to booking business settings. For example, to call the\nListTeamMemberBookingProfiles endpoint.",
        "INVOICES_READ": "__HTTP Method__: `GET`, `POST`\n\nGrants read access to invoice information. For example, to call the ListInvoices endpoint.",
        "INVOICES_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to invoice information. For example, to call the CreateInvoice endpoint.",
        "SUBSCRIPTIONS_READ": "__HTTP Method__: `GET`, `POST`\n\nGrants read access to subscription information. For example, to call the RetrieveSubscription\nendpoint.",
        "SUBSCRIPTIONS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to subscription information. For example, to call the CreateSubscription\nendpoint.",
        "DISPUTES_READ": "__HTTP Method__: `GET`\n\nGrants read access to dispute information. For example, to call the RetrieveDispute\nendpoint.",
        "DISPUTES_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to dispute information. For example, to call the SubmitEvidence\nendpoint.",
        "GIFTCARDS_READ": "__HTTP Method__: `GET`, `POST`\n\nGrants read access to gift card information. For example, to call the RetrieveGiftCard\nendpoint.",
        "GIFTCARDS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to gift card information. For example, to call the CreateGiftCard\nendpoint.",
        "ONLINE_STORE_SNIPPETS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nWrite access to ECOM online store snippets on published websites.",
        "ONLINE_STORE_SNIPPETS_READ": "__HTTP Method__: `GET`, `POST`\n\nRead access to ECOM online store snippets on published websites.",
        "ONLINE_STORE_SITE_READ": "__HTTP Method__: `GET`, `POST`\n\nRead access to ECOM online store site details.",
        "PAYMENTS_WRITE_SHARED_ONFILE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nAllows the developer to process payments on behalf of a seller using a shared on file payment method.",
        "APPOINTMENTS_ALL_READ": "__HTTP Method__: `GET`, `POST`\n\nGrants read access to all of a seller\u0027s booking information, calendar, and business details.\nThis permission must be accompanied by the `APPOINTMENTS_READ` permission.",
        "APPOINTMENTS_ALL_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to all booking details, including double-booking a seller.\nThis permission must be accompanied by the `APPOINTMENTS_WRITE` permission.",
        "MERCHANT_PROFILE_WRITE": "__HTTP Method__: `POST`, `PUT`\n\nGrants write access to business and location information. For example, to create a new location or\nupdate the business hours at an existing location.",
        "VENDOR_READ": "__HTTP Method__: `GET`, `POST`\n\nGrants read access to vendor information, for example, when calling the\n`RetrieveVendor` endpoint.",
        "VENDOR_WRITE": "__HTTP Method__:  `POST`, `PUT`, `DELETE`\n\nGrants write access to vendor information, for example, when calling the\n`BulkUpdateVendors` endpoint.",
        "PAYOUTS_READ": "__HTTP Method__: `GET`\n\nGrants read access to payouts and payout entries information. For example,\nto call the Connect v2 `ListPayouts` endpoint.",
        "RESERVATIONS_READ": "__HTTP Method__: `GET`\n\nGrants read access to reservation information, for example, when calling the\n`RetrieveReservation` endpoint.",
        "RESERVATIONS_WRITE": "__HTTP Method__:  `POST`, `PUT`, `DELETE`\n\nGrants write access to reservation information, for example, when calling the\n`CreateReservation` endpoint.",
        "RESTAURANT_CHECKS_READ": "__HTTP Method__: `GET`\n\nGrants read access to check information, for example, when calling the\n`RetrieveCheck` endpoint."
      }
    },
    "oauth2ClientSecret": {
      "type": "apiKey",
      "in": "header",
      "name": "Authorization"
    }
  },
  "paths": {
    "/mobile/authorization-code": {
      "post": {
        "tags": [
          "MobileAuthorization"
        ],
        "summary": "CreateMobileAuthorizationCode",
        "operationId": "CreateMobileAuthorizationCode",
        "description": "Generates code to authorize a mobile application to connect to a Square card reader.\n\nAuthorization codes are one-time-use codes and expire 60 minutes after being issued.\n\n__Important:__ The `Authorization` header you provide to this endpoint must have the following format:\n\n```\nAuthorization: Bearer ACCESS_TOKEN\n```\n\nReplace `ACCESS_TOKEN` with a\n[valid production authorization credential](https://developer.squareup.com/docs/build-basics/access-tokens).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE_IN_PERSON"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE_IN_PERSON"
            ]
          }
        ]
      }
    },
    "/oauth2/clients/{client_id}/access-token/renew": {
      "post": {
        "tags": [
          "OAuth"
        ],
        "summary": "RenewToken",
        "operationId": "RenewToken",
        "description": "`RenewToken` is deprecated. For information about refreshing OAuth access tokens, see\n[Migrate from Renew to Refresh OAuth Tokens](https://developer.squareup.com/docs/oauth-api/migrate-to-refresh-tokens).\n\nRenews an OAuth access token before it expires.\n\nOAuth access tokens besides your application\u0027s personal access token expire after 30 days.\nYou can also renew expired tokens within 15 days of their expiration.\nYou cannot renew an access token that has been e[...]",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2ClientSecret": []
          }
        ]
      }
    },
    "/oauth2/revoke": {
      "post": {
        "tags": [
          "OAuth"
        ],
        "summary": "RevokeToken",
        "operationId": "RevokeToken",
        "description": "Revokes an access token generated with the OAuth flow.\n\nIf an account has more than one OAuth access token for your application, this\nendpoint revokes all of them, regardless of which token you specify. When an\nOAuth access token is revoked, all of the active subscriptions associated\nwith that OAuth token are canceled immediately.\n\n__Important:__ The `Authorization` header for this endpoint must have the\nfollowing format:\n\n```\nAuthorization: Client APPLICATION_[...]",
        "x-release-status": "PUBLIC",
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2ClientSecret": []
          }
        ]
      }
    },
    "/oauth2/token": {
      "post": {
        "tags": [
          "OAuth"
        ],
        "summary": "ObtainToken",
        "operationId": "ObtainToken",
        "description": "Returns an OAuth access token and a refresh token unless the \n`short_lived` parameter is set to `true`, in which case the endpoint \nreturns only an access token.\n\nThe `grant_type` parameter specifies the type of OAuth request. If \n`grant_type` is `authorization_code`, you must include the authorization \ncode you received when a seller granted you authorization. If `grant_type` \nis `refresh_token`, you must provide a valid refresh token. If you\u0027re using \nan ol[...]",
        "x-release-status": "PUBLIC",
        "x-sq-version": "2023-07-20",
        "security": []
      }
    },
    "/oauth2/token/status": {
      "post": {
        "tags": [
          "OAuth"
        ],
        "summary": "RetrieveTokenStatus",
        "operationId": "RetrieveTokenStatus",
        "description": "Returns information about an [OAuth access token](https://developer.squareup.com/docs/build-basics/access-tokens#get-an-oauth-access-token) or an application’s [personal access token](https://developer.squareup.com/docs/build-basics/access-tokens#get-a-personal-access-token).\n\nAdd the access token to the Authorization header of the request.\n\n__Important:__ The `Authorization` header you provide to this endpoint must have the following format:\n\n```\nAuthorization: Be[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v1/{location_id}/orders": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "V1ListOrders",
        "operationId": "V1ListOrders",
        "description": "Provides summary information for a merchant\u0027s online store orders.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-visibility": "SDK_ONLY",
        "x-oauthpermissions": [
          "ORDERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/orders/{order_id}": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "V1RetrieveOrder",
        "operationId": "V1RetrieveOrder",
        "description": "Provides comprehensive information for a single online store order, including the order\u0027s history.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-visibility": "SDK_ONLY",
        "x-oauthpermissions": [
          "ORDERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "V1UpdateOrder",
        "operationId": "V1UpdateOrder",
        "description": "Updates the details of an online store order. Every update you perform on an order corresponds to one of three actions:",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-visibility": "SDK_ONLY",
        "x-oauthpermissions": [
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/payments": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "V1ListPayments",
        "operationId": "V1ListPayments",
        "description": "Provides summary information for all payments taken for a given\nSquare account during a date range. Date ranges cannot exceed 1 year in\nlength. See Date ranges for details of inclusive and exclusive dates.\n\n*Note**: Details for payments processed with Square Point of Sale while\nin offline mode may not be transmitted to Square for up to 72 hours.\nOffline payments have a `created_at` value that reflects the time the\npayment was originally processed, not the time it w[...]",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/payments/{payment_id}": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "V1RetrievePayment",
        "operationId": "V1RetrievePayment",
        "description": "Provides comprehensive information for a single payment.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/refunds": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "V1ListRefunds",
        "operationId": "V1ListRefunds",
        "description": "Provides the details for all refunds initiated by a merchant or any of the merchant\u0027s mobile staff during a date range. Date ranges cannot exceed one year in length.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "V1CreateRefund",
        "operationId": "V1CreateRefund",
        "description": "Issues a refund for a previously processed payment. You must issue\na refund within 60 days of the associated payment.\n\nYou cannot issue a partial refund for a split tender payment. You must\ninstead issue a full or partial refund for a particular tender, by\nproviding the applicable tender id to the V1CreateRefund endpoint.\nIssuing a full refund for a split tender payment refunds all tenders\nassociated with the payment.\n\nIssuing a refund for a card payment is not r[...]",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/settlements": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "V1ListSettlements",
        "operationId": "V1ListSettlements",
        "description": "Provides summary information for all deposits and withdrawals\ninitiated by Square to a linked bank account during a date range. Date\nranges cannot exceed one year in length.\n\n*Note**: the ListSettlements endpoint does not provide entry\ninformation.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "SETTLEMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "SETTLEMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/settlements/{settlement_id}": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "V1RetrieveSettlement",
        "operationId": "V1RetrieveSettlement",
        "description": "Provides comprehensive information for a single settlement.\n\nThe returned `Settlement` objects include an `entries` field that lists\nthe transactions that contribute to the settlement total. Most\nsettlement entries correspond to a payment payout, but settlement\nentries are also generated for less common events, like refunds, manual\nadjustments, or chargeback holds.\n\nSquare initiates its regular deposits as indicated in the\n[Deposit Options with Square](https://sq[...]",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "SETTLEMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "SETTLEMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/apple-pay/domains": {
      "post": {
        "tags": [
          "ApplePay"
        ],
        "summary": "RegisterDomain",
        "operationId": "RegisterDomain",
        "description": "Activates a domain for use with Apple Pay on the Web and Square. A validation\nis performed on this domain by Apple to ensure that it is properly set up as\nan Apple Pay enabled domain.\n\nThis endpoint provides an easy way for platform developers to bulk activate\nApple Pay on the Web with Square for merchants using their platform.\n\nNote: The SqPaymentForm library is deprecated as of May 13, 2021, and will only receive critical security updates until it is retired on O[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v2/bank-accounts": {
      "get": {
        "tags": [
          "BankAccounts"
        ],
        "summary": "ListBankAccounts",
        "operationId": "ListBankAccounts",
        "description": "Returns a list of [BankAccount](https://developer.squareup.com/reference/square_2023-07-20/objects/BankAccount) objects linked to a Square account.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "BANK_ACCOUNTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "BANK_ACCOUNTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bank-accounts/by-v1-id/{v1_bank_account_id}": {
      "get": {
        "tags": [
          "BankAccounts"
        ],
        "summary": "GetBankAccountByV1Id",
        "operationId": "GetBankAccountByV1Id",
        "description": "Returns details of a [BankAccount](https://developer.squareup.com/reference/square_2023-07-20/objects/BankAccount) identified by V1 bank account ID.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "BANK_ACCOUNTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "BANK_ACCOUNTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bank-accounts/{bank_account_id}": {
      "get": {
        "tags": [
          "BankAccounts"
        ],
        "summary": "GetBankAccount",
        "operationId": "GetBankAccount",
        "description": "Returns details of a [BankAccount](https://developer.squareup.com/reference/square_2023-07-20/objects/BankAccount)\nlinked to a Square account.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "BANK_ACCOUNTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "BANK_ACCOUNTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings": {
      "get": {
        "tags": [
          "Bookings"
        ],
        "summary": "ListBookings",
        "operationId": "ListBookings",
        "description": "Retrieve a collection of bookings.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "APPOINTMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Bookings"
        ],
        "summary": "CreateBooking",
        "operationId": "CreateBooking",
        "description": "Creates a booking.\n\nThe required input must include the following:\n- `Booking.location_id`\n- `Booking.start_at`\n- `Booking.team_member_id`\n- `Booking.AppointmentSegment.service_variation_id`\n- `Booking.AppointmentSegment.service_variation_version`\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAut[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "APPOINTMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/bookings/availability/search": {
      "post": {
        "tags": [
          "Bookings"
        ],
        "summary": "SearchAvailability",
        "operationId": "SearchAvailability",
        "description": "Searches for availabilities for booking.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "APPOINTMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings/business-booking-profile": {
      "get": {
        "tags": [
          "Bookings"
        ],
        "summary": "RetrieveBusinessBookingProfile",
        "operationId": "RetrieveBusinessBookingProfile",
        "description": "Retrieves a seller\u0027s booking profile.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "APPOINTMENTS_BUSINESS_SETTINGS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_BUSINESS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings/custom-attribute-definitions": {
      "get": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "ListBookingCustomAttributeDefinitions",
        "operationId": "ListBookingCustomAttributeDefinitions",
        "description": "Get all bookings custom attribute definitions.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "APPOINTMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "CreateBookingCustomAttributeDefinition",
        "operationId": "CreateBookingCustomAttributeDefinition",
        "description": "Creates a bookings custom attribute definition.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "APPOINTMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/bookings/custom-attribute-definitions/{key}": {
      "delete": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "DeleteBookingCustomAttributeDefinition",
        "operationId": "DeleteBookingCustomAttributeDefinition",
        "description": "Deletes a bookings custom attribute definition.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "APPOINTMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "RetrieveBookingCustomAttributeDefinition",
        "operationId": "RetrieveBookingCustomAttributeDefinition",
        "description": "Retrieves a bookings custom attribute definition.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "APPOINTMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "UpdateBookingCustomAttributeDefinition",
        "operationId": "UpdateBookingCustomAttributeDefinition",
        "description": "Updates a bookings custom attribute definition.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "APPOINTMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/bookings/custom-attributes/bulk-delete": {
      "post": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "BulkDeleteBookingCustomAttributes",
        "operationId": "BulkDeleteBookingCustomAttributes",
        "description": "Bulk deletes bookings custom attributes.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "APPOINTMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/bookings/custom-attributes/bulk-upsert": {
      "post": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "BulkUpsertBookingCustomAttributes",
        "operationId": "BulkUpsertBookingCustomAttributes",
        "description": "Bulk upserts bookings custom attributes.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "APPOINTMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/bookings/team-member-booking-profiles": {
      "get": {
        "tags": [
          "Bookings"
        ],
        "summary": "ListTeamMemberBookingProfiles",
        "operationId": "ListTeamMemberBookingProfiles",
        "description": "Lists booking profiles for team members.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "APPOINTMENTS_BUSINESS_SETTINGS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_BUSINESS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings/team-member-booking-profiles/{team_member_id}": {
      "get": {
        "tags": [
          "Bookings"
        ],
        "summary": "RetrieveTeamMemberBookingProfile",
        "operationId": "RetrieveTeamMemberBookingProfile",
        "description": "Retrieves a team member\u0027s booking profile.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "APPOINTMENTS_BUSINESS_SETTINGS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_BUSINESS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings/{booking_id}": {
      "get": {
        "tags": [
          "Bookings"
        ],
        "summary": "RetrieveBooking",
        "operationId": "RetrieveBooking",
        "description": "Retrieves a booking.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "APPOINTMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Bookings"
        ],
        "summary": "UpdateBooking",
        "operationId": "UpdateBooking",
        "description": "Updates a booking.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "APPOINTMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/bookings/{booking_id}/cancel": {
      "post": {
        "tags": [
          "Bookings"
        ],
        "summary": "CancelBooking",
        "operationId": "CancelBooking",
        "description": "Cancels an existing booking.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "APPOINTMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/bookings/{booking_id}/custom-attributes": {
      "get": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "ListBookingCustomAttributes",
        "operationId": "ListBookingCustomAttributes",
        "description": "Lists a booking\u0027s custom attributes.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "APPOINTMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings/{booking_id}/custom-attributes/{key}": {
      "delete": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "DeleteBookingCustomAttribute",
        "operationId": "DeleteBookingCustomAttribute",
        "description": "Deletes a bookings custom attribute.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "APPOINTMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "RetrieveBookingCustomAttribute",
        "operationId": "RetrieveBookingCustomAttribute",
        "description": "Retrieves a bookings custom attribute.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "APPOINTMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "UpsertBookingCustomAttribute",
        "operationId": "UpsertBookingCustomAttribute",
        "description": "Upserts a bookings custom attribute.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "APPOINTMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/cards": {
      "get": {
        "tags": [
          "Cards"
        ],
        "summary": "ListCards",
        "operationId": "ListCards",
        "description": "Retrieves a list of cards owned by the account making the request.\nA max of 25 cards will be returned.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "CreateCard",
        "operationId": "CreateCard",
        "description": "Adds a card on file to an existing merchant.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/cards/{card_id}": {
      "get": {
        "tags": [
          "Cards"
        ],
        "summary": "RetrieveCard",
        "operationId": "RetrieveCard",
        "description": "Retrieves details for a specific Card.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/cards/{card_id}/disable": {
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "DisableCard",
        "operationId": "DisableCard",
        "description": "Disables the card, preventing any further updates or charges.\nDisabling an already disabled card is allowed but has no effect.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/cash-drawers/shifts": {
      "get": {
        "tags": [
          "CashDrawers"
        ],
        "summary": "ListCashDrawerShifts",
        "operationId": "ListCashDrawerShifts",
        "description": "Provides the details for all of the cash drawer shifts for a location\nin a date range.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CASH_DRAWER_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CASH_DRAWER_READ"
            ]
          }
        ]
      }
    },
    "/v2/cash-drawers/shifts/{shift_id}": {
      "get": {
        "tags": [
          "CashDrawers"
        ],
        "summary": "RetrieveCashDrawerShift",
        "operationId": "RetrieveCashDrawerShift",
        "description": "Provides the summary details for a single cash drawer shift. See\n[ListCashDrawerShiftEvents](https://developer.squareup.com/reference/square_2023-07-20/cash-drawers-api/list-cash-drawer-shift-events) for a list of cash drawer shift events.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CASH_DRAWER_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CASH_DRAWER_READ"
            ]
          }
        ]
      }
    },
    "/v2/cash-drawers/shifts/{shift_id}/events": {
      "get": {
        "tags": [
          "CashDrawers"
        ],
        "summary": "ListCashDrawerShiftEvents",
        "operationId": "ListCashDrawerShiftEvents",
        "description": "Provides a paginated list of events for a single cash drawer shift.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CASH_DRAWER_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CASH_DRAWER_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/batch-delete": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "BatchDeleteCatalogObjects",
        "operationId": "BatchDeleteCatalogObjects",
        "description": "Deletes a set of [CatalogItem](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogItem)s based on the\nprovided list of target IDs and returns a set of successfully deleted IDs in\nthe response. Deletion is a cascading event such that all children of the\ntargeted object are also deleted. For example, deleting a CatalogItem will\nalso delete all of its [CatalogItemVariation](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogI[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/catalog/batch-retrieve": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "BatchRetrieveCatalogObjects",
        "operationId": "BatchRetrieveCatalogObjects",
        "description": "Returns a set of objects based on the provided ID.\nEach [CatalogItem](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogItem) returned in the set includes all of its\nchild information including: all of its\n[CatalogItemVariation](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogItemVariation) objects, references to\nits [CatalogModifierList](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogModifie[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/batch-upsert": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "BatchUpsertCatalogObjects",
        "operationId": "BatchUpsertCatalogObjects",
        "description": "Creates or updates up to 10,000 target objects based on the provided\nlist of objects. The target objects are grouped into batches and each batch is\ninserted/updated in an all-or-nothing manner. If an object within a batch is\nmalformed in some way, or violates a database constraint, the entire batch\ncontaining that item will be disregarded. However, other batches in the same\nrequest may still succeed. Each batch may contain up to 1,000 objects, and\nbatches will be pr[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/catalog/info": {
      "get": {
        "tags": [
          "Catalog"
        ],
        "summary": "CatalogInfo",
        "operationId": "CatalogInfo",
        "description": "Retrieves information about the Square Catalog API, such as batch size\nlimits that can be used by the `BatchUpsertCatalogObjects` endpoint.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/list": {
      "get": {
        "tags": [
          "Catalog"
        ],
        "summary": "ListCatalog",
        "operationId": "ListCatalog",
        "description": "Returns a list of all [CatalogObject](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogObject)s of the specified types in the catalog. \n\nThe `types` parameter is specified as a comma-separated list of the [CatalogObjectType](https://developer.squareup.com/reference/square_2023-07-20/enums/CatalogObjectType) values, \nfor example, \"`ITEM`, `ITEM_VARIATION`, `MODIFIER`, `MODIFIER_LIST`, `CATEGORY`, `DISCOUNT`, `TAX`, `IMAGE`\".\n\n__Important:__ [...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/object": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "UpsertCatalogObject",
        "operationId": "UpsertCatalogObject",
        "description": "Creates a new or updates the specified [CatalogObject](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogObject).\n\nTo ensure consistency, only one update request is processed at a time per seller account.  \nWhile one (batch or non-batch) update request is being processed, other (batched and non-batched) \nupdate requests are rejected with the `429` error code.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/catalog/object/{object_id}": {
      "delete": {
        "tags": [
          "Catalog"
        ],
        "summary": "DeleteCatalogObject",
        "operationId": "DeleteCatalogObject",
        "description": "Deletes a single [CatalogObject](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogObject) based on the\nprovided ID and returns the set of successfully deleted IDs in the response.\nDeletion is a cascading event such that all children of the targeted object\nare also deleted. For example, deleting a [CatalogItem](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogItem)\nwill also delete all of its\n[CatalogItemVariation](htt[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Catalog"
        ],
        "summary": "RetrieveCatalogObject",
        "operationId": "RetrieveCatalogObject",
        "description": "Returns a single [CatalogItem](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogItem) as a\n[CatalogObject](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogObject) based on the provided ID. The returned\nobject includes all of the relevant [CatalogItem](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogItem)\ninformation including: [CatalogItemVariation](https://developer.squareup.com/reference/squ[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/search": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "SearchCatalogObjects",
        "operationId": "SearchCatalogObjects",
        "description": "Searches for [CatalogObject](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogObject) of any type by matching supported search attribute values,\nexcluding custom attribute values on items or item variations, against one or more of the specified query filters.\n\nThis (`SearchCatalogObjects`) endpoint differs from the [SearchCatalogItems](https://developer.squareup.com/reference/square_2023-07-20/catalog-api/search-catalog-items)\nendpoint in the [...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/search-catalog-items": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "SearchCatalogItems",
        "operationId": "SearchCatalogItems",
        "description": "Searches for catalog items or item variations by matching supported search attribute values, including\ncustom attribute values, against one or more of the specified query filters.\n\nThis (`SearchCatalogItems`) endpoint differs from the [SearchCatalogObjects](https://developer.squareup.com/reference/square_2023-07-20/catalog-api/search-catalog-objects)\nendpoint in the following aspects:\n\n- `SearchCatalogItems` can only search for items or item variations, whereas `Sea[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/update-item-modifier-lists": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "UpdateItemModifierLists",
        "operationId": "UpdateItemModifierLists",
        "description": "Updates the [CatalogModifierList](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogModifierList) objects\nthat apply to the targeted [CatalogItem](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogItem) without having\nto perform an upsert on the entire item.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/catalog/update-item-taxes": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "UpdateItemTaxes",
        "operationId": "UpdateItemTaxes",
        "description": "Updates the [CatalogTax](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogTax) objects that apply to the\ntargeted [CatalogItem](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogItem) without having to perform an\nupsert on the entire item.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers": {
      "get": {
        "tags": [
          "Customers"
        ],
        "summary": "ListCustomers",
        "operationId": "ListCustomers",
        "description": "Lists customer profiles associated with a Square account.\n\nUnder normal operating conditions, newly created or updated customer profiles become available\nfor the listing operation in well under 30 seconds. Occasionally, propagation of the new or updated\nprofiles can take closer to one minute or longer, especially during network incidents and outages.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "CreateCustomer",
        "operationId": "CreateCustomer",
        "description": "Creates a new customer for a business.\n\nYou must provide at least one of the following values in your request to this\nendpoint:\n\n- `given_name`\n- `family_name`\n- `company_name`\n- `email_address`\n- `phone_number`",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/custom-attribute-definitions": {
      "get": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "ListCustomerCustomAttributeDefinitions",
        "operationId": "ListCustomerCustomAttributeDefinitions",
        "description": "Lists the customer-related [custom attribute definitions](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) that belong to a Square seller account.\n\nWhen all response pages are retrieved, the results include all custom attribute definitions\nthat are visible to the requesting application, including those that are created by other\napplications and set to `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`. Note that\nsell[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "CreateCustomerCustomAttributeDefinition",
        "operationId": "CreateCustomerCustomAttributeDefinition",
        "description": "Creates a customer-related [custom attribute definition](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) for a Square seller account.\nUse this endpoint to define a custom attribute that can be associated with customer profiles.\n\nA custom attribute definition specifies the `key`, `visibility`, `schema`, and other properties\nfor a custom attribute. After the definition is created, you can call\n[UpsertCustomerCustomAttribute[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/custom-attribute-definitions/{key}": {
      "delete": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "DeleteCustomerCustomAttributeDefinition",
        "operationId": "DeleteCustomerCustomAttributeDefinition",
        "description": "Deletes a customer-related [custom attribute definition](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) from a Square seller account.\n\nDeleting a custom attribute definition also deletes the corresponding custom attribute from\nall customer profiles in the seller\u0027s Customer Directory.\n\nOnly the definition owner can delete a custom attribute definition.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "RetrieveCustomerCustomAttributeDefinition",
        "operationId": "RetrieveCustomerCustomAttributeDefinition",
        "description": "Retrieves a customer-related [custom attribute definition](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) from a Square seller account.\n\nTo retrieve a custom attribute definition created by another application, the `visibility`\nsetting must be `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`. Note that seller-defined custom attributes\n(also known as custom fields) are always set to `VISIBILITY_READ_WRITE_VALUES`."[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "UpdateCustomerCustomAttributeDefinition",
        "operationId": "UpdateCustomerCustomAttributeDefinition",
        "description": "Updates a customer-related [custom attribute definition](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) for a Square seller account.\n\nUse this endpoint to update the following fields: `name`, `description`, `visibility`, or the\n`schema` for a `Selection` data type.\n\nOnly the definition owner can update a custom attribute definition. Note that sellers can view\nall custom attributes in exported customer data, including th[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/custom-attributes/bulk-upsert": {
      "post": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "BulkUpsertCustomerCustomAttributes",
        "operationId": "BulkUpsertCustomerCustomAttributes",
        "description": "Creates or updates [custom attributes](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) for customer profiles as a bulk operation.\n\nUse this endpoint to set the value of one or more custom attributes for one or more customer profiles.\nA custom attribute is based on a custom attribute definition in a Square seller account, which is\ncreated using the [CreateCustomerCustomAttributeDefinition](https://developer.squareup.com/reference/squ[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/groups": {
      "get": {
        "tags": [
          "CustomerGroups"
        ],
        "summary": "ListCustomerGroups",
        "operationId": "ListCustomerGroups",
        "description": "Retrieves the list of customer groups of a business.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "CustomerGroups"
        ],
        "summary": "CreateCustomerGroup",
        "operationId": "CreateCustomerGroup",
        "description": "Creates a new customer group for a business.\n\nThe request must include the `name` value of the group.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/groups/{group_id}": {
      "delete": {
        "tags": [
          "CustomerGroups"
        ],
        "summary": "DeleteCustomerGroup",
        "operationId": "DeleteCustomerGroup",
        "description": "Deletes a customer group as identified by the `group_id` value.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "CustomerGroups"
        ],
        "summary": "RetrieveCustomerGroup",
        "operationId": "RetrieveCustomerGroup",
        "description": "Retrieves a specific customer group as identified by the `group_id` value.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "CustomerGroups"
        ],
        "summary": "UpdateCustomerGroup",
        "operationId": "UpdateCustomerGroup",
        "description": "Updates a customer group as identified by the `group_id` value.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/search": {
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "SearchCustomers",
        "operationId": "SearchCustomers",
        "description": "Searches the customer profiles associated with a Square account using one or more supported query filters.\n\nCalling `SearchCustomers` without any explicit query filter returns all\ncustomer profiles ordered alphabetically based on `given_name` and\n`family_name`.\n\nUnder normal operating conditions, newly created or updated customer profiles become available\nfor the search operation in well under 30 seconds. Occasionally, propagation of the new or updated\nprofiles ca[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/customers/segments": {
      "get": {
        "tags": [
          "CustomerSegments"
        ],
        "summary": "ListCustomerSegments",
        "operationId": "ListCustomerSegments",
        "description": "Retrieves the list of customer segments of a business.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/customers/segments/{segment_id}": {
      "get": {
        "tags": [
          "CustomerSegments"
        ],
        "summary": "RetrieveCustomerSegment",
        "operationId": "RetrieveCustomerSegment",
        "description": "Retrieves a specific customer segment as identified by the `segment_id` value.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}": {
      "delete": {
        "tags": [
          "Customers"
        ],
        "summary": "DeleteCustomer",
        "operationId": "DeleteCustomer",
        "description": "Deletes a customer profile from a business. This operation also unlinks any associated cards on file. \n\nAs a best practice, include the `version` field in the request to enable [optimistic concurrency](https://developer.squareup.com/docs/build-basics/common-api-patterns/optimistic-concurrency) control.\nIf included, the value must be set to the current version of the customer profile. \n\nTo delete a customer profile that was created by merging existing profiles, you mu[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Customers"
        ],
        "summary": "RetrieveCustomer",
        "operationId": "RetrieveCustomer",
        "description": "Returns details for a single customer.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Customers"
        ],
        "summary": "UpdateCustomer",
        "operationId": "UpdateCustomer",
        "description": "Updates a customer profile. This endpoint supports sparse updates, so only new or changed fields are required in the request.\nTo add or update a field, specify the new value. To remove a field, specify `null` and include the `X-Clear-Null` header set to `true`\n(recommended) or specify an empty string (string fields only).\n\nAs a best practice, include the `version` field in the request to enable [optimistic concurrency](https://developer.squareup.com/docs/build-basics/[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}/cards": {
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "CreateCustomerCard",
        "operationId": "CreateCustomerCard",
        "description": "Adds a card on file to an existing customer.\n\nAs with charges, calls to `CreateCustomerCard` are idempotent. Multiple\ncalls with the same card nonce return the same card record that was created\nwith the provided nonce during the _first_ call.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}/cards/{card_id}": {
      "delete": {
        "tags": [
          "Customers"
        ],
        "summary": "DeleteCustomerCard",
        "operationId": "DeleteCustomerCard",
        "description": "Removes a card on file from a customer.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}/custom-attributes": {
      "get": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "ListCustomerCustomAttributes",
        "operationId": "ListCustomerCustomAttributes",
        "description": "Lists the [custom attributes](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) associated with a customer profile.\n\nYou can use the `with_definitions` query parameter to also retrieve custom attribute definitions\nin the same call.\n\nWhen all response pages are retrieved, the results include all custom attributes that are\nvisible to the requesting application, including those that are owned by other applications\nand set to `VISIBILI[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}/custom-attributes/{key}": {
      "delete": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "DeleteCustomerCustomAttribute",
        "operationId": "DeleteCustomerCustomAttribute",
        "description": "Deletes a [custom attribute](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) associated with a customer profile.\n\nTo delete a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_WRITE_VALUES`. Note that seller-defined custom attributes\n(also known as custom fields) are always set to `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "RetrieveCustomerCustomAttribute",
        "operationId": "RetrieveCustomerCustomAttribute",
        "description": "Retrieves a [custom attribute](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) associated with a customer profile.\n\nYou can use the `with_definition` query parameter to also retrieve the custom attribute definition\nin the same call.\n\nTo retrieve a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`. Note that seller-defined custom attributes\n(als[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "UpsertCustomerCustomAttribute",
        "operationId": "UpsertCustomerCustomAttribute",
        "description": "Creates or updates a [custom attribute](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) for a customer profile.\n\nUse this endpoint to set the value of a custom attribute for a specified customer profile.\nA custom attribute is based on a custom attribute definition in a Square seller account, which\nis created using the [CreateCustomerCustomAttributeDefinition](https://developer.squareup.com/reference/square_2023-07-20/customer-custom[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}/groups/{group_id}": {
      "delete": {
        "tags": [
          "Customers"
        ],
        "summary": "RemoveGroupFromCustomer",
        "operationId": "RemoveGroupFromCustomer",
        "description": "Removes a group membership from a customer.\n\nThe customer is identified by the `customer_id` value\nand the customer group is identified by the `group_id` value.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Customers"
        ],
        "summary": "AddGroupToCustomer",
        "operationId": "AddGroupToCustomer",
        "description": "Adds a group membership to a customer.\n\nThe customer is identified by the `customer_id` value\nand the customer group is identified by the `group_id` value.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/devices/codes": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "ListDeviceCodes",
        "operationId": "ListDeviceCodes",
        "description": "Lists all DeviceCodes associated with the merchant.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "DEVICE_CREDENTIAL_MANAGEMENT"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "DEVICE_CREDENTIAL_MANAGEMENT"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Devices"
        ],
        "summary": "CreateDeviceCode",
        "operationId": "CreateDeviceCode",
        "description": "Creates a DeviceCode that can be used to login to a Square Terminal device to enter the connected\nterminal mode.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "DEVICE_CREDENTIAL_MANAGEMENT"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "DEVICE_CREDENTIAL_MANAGEMENT"
            ]
          }
        ]
      }
    },
    "/v2/devices/codes/{id}": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "GetDeviceCode",
        "operationId": "GetDeviceCode",
        "description": "Retrieves DeviceCode with the associated ID.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "DEVICE_CREDENTIAL_MANAGEMENT"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "DEVICE_CREDENTIAL_MANAGEMENT"
            ]
          }
        ]
      }
    },
    "/v2/disputes": {
      "get": {
        "tags": [
          "Disputes"
        ],
        "summary": "ListDisputes",
        "operationId": "ListDisputes",
        "description": "Returns a list of disputes associated with a particular account.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "DISPUTES_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "DISPUTES_READ"
            ]
          }
        ]
      }
    },
    "/v2/disputes/{dispute_id}": {
      "get": {
        "tags": [
          "Disputes"
        ],
        "summary": "RetrieveDispute",
        "operationId": "RetrieveDispute",
        "description": "Returns details about a specific dispute.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "DISPUTES_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "DISPUTES_READ"
            ]
          }
        ]
      }
    },
    "/v2/disputes/{dispute_id}/accept": {
      "post": {
        "tags": [
          "Disputes"
        ],
        "summary": "AcceptDispute",
        "operationId": "AcceptDispute",
        "description": "Accepts the loss on a dispute. Square returns the disputed amount to the cardholder and\nupdates the dispute state to ACCEPTED.\n\nSquare debits the disputed amount from the seller’s Square account. If the Square account\ndoes not have sufficient funds, Square debits the associated bank account.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "DISPUTES_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "DISPUTES_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/disputes/{dispute_id}/evidence": {
      "get": {
        "tags": [
          "Disputes"
        ],
        "summary": "ListDisputeEvidence",
        "operationId": "ListDisputeEvidence",
        "description": "Returns a list of evidence associated with a dispute.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "DISPUTES_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "DISPUTES_READ"
            ]
          }
        ]
      }
    },
    "/v2/disputes/{dispute_id}/evidence-text": {
      "post": {
        "tags": [
          "Disputes"
        ],
        "summary": "CreateDisputeEvidenceText",
        "operationId": "CreateDisputeEvidenceText",
        "description": "Uploads text to use as evidence for a dispute challenge.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "DISPUTES_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "DISPUTES_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/disputes/{dispute_id}/evidence/{evidence_id}": {
      "delete": {
        "tags": [
          "Disputes"
        ],
        "summary": "DeleteDisputeEvidence",
        "operationId": "DeleteDisputeEvidence",
        "description": "Removes specified evidence from a dispute.\nSquare does not send the bank any evidence that is removed.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "DISPUTES_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "DISPUTES_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Disputes"
        ],
        "summary": "RetrieveDisputeEvidence",
        "operationId": "RetrieveDisputeEvidence",
        "description": "Returns the metadata for the evidence specified in the request URL path.\n\nYou must maintain a copy of any evidence uploaded if you want to reference it later. Evidence cannot be downloaded after you upload it.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "DISPUTES_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "DISPUTES_READ"
            ]
          }
        ]
      }
    },
    "/v2/disputes/{dispute_id}/submit-evidence": {
      "post": {
        "tags": [
          "Disputes"
        ],
        "summary": "SubmitEvidence",
        "operationId": "SubmitEvidence",
        "description": "Submits evidence to the cardholder\u0027s bank.\n\nThe evidence submitted by this endpoint includes evidence uploaded\nusing the [CreateDisputeEvidenceFile](https://developer.squareup.com/reference/square_2023-07-20/disputes-api/create-dispute-evidence-file) and\n[CreateDisputeEvidenceText](https://developer.squareup.com/reference/square_2023-07-20/disputes-api/create-dispute-evidence-text) endpoints and\nevidence automatically provided by Square, when available. Evidence[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "DISPUTES_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "DISPUTES_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/employees": {
      "get": {
        "tags": [
          "Employees"
        ],
        "summary": "ListEmployees",
        "operationId": "ListEmployees",
        "description": "",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "EMPLOYEES_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/employees/{id}": {
      "get": {
        "tags": [
          "Employees"
        ],
        "summary": "RetrieveEmployee",
        "operationId": "RetrieveEmployee",
        "description": "",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "EMPLOYEES_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/gift-cards": {
      "get": {
        "tags": [
          "GiftCards"
        ],
        "summary": "ListGiftCards",
        "operationId": "ListGiftCards",
        "description": "Lists all gift cards. You can specify optional filters to retrieve \na subset of the gift cards. Results are sorted by `created_at` in ascending order.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "GIFTCARDS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "GiftCards"
        ],
        "summary": "CreateGiftCard",
        "operationId": "CreateGiftCard",
        "description": "Creates a digital gift card or registers a physical (plastic) gift card. After the gift card \nis created, you must call [CreateGiftCardActivity](https://developer.squareup.com/reference/square_2023-07-20/gift-card-activities-api/create-gift-card-activity) \nto activate the card with an initial balance before it can be used for payment.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "GIFTCARDS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/gift-cards/activities": {
      "get": {
        "tags": [
          "GiftCardActivities"
        ],
        "summary": "ListGiftCardActivities",
        "operationId": "ListGiftCardActivities",
        "description": "Lists gift card activities. By default, you get gift card activities for all\ngift cards in the seller\u0027s account. You can optionally specify query parameters to\nfilter the list. For example, you can get a list of gift card activities for a gift card,\nfor all gift cards in a specific region, or for activities within a time window.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "GIFTCARDS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "GiftCardActivities"
        ],
        "summary": "CreateGiftCardActivity",
        "operationId": "CreateGiftCardActivity",
        "description": "Creates a gift card activity to manage the balance or state of a [gift card](https://developer.squareup.com/reference/square_2023-07-20/objects/GiftCard). \nFor example, you create an `ACTIVATE` activity to activate a gift card with an initial balance \nbefore the gift card can be used.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "GIFTCARDS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/gift-cards/from-gan": {
      "post": {
        "tags": [
          "GiftCards"
        ],
        "summary": "RetrieveGiftCardFromGAN",
        "operationId": "RetrieveGiftCardFromGAN",
        "description": "Retrieves a gift card using the gift card account number (GAN).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "GIFTCARDS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_READ"
            ]
          }
        ]
      }
    },
    "/v2/gift-cards/from-nonce": {
      "post": {
        "tags": [
          "GiftCards"
        ],
        "summary": "RetrieveGiftCardFromNonce",
        "operationId": "RetrieveGiftCardFromNonce",
        "description": "Retrieves a gift card using a secure payment token that represents the gift card.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "GIFTCARDS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_READ"
            ]
          }
        ]
      }
    },
    "/v2/gift-cards/{gift_card_id}/link-customer": {
      "post": {
        "tags": [
          "GiftCards"
        ],
        "summary": "LinkCustomerToGiftCard",
        "operationId": "LinkCustomerToGiftCard",
        "description": "Links a customer to a gift card, which is also referred to as adding a card on file.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "GIFTCARDS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/gift-cards/{gift_card_id}/unlink-customer": {
      "post": {
        "tags": [
          "GiftCards"
        ],
        "summary": "UnlinkCustomerFromGiftCard",
        "operationId": "UnlinkCustomerFromGiftCard",
        "description": "Unlinks a customer from a gift card, which is also referred to as removing a card on file.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "GIFTCARDS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/gift-cards/{id}": {
      "get": {
        "tags": [
          "GiftCards"
        ],
        "summary": "RetrieveGiftCard",
        "operationId": "RetrieveGiftCard",
        "description": "Retrieves a gift card using the gift card ID.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "GIFTCARDS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/adjustment/{adjustment_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "DeprecatedRetrieveInventoryAdjustment",
        "operationId": "DeprecatedRetrieveInventoryAdjustment",
        "description": "Deprecated version of [RetrieveInventoryAdjustment](https://developer.squareup.com/reference/square_2023-07-20/inventory-api/retrieve-inventory-adjustment) after the endpoint URL\nis updated to conform to the standard convention.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/adjustments/{adjustment_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "RetrieveInventoryAdjustment",
        "operationId": "RetrieveInventoryAdjustment",
        "description": "Returns the [InventoryAdjustment](https://developer.squareup.com/reference/square_2023-07-20/objects/InventoryAdjustment) object\nwith the provided `adjustment_id`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/batch-change": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "DeprecatedBatchChangeInventory",
        "operationId": "DeprecatedBatchChangeInventory",
        "description": "Deprecated version of [BatchChangeInventory](https://developer.squareup.com/reference/square_2023-07-20/inventory-api/batch-change-inventory) after the endpoint URL\nis updated to conform to the standard convention.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "INVENTORY_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVENTORY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/inventory/batch-retrieve-changes": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "DeprecatedBatchRetrieveInventoryChanges",
        "operationId": "DeprecatedBatchRetrieveInventoryChanges",
        "description": "Deprecated version of [BatchRetrieveInventoryChanges](https://developer.squareup.com/reference/square_2023-07-20/inventory-api/batch-retrieve-inventory-changes) after the endpoint URL\nis updated to conform to the standard convention.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/batch-retrieve-counts": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "DeprecatedBatchRetrieveInventoryCounts",
        "operationId": "DeprecatedBatchRetrieveInventoryCounts",
        "description": "Deprecated version of [BatchRetrieveInventoryCounts](https://developer.squareup.com/reference/square_2023-07-20/inventory-api/batch-retrieve-inventory-counts) after the endpoint URL\nis updated to conform to the standard convention.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/changes/batch-create": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "BatchChangeInventory",
        "operationId": "BatchChangeInventory",
        "description": "Applies adjustments and counts to the provided item quantities.\n\nOn success: returns the current calculated counts for all objects\nreferenced in the request.\nOn failure: returns a list of related errors.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVENTORY_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVENTORY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/inventory/changes/batch-retrieve": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "BatchRetrieveInventoryChanges",
        "operationId": "BatchRetrieveInventoryChanges",
        "description": "Returns historical physical counts and adjustments based on the\nprovided filter criteria.\n\nResults are paginated and sorted in ascending order according their\n`occurred_at` timestamp (oldest first).\n\nBatchRetrieveInventoryChanges is a catch-all query endpoint for queries\nthat cannot be handled by other, simpler endpoints.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/counts/batch-retrieve": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "BatchRetrieveInventoryCounts",
        "operationId": "BatchRetrieveInventoryCounts",
        "description": "Returns current counts for the provided\n[CatalogObject](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogObject)s at the requested\n[Location](https://developer.squareup.com/reference/square_2023-07-20/objects/Location)s.\n\nResults are paginated and sorted in descending order according to their\n`calculated_at` timestamp (newest first).\n\nWhen `updated_after` is specified, only counts that have changed since that\ntime (based on the server time[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/physical-count/{physical_count_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "DeprecatedRetrieveInventoryPhysicalCount",
        "operationId": "DeprecatedRetrieveInventoryPhysicalCount",
        "description": "Deprecated version of [RetrieveInventoryPhysicalCount](https://developer.squareup.com/reference/square_2023-07-20/inventory-api/retrieve-inventory-physical-count) after the endpoint URL\nis updated to conform to the standard convention.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/physical-counts/{physical_count_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "RetrieveInventoryPhysicalCount",
        "operationId": "RetrieveInventoryPhysicalCount",
        "description": "Returns the [InventoryPhysicalCount](https://developer.squareup.com/reference/square_2023-07-20/objects/InventoryPhysicalCount)\nobject with the provided `physical_count_id`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/transfers/{transfer_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "RetrieveInventoryTransfer",
        "operationId": "RetrieveInventoryTransfer",
        "description": "Returns the [InventoryTransfer](https://developer.squareup.com/reference/square_2023-07-20/objects/InventoryTransfer) object\nwith the provided `transfer_id`.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/{catalog_object_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "RetrieveInventoryCount",
        "operationId": "RetrieveInventoryCount",
        "description": "Retrieves the current calculated stock count for a given\n[CatalogObject](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogObject) at a given set of\n[Location](https://developer.squareup.com/reference/square_2023-07-20/objects/Location)s. Responses are paginated and unsorted.\nFor more sophisticated queries, use a batch endpoint.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/{catalog_object_id}/changes": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "RetrieveInventoryChanges",
        "operationId": "RetrieveInventoryChanges",
        "description": "Returns a set of physical counts and inventory adjustments for the\nprovided [CatalogObject](https://developer.squareup.com/reference/square_2023-07-20/objects/CatalogObject) at the requested\n[Location](https://developer.squareup.com/reference/square_2023-07-20/objects/Location)s.\n\nYou can achieve the same result by calling [BatchRetrieveInventoryChanges](https://developer.squareup.com/reference/square_2023-07-20/inventory-api/batch-retrieve-inventory-changes)\nand hav[...]",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/invoices": {
      "get": {
        "tags": [
          "Invoices"
        ],
        "summary": "ListInvoices",
        "operationId": "ListInvoices",
        "description": "Returns a list of invoices for a given location. The response \nis paginated. If truncated, the response includes a `cursor` that you    \nuse in a subsequent request to retrieve the next set of invoices.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVOICES_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVOICES_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Invoices"
        ],
        "summary": "CreateInvoice",
        "operationId": "CreateInvoice",
        "description": "Creates a draft [invoice](https://developer.squareup.com/reference/square_2023-07-20/objects/Invoice) \nfor an order created using the Orders API.\n\nA draft invoice remains in your account and no action is taken. \nYou must publish the invoice before Square can process it (send it to the customer\u0027s email address or charge the customer’s card on file).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ORDERS_WRITE",
          "INVOICES_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE",
              "INVOICES_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/invoices/search": {
      "post": {
        "tags": [
          "Invoices"
        ],
        "summary": "SearchInvoices",
        "operationId": "SearchInvoices",
        "description": "Searches for invoices from a location specified in \nthe filter. You can optionally specify customers in the filter for whom to \nretrieve invoices. In the current implementation, you can only specify one location and \noptionally one customer.\n\nThe response is paginated. If truncated, the response includes a `cursor` \nthat you use in a subsequent request to retrieve the next set of invoices.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVOICES_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVOICES_READ"
            ]
          }
        ]
      }
    },
    "/v2/invoices/{invoice_id}": {
      "delete": {
        "tags": [
          "Invoices"
        ],
        "summary": "DeleteInvoice",
        "operationId": "DeleteInvoice",
        "description": "Deletes the specified invoice. When an invoice is deleted, the \nassociated order status changes to CANCELED. You can only delete a draft \ninvoice (you cannot delete a published invoice, including one that is scheduled for processing).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ORDERS_WRITE",
          "INVOICES_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE",
              "INVOICES_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Invoices"
        ],
        "summary": "GetInvoice",
        "operationId": "GetInvoice",
        "description": "Retrieves an invoice by invoice ID.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVOICES_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "INVOICES_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Invoices"
        ],
        "summary": "UpdateInvoice",
        "operationId": "UpdateInvoice",
        "description": "Updates an invoice by modifying fields, clearing fields, or both. For most updates, you can use a sparse \n`Invoice` object to add fields or change values and use the `fields_to_clear` field to specify fields to clear. \nHowever, some restrictions apply. For example, you cannot change the `order_id` or `location_id` field and you \nmust provide the complete `custom_fields` list to update a custom field. Published invoices have additional restrictions.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ORDERS_WRITE",
          "INVOICES_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE",
              "INVOICES_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/invoices/{invoice_id}/cancel": {
      "post": {
        "tags": [
          "Invoices"
        ],
        "summary": "CancelInvoice",
        "operationId": "CancelInvoice",
        "description": "Cancels an invoice. The seller cannot collect payments for \nthe canceled invoice.\n\nYou cannot cancel an invoice in the `DRAFT` state or in a terminal state: `PAID`, `REFUNDED`, `CANCELED`, or `FAILED`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ORDERS_WRITE",
          "INVOICES_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE",
              "INVOICES_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/invoices/{invoice_id}/publish": {
      "post": {
        "tags": [
          "Invoices"
        ],
        "summary": "PublishInvoice",
        "operationId": "PublishInvoice",
        "description": "Publishes the specified draft invoice. \n\nAfter an invoice is published, Square \nfollows up based on the invoice configuration. For example, Square \nsends the invoice to the customer\u0027s email address, charges the customer\u0027s card on file, or does \nnothing. Square also makes the invoice available on a Square-hosted invoice page. \n\nThe invoice `status` also changes from `DRAFT` to a status \nbased on the invoice configuration. For example, the status changes t[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ORDERS_WRITE",
          "INVOICES_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE",
              "INVOICES_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/labor/break-types": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "ListBreakTypes",
        "operationId": "ListBreakTypes",
        "description": "Returns a paginated list of `BreakType` instances for a business.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "CreateBreakType",
        "operationId": "CreateBreakType",
        "description": "Creates a new `BreakType`.\n\nA `BreakType` is a template for creating `Break` objects.\nYou must provide the following values in your request to this\nendpoint:\n\n- `location_id`\n- `break_name`\n- `expected_duration`\n- `is_paid`\n\nYou can only have three `BreakType` instances per location. If you attempt to add a fourth\n`BreakType` for a location, an `INVALID_REQUEST_ERROR` \"Exceeded limit of 3 breaks per location.\"\nis returned.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/labor/break-types/{id}": {
      "delete": {
        "tags": [
          "Labor"
        ],
        "summary": "DeleteBreakType",
        "operationId": "DeleteBreakType",
        "description": "Deletes an existing `BreakType`.\n\nA `BreakType` can be deleted even if it is referenced from a `Shift`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "GetBreakType",
        "operationId": "GetBreakType",
        "description": "Returns a single `BreakType` specified by `id`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Labor"
        ],
        "summary": "UpdateBreakType",
        "operationId": "UpdateBreakType",
        "description": "Updates an existing `BreakType`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_WRITE",
          "TIMECARDS_SETTINGS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_WRITE",
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/employee-wages": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "ListEmployeeWages",
        "operationId": "ListEmployeeWages",
        "description": "Returns a paginated list of `EmployeeWage` instances for a business.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "EMPLOYEES_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/employee-wages/{id}": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "GetEmployeeWage",
        "operationId": "GetEmployeeWage",
        "description": "Returns a single `EmployeeWage` specified by `id`.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "EMPLOYEES_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/shifts": {
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "CreateShift",
        "operationId": "CreateShift",
        "description": "Creates a new `Shift`.\n\nA `Shift` represents a complete workday for a single employee.\nYou must provide the following values in your request to this\nendpoint:\n\n- `location_id`\n- `employee_id`\n- `start_at`\n\nAn attempt to create a new `Shift` can result in a `BAD_REQUEST` error when:\n- The `status` of the new `Shift` is `OPEN` and the employee has another\nshift with an `OPEN` status.\n- The `start_at` date is in the future.\n- The `start_at` or `end_at` date ove[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/labor/shifts/search": {
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "SearchShifts",
        "operationId": "SearchShifts",
        "description": "Returns a paginated list of `Shift` records for a business.\nThe list to be returned can be filtered by:\n- Location IDs.\n- Employee IDs.\n- Shift status (`OPEN` and `CLOSED`).\n- Shift start.\n- Shift end.\n- Workday details.\n\nThe list can be sorted by:\n- `start_at`.\n- `end_at`.\n- `created_at`.\n- `updated_at`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/shifts/{id}": {
      "delete": {
        "tags": [
          "Labor"
        ],
        "summary": "DeleteShift",
        "operationId": "DeleteShift",
        "description": "Deletes a `Shift`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "GetShift",
        "operationId": "GetShift",
        "description": "Returns a single `Shift` specified by `id`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Labor"
        ],
        "summary": "UpdateShift",
        "operationId": "UpdateShift",
        "description": "Updates an existing `Shift`.\n\nWhen adding a `Break` to a `Shift`, any earlier `Break` instances in the `Shift` have\nthe `end_at` property set to a valid RFC-3339 datetime string.\n\nWhen closing a `Shift`, all `Break` instances in the `Shift` must be complete with `end_at`\nset on each `Break`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_WRITE",
          "TIMECARDS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE",
              "TIMECARDS_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/team-member-wages": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "ListTeamMemberWages",
        "operationId": "ListTeamMemberWages",
        "description": "Returns a paginated list of `TeamMemberWage` instances for a business.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "EMPLOYEES_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/team-member-wages/{id}": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "GetTeamMemberWage",
        "operationId": "GetTeamMemberWage",
        "description": "Returns a single `TeamMemberWage` specified by `id `.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "EMPLOYEES_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/workweek-configs": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "ListWorkweekConfigs",
        "operationId": "ListWorkweekConfigs",
        "description": "Returns a list of `WorkweekConfig` instances for a business.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/workweek-configs/{id}": {
      "put": {
        "tags": [
          "Labor"
        ],
        "summary": "UpdateWorkweekConfig",
        "operationId": "UpdateWorkweekConfig",
        "description": "Updates a `WorkweekConfig`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_WRITE",
          "TIMECARDS_SETTINGS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_WRITE",
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "ListLocations",
        "operationId": "ListLocations",
        "description": "Provides details about all of the seller\u0027s [locations](https://developer.squareup.com/docs/locations-api),\nincluding those with an inactive status.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Locations"
        ],
        "summary": "CreateLocation",
        "operationId": "CreateLocation",
        "description": "Creates a [location](https://developer.squareup.com/docs/locations-api).\nCreating new locations allows for separate configuration of receipt layouts, item prices,\nand sales reports. Developers can use locations to separate sales activity through applications\nthat integrate with Square from sales activity elsewhere in a seller\u0027s account.\nLocations created programmatically with the Locations API last forever and\nare visible to the seller for their own management. [...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/custom-attribute-definitions": {
      "get": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "ListLocationCustomAttributeDefinitions",
        "operationId": "ListLocationCustomAttributeDefinitions",
        "description": "Lists the location-related [custom attribute definitions](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) that belong to a Square seller account.\nWhen all response pages are retrieved, the results include all custom attribute definitions\nthat are visible to the requesting application, including those that are created by other\napplications and set to `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "CreateLocationCustomAttributeDefinition",
        "operationId": "CreateLocationCustomAttributeDefinition",
        "description": "Creates a location-related [custom attribute definition](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) for a Square seller account.\nUse this endpoint to define a custom attribute that can be associated with locations.\nA custom attribute definition specifies the `key`, `visibility`, `schema`, and other properties\nfor a custom attribute. After the definition is created, you can call\n[UpsertLocationCustomAttribute](https://[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/custom-attribute-definitions/{key}": {
      "delete": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "DeleteLocationCustomAttributeDefinition",
        "operationId": "DeleteLocationCustomAttributeDefinition",
        "description": "Deletes a location-related [custom attribute definition](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) from a Square seller account.\nDeleting a custom attribute definition also deletes the corresponding custom attribute from\nall locations.\nOnly the definition owner can delete a custom attribute definition.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "RetrieveLocationCustomAttributeDefinition",
        "operationId": "RetrieveLocationCustomAttributeDefinition",
        "description": "Retrieves a location-related [custom attribute definition](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) from a Square seller account.\nTo retrieve a custom attribute definition created by another application, the `visibility`\nsetting must be `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "UpdateLocationCustomAttributeDefinition",
        "operationId": "UpdateLocationCustomAttributeDefinition",
        "description": "Updates a location-related [custom attribute definition](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) for a Square seller account.\nUse this endpoint to update the following fields: `name`, `description`, `visibility`, or the\n`schema` for a `Selection` data type.\nOnly the definition owner can update a custom attribute definition.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/custom-attributes/bulk-delete": {
      "post": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "BulkDeleteLocationCustomAttributes",
        "operationId": "BulkDeleteLocationCustomAttributes",
        "description": "Deletes [custom attributes](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) for locations as a bulk operation.\nTo delete a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/custom-attributes/bulk-upsert": {
      "post": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "BulkUpsertLocationCustomAttributes",
        "operationId": "BulkUpsertLocationCustomAttributes",
        "description": "Creates or updates [custom attributes](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) for locations as a bulk operation.\nUse this endpoint to set the value of one or more custom attributes for one or more locations.\nA custom attribute is based on a custom attribute definition in a Square seller account, which is\ncreated using the [CreateLocationCustomAttributeDefinition](https://developer.squareup.com/reference/square_2023-07-20/loc[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "RetrieveLocation",
        "operationId": "RetrieveLocation",
        "description": "Retrieves details of a single location. Specify \"main\"\nas the location ID to retrieve details of the [main location](https://developer.squareup.com/docs/locations-api#about-the-main-location).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Locations"
        ],
        "summary": "UpdateLocation",
        "operationId": "UpdateLocation",
        "description": "Updates a [location](https://developer.squareup.com/docs/locations-api).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/checkouts": {
      "post": {
        "tags": [
          "Checkout"
        ],
        "summary": "CreateCheckout",
        "operationId": "CreateCheckout",
        "description": "Links a `checkoutId` to a `checkout_page_url` that customers are\ndirected to in order to provide their payment information using a\npayment processing workflow hosted on connect.squareup.com. \n\n\nNOTE: The Checkout API has been updated with new features. \nFor more information, see [Checkout API highlights](https://developer.squareup.com/docs/checkout-api#checkout-api-highlights).\nWe recommend that you use the new [CreatePaymentLink](https://developer.squareup.com/ref[...]",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "PAYMENTS_WRITE",
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE",
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/custom-attributes": {
      "get": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "ListLocationCustomAttributes",
        "operationId": "ListLocationCustomAttributes",
        "description": "Lists the [custom attributes](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) associated with a location.\nYou can use the `with_definitions` query parameter to also retrieve custom attribute definitions\nin the same call.\nWhen all response pages are retrieved, the results include all custom attributes that are\nvisible to the requesting application, including those that are owned by other applications\nand set to `VISIBILITY_READ_ONLY[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/custom-attributes/{key}": {
      "delete": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "DeleteLocationCustomAttribute",
        "operationId": "DeleteLocationCustomAttribute",
        "description": "Deletes a [custom attribute](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) associated with a location.\nTo delete a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "RetrieveLocationCustomAttribute",
        "operationId": "RetrieveLocationCustomAttribute",
        "description": "Retrieves a [custom attribute](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) associated with a location.\nYou can use the `with_definition` query parameter to also retrieve the custom attribute definition\nin the same call.\nTo retrieve a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "UpsertLocationCustomAttribute",
        "operationId": "UpsertLocationCustomAttribute",
        "description": "Creates or updates a [custom attribute](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) for a location.\nUse this endpoint to set the value of a custom attribute for a specified location.\nA custom attribute is based on a custom attribute definition in a Square seller account, which\nis created using the [CreateLocationCustomAttributeDefinition](https://developer.squareup.com/reference/square_2023-07-20/location-custom-attributes-api/cr[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions": {
      "get": {
        "tags": [
          "Transactions"
        ],
        "summary": "ListTransactions",
        "operationId": "ListTransactions",
        "description": "Lists transactions for a particular location.\n\nTransactions include payment information from sales and exchanges and refund\ninformation from returns and exchanges.\n\nMax results per [page](https://developer.squareup.com/docs/working-with-apis/pagination): 50",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions/{transaction_id}": {
      "get": {
        "tags": [
          "Transactions"
        ],
        "summary": "RetrieveTransaction",
        "operationId": "RetrieveTransaction",
        "description": "Retrieves details for a single transaction.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions/{transaction_id}/capture": {
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "CaptureTransaction",
        "operationId": "CaptureTransaction",
        "description": "Captures a transaction that was created with the [Charge](https://developer.squareup.com/reference/square_2023-07-20/transactions-api/charge)\nendpoint with a `delay_capture` value of `true`.\n\n\nSee [Delayed capture transactions](https://developer.squareup.com/docs/payments/transactions/overview#delayed-capture)\nfor more information.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions/{transaction_id}/void": {
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "VoidTransaction",
        "operationId": "VoidTransaction",
        "description": "Cancels a transaction that was created with the [Charge](https://developer.squareup.com/reference/square_2023-07-20/transactions-api/charge)\nendpoint with a `delay_capture` value of `true`.\n\n\nSee [Delayed capture transactions](https://developer.squareup.com/docs/payments/transactions/overview#delayed-capture)\nfor more information.",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/accounts": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "CreateLoyaltyAccount",
        "operationId": "CreateLoyaltyAccount",
        "description": "Creates a loyalty account. To create a loyalty account, you must provide the `program_id` and a `mapping` with the `phone_number` of the buyer.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/accounts/search": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "SearchLoyaltyAccounts",
        "operationId": "SearchLoyaltyAccounts",
        "description": "Searches for loyalty accounts in a loyalty program.\n\nYou can search for a loyalty account using the phone number or customer ID associated with the account. To return all loyalty accounts, specify an empty `query` object or omit it entirely.\n\nSearch results are sorted by `created_at` in ascending order.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/accounts/{account_id}": {
      "get": {
        "tags": [
          "Loyalty"
        ],
        "summary": "RetrieveLoyaltyAccount",
        "operationId": "RetrieveLoyaltyAccount",
        "description": "Retrieves a loyalty account.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/accounts/{account_id}/accumulate": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "AccumulateLoyaltyPoints",
        "operationId": "AccumulateLoyaltyPoints",
        "description": "Adds points earned from a purchase to a [loyalty account](https://developer.squareup.com/reference/square_2023-07-20/objects/LoyaltyAccount).\n\n- If you are using the Orders API to manage orders, provide the `order_id`. Square reads the order\nto compute the points earned from both the base loyalty program and an associated\n[loyalty promotion](https://developer.squareup.com/reference/square_2023-07-20/objects/LoyaltyPromotion). For purchases that qualify for multiple ac[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/accounts/{account_id}/adjust": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "AdjustLoyaltyPoints",
        "operationId": "AdjustLoyaltyPoints",
        "description": "Adds points to or subtracts points from a buyer\u0027s account.\n\nUse this endpoint only when you need to manually adjust points. Otherwise, in your application flow, you call\n[AccumulateLoyaltyPoints](https://developer.squareup.com/reference/square_2023-07-20/loyalty-api/accumulate-loyalty-points)\nto add points when a buyer pays for the purchase.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/events/search": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "SearchLoyaltyEvents",
        "operationId": "SearchLoyaltyEvents",
        "description": "Searches for loyalty events.\n\nA Square loyalty program maintains a ledger of events that occur during the lifetime of a\nbuyer\u0027s loyalty account. Each change in the point balance\n(for example, points earned, points redeemed, and points expired) is\nrecorded in the ledger. Using this endpoint, you can search the ledger for events.\n\nSearch results are sorted by `created_at` in descending order.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/programs": {
      "get": {
        "tags": [
          "Loyalty"
        ],
        "summary": "ListLoyaltyPrograms",
        "operationId": "ListLoyaltyPrograms",
        "description": "Returns a list of loyalty programs in the seller\u0027s account.\nLoyalty programs define how buyers can earn points and redeem points for rewards. Square sellers can have only one loyalty program, which is created and managed from the Seller Dashboard. For more information, see [Loyalty Program Overview](https://developer.squareup.com/docs/loyalty/overview).\n\n\nReplaced with [RetrieveLoyaltyProgram](https://developer.squareup.com/reference/square_2023-07-20/loyalty-api[...]",
        "x-release-status": "DEPRECATED",
        "x-is-deprecated": true,
        "x-oauthpermissions": [
          "LOYALTY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/programs/{program_id}": {
      "get": {
        "tags": [
          "Loyalty"
        ],
        "summary": "RetrieveLoyaltyProgram",
        "operationId": "RetrieveLoyaltyProgram",
        "description": "Retrieves the loyalty program in a seller\u0027s account, specified by the program ID or the keyword `main`.\n\nLoyalty programs define how buyers can earn points and redeem points for rewards. Square sellers can have only one loyalty program, which is created and managed from the Seller Dashboard. For more information, see [Loyalty Program Overview](https://developer.squareup.com/docs/loyalty/overview).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/programs/{program_id}/calculate": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "CalculateLoyaltyPoints",
        "operationId": "CalculateLoyaltyPoints",
        "description": "Calculates the number of points a buyer can earn from a purchase. Applications might call this endpoint\nto display the points to the buyer.\n\n- If you are using the Orders API to manage orders, provide the `order_id` and (optional) `loyalty_account_id`.\nSquare reads the order to compute the points earned from the base loyalty program and an associated\n[loyalty promotion](https://developer.squareup.com/reference/square_2023-07-20/objects/LoyaltyPromotion).\n\n- If you [...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/programs/{program_id}/promotions": {
      "get": {
        "tags": [
          "Loyalty"
        ],
        "summary": "ListLoyaltyPromotions",
        "operationId": "ListLoyaltyPromotions",
        "description": "Lists the loyalty promotions associated with a [loyalty program](https://developer.squareup.com/reference/square_2023-07-20/objects/LoyaltyProgram).\nResults are sorted by the `created_at` date in descending order (newest to oldest).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "CreateLoyaltyPromotion",
        "operationId": "CreateLoyaltyPromotion",
        "description": "Creates a loyalty promotion for a [loyalty program](https://developer.squareup.com/reference/square_2023-07-20/objects/LoyaltyProgram). A loyalty promotion\nenables buyers to earn points in addition to those earned from the base loyalty program.\n\nThis endpoint sets the loyalty promotion to the `ACTIVE` or `SCHEDULED` status, depending on the\n`available_time` setting. A loyalty program can have a maximum of 10 loyalty promotions with an\n`ACTIVE` or `SCHEDULED` status."[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/programs/{program_id}/promotions/{promotion_id}": {
      "get": {
        "tags": [
          "Loyalty"
        ],
        "summary": "RetrieveLoyaltyPromotion",
        "operationId": "RetrieveLoyaltyPromotion",
        "description": "Retrieves a loyalty promotion.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/programs/{program_id}/promotions/{promotion_id}/cancel": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "CancelLoyaltyPromotion",
        "operationId": "CancelLoyaltyPromotion",
        "description": "Cancels a loyalty promotion. Use this endpoint to cancel an `ACTIVE` promotion earlier than the\nend date, cancel an `ACTIVE` promotion when an end date is not specified, or cancel a `SCHEDULED` promotion.\nBecause updating a promotion is not supported, you can also use this endpoint to cancel a promotion before\nyou create a new one.\n\nThis endpoint sets the loyalty promotion to the `CANCELED` state",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/rewards": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "CreateLoyaltyReward",
        "operationId": "CreateLoyaltyReward",
        "description": "Creates a loyalty reward. In the process, the endpoint does following:\n\n- Uses the `reward_tier_id` in the request to determine the number of points\nto lock for this reward.\n- If the request includes `order_id`, it adds the reward and related discount to the order.\n\nAfter a reward is created, the points are locked and\nnot available for the buyer to redeem another reward.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/rewards/search": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "SearchLoyaltyRewards",
        "operationId": "SearchLoyaltyRewards",
        "description": "Searches for loyalty rewards. This endpoint accepts a request with no query filters and returns results for all loyalty accounts.\nIf you include a `query` object, `loyalty_account_id` is required and `status` is  optional.\n\nIf you know a reward ID, use the\n[RetrieveLoyaltyReward](https://developer.squareup.com/reference/square_2023-07-20/loyalty-api/retrieve-loyalty-reward) endpoint.\n\nSearch results are sorted by `updated_at` in descending order.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/rewards/{reward_id}": {
      "delete": {
        "tags": [
          "Loyalty"
        ],
        "summary": "DeleteLoyaltyReward",
        "operationId": "DeleteLoyaltyReward",
        "description": "Deletes a loyalty reward by doing the following:\n\n- Returns the loyalty points back to the loyalty account.\n- If an order ID was specified when the reward was created\n(see [CreateLoyaltyReward](https://developer.squareup.com/reference/square_2023-07-20/loyalty-api/create-loyalty-reward)),\nit updates the order by removing the reward and related\ndiscounts.\n\nYou cannot delete a reward that has reached the terminal state (REDEEMED).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Loyalty"
        ],
        "summary": "RetrieveLoyaltyReward",
        "operationId": "RetrieveLoyaltyReward",
        "description": "Retrieves a loyalty reward.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/rewards/{reward_id}/redeem": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "RedeemLoyaltyReward",
        "operationId": "RedeemLoyaltyReward",
        "description": "Redeems a loyalty reward.\n\nThe endpoint sets the reward to the `REDEEMED` terminal state.\n\nIf you are using your own order processing system (not using the\nOrders API), you call this endpoint after the buyer paid for the\npurchase.\n\nAfter the reward reaches the terminal state, it cannot be deleted.\nIn other words, points used for the reward cannot be returned\nto the account.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "LOYALTY_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/merchants": {
      "get": {
        "tags": [
          "Merchants"
        ],
        "summary": "ListMerchants",
        "operationId": "ListMerchants",
        "description": "Provides details about the merchant associated with a given access token.\n\nThe access token used to connect your application to a Square seller is associated\nwith a single merchant. That means that `ListMerchants` returns a list\nwith a single `Merchant` object. You can specify your personal access token\nto get your own merchant information or specify an OAuth token to get the\ninformation for the merchant that granted your application access.\n\nIf you know the merch[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      }
    },
    "/v2/merchants/custom-attribute-definitions": {
      "get": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "ListMerchantCustomAttributeDefinitions",
        "operationId": "ListMerchantCustomAttributeDefinitions",
        "description": "Lists the merchant-related [custom attribute definitions](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) that belong to a Square seller account.\nWhen all response pages are retrieved, the results include all custom attribute definitions\nthat are visible to the requesting application, including those that are created by other\napplications and set to `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "CreateMerchantCustomAttributeDefinition",
        "operationId": "CreateMerchantCustomAttributeDefinition",
        "description": "Creates a merchant-related [custom attribute definition](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) for a Square seller account.\nUse this endpoint to define a custom attribute that can be associated with a merchant connecting to your application.\nA custom attribute definition specifies the `key`, `visibility`, `schema`, and other properties\nfor a custom attribute. After the definition is created, you can call\n[UpsertM[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/merchants/custom-attribute-definitions/{key}": {
      "delete": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "DeleteMerchantCustomAttributeDefinition",
        "operationId": "DeleteMerchantCustomAttributeDefinition",
        "description": "Deletes a merchant-related [custom attribute definition](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) from a Square seller account.\nDeleting a custom attribute definition also deletes the corresponding custom attribute from\nthe merchant.\nOnly the definition owner can delete a custom attribute definition.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "RetrieveMerchantCustomAttributeDefinition",
        "operationId": "RetrieveMerchantCustomAttributeDefinition",
        "description": "Retrieves a merchant-related [custom attribute definition](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) from a Square seller account.\nTo retrieve a custom attribute definition created by another application, the `visibility`\nsetting must be `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "UpdateMerchantCustomAttributeDefinition",
        "operationId": "UpdateMerchantCustomAttributeDefinition",
        "description": "Updates a merchant-related [custom attribute definition](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) for a Square seller account.\nUse this endpoint to update the following fields: `name`, `description`, `visibility`, or the\n`schema` for a `Selection` data type.\nOnly the definition owner can update a custom attribute definition.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/merchants/custom-attributes/bulk-delete": {
      "post": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "BulkDeleteMerchantCustomAttributes",
        "operationId": "BulkDeleteMerchantCustomAttributes",
        "description": "Deletes [custom attributes](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) for a merchant as a bulk operation.\nTo delete a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/merchants/custom-attributes/bulk-upsert": {
      "post": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "BulkUpsertMerchantCustomAttributes",
        "operationId": "BulkUpsertMerchantCustomAttributes",
        "description": "Creates or updates [custom attributes](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) for a merchant as a bulk operation.\nUse this endpoint to set the value of one or more custom attributes for a merchant.\nA custom attribute is based on a custom attribute definition in a Square seller account, which is\ncreated using the [CreateMerchantCustomAttributeDefinition](https://developer.squareup.com/reference/square_2023-07-20/merchant-cust[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/merchants/{merchant_id}": {
      "get": {
        "tags": [
          "Merchants"
        ],
        "summary": "RetrieveMerchant",
        "operationId": "RetrieveMerchant",
        "description": "Retrieves the `Merchant` object for the given `merchant_id`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      }
    },
    "/v2/merchants/{merchant_id}/custom-attributes": {
      "get": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "ListMerchantCustomAttributes",
        "operationId": "ListMerchantCustomAttributes",
        "description": "Lists the [custom attributes](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) associated with a merchant.\nYou can use the `with_definitions` query parameter to also retrieve custom attribute definitions\nin the same call.\nWhen all response pages are retrieved, the results include all custom attributes that are\nvisible to the requesting application, including those that are owned by other applications\nand set to `VISIBILITY_READ_ONLY[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      }
    },
    "/v2/merchants/{merchant_id}/custom-attributes/{key}": {
      "delete": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "DeleteMerchantCustomAttribute",
        "operationId": "DeleteMerchantCustomAttribute",
        "description": "Deletes a [custom attribute](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) associated with a merchant.\nTo delete a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "RetrieveMerchantCustomAttribute",
        "operationId": "RetrieveMerchantCustomAttribute",
        "description": "Retrieves a [custom attribute](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) associated with a merchant.\nYou can use the `with_definition` query parameter to also retrieve the custom attribute definition\nin the same call.\nTo retrieve a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "UpsertMerchantCustomAttribute",
        "operationId": "UpsertMerchantCustomAttribute",
        "description": "Creates or updates a [custom attribute](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) for a merchant.\nUse this endpoint to set the value of a custom attribute for a specified merchant.\nA custom attribute is based on a custom attribute definition in a Square seller account, which\nis created using the [CreateMerchantCustomAttributeDefinition](https://developer.squareup.com/reference/square_2023-07-20/merchant-custom-attributes-api/cr[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/online-checkout/payment-links": {
      "get": {
        "tags": [
          "Checkout"
        ],
        "summary": "ListPaymentLinks",
        "operationId": "ListPaymentLinks",
        "description": "Lists all payment links.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ORDERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Checkout"
        ],
        "summary": "CreatePaymentLink",
        "operationId": "CreatePaymentLink",
        "description": "Creates a Square-hosted checkout page. Applications can share the resulting payment link with their buyer to pay for goods and services.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE",
          "ORDERS_READ",
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE",
              "ORDERS_READ",
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/online-checkout/payment-links/{id}": {
      "delete": {
        "tags": [
          "Checkout"
        ],
        "summary": "DeletePaymentLink",
        "operationId": "DeletePaymentLink",
        "description": "Deletes a payment link.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ORDERS_READ",
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ",
              "ORDERS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Checkout"
        ],
        "summary": "RetrievePaymentLink",
        "operationId": "RetrievePaymentLink",
        "description": "Retrieves a payment link.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ORDERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Checkout"
        ],
        "summary": "UpdatePaymentLink",
        "operationId": "UpdatePaymentLink",
        "description": "Updates a payment link. You can update the `payment_link` fields such as\n`description`, `checkout_options`, and  `pre_populated_data`.\nYou cannot update other fields such as the `order_id`, `version`, `URL`, or `timestamp` field.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE",
          "ORDERS_READ",
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE",
              "ORDERS_READ",
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/orders": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "CreateOrder",
        "operationId": "CreateOrder",
        "description": "Creates a new [order](https://developer.squareup.com/reference/square_2023-07-20/objects/Order) that can include information about products for\npurchase and settings to apply to the purchase.\n\nTo pay for a created order, see\n[Pay for Orders](https://developer.squareup.com/docs/orders-api/pay-for-orders).\n\nYou can modify open orders using the [UpdateOrder](https://developer.squareup.com/reference/square_2023-07-20/orders-api/update-order) endpoint.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/orders/batch-retrieve": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "BatchRetrieveOrders",
        "operationId": "BatchRetrieveOrders",
        "description": "Retrieves a set of [orders](https://developer.squareup.com/reference/square_2023-07-20/objects/Order) by their IDs.\n\nIf a given order ID does not exist, the ID is ignored instead of generating an error.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ORDERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/orders/calculate": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "CalculateOrder",
        "operationId": "CalculateOrder",
        "description": "Enables applications to preview order pricing without creating an order.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v2/orders/clone": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "CloneOrder",
        "operationId": "CloneOrder",
        "description": "Creates a new order, in the `DRAFT` state, by duplicating an existing order. The newly created order has\nonly the core fields (such as line items, taxes, and discounts) copied from the original order.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/orders/custom-attribute-definitions": {
      "get": {
        "tags": [
          "OrderCustomAttributes"
        ],
        "summary": "ListOrderCustomAttributeDefinitions",
        "operationId": "ListOrderCustomAttributeDefinitions",
        "description": "Lists the order-related [custom attribute definitions](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) that belong to a Square seller account.\n\nWhen all response pages are retrieved, the results include all custom attribute definitions\nthat are visible to the requesting application, including those that are created by other\napplications and set to `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`. Note that\nseller-[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "ORDERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "OrderCustomAttributes"
        ],
        "summary": "CreateOrderCustomAttributeDefinition",
        "operationId": "CreateOrderCustomAttributeDefinition",
        "description": "Creates an order-related custom attribute definition.  Use this endpoint to\ndefine a custom attribute that can be associated with orders.\n\nAfter creating a custom attribute definition, you can set the custom attribute for orders\nin the Square seller account.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/orders/custom-attribute-definitions/{key}": {
      "delete": {
        "tags": [
          "OrderCustomAttributes"
        ],
        "summary": "DeleteOrderCustomAttributeDefinition",
        "operationId": "DeleteOrderCustomAttributeDefinition",
        "description": "Deletes an order-related [custom attribute definition](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) from a Square seller account.\n\nOnly the definition owner can delete a custom attribute definition.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "OrderCustomAttributes"
        ],
        "summary": "RetrieveOrderCustomAttributeDefinition",
        "operationId": "RetrieveOrderCustomAttributeDefinition",
        "description": "Retrieves an order-related [custom attribute definition](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttributeDefinition) from a Square seller account.\n\nTo retrieve a custom attribute definition created by another application, the `visibility`\nsetting must be `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`. Note that seller-defined custom attributes\n(also known as custom fields) are always set to `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "ORDERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "OrderCustomAttributes"
        ],
        "summary": "UpdateOrderCustomAttributeDefinition",
        "operationId": "UpdateOrderCustomAttributeDefinition",
        "description": "Updates an order-related custom attribute definition for a Square seller account.\n\nOnly the definition owner can update a custom attribute definition. Note that sellers can view all custom attributes in exported customer data, including those set to `VISIBILITY_HIDDEN`.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/orders/custom-attributes/bulk-delete": {
      "post": {
        "tags": [
          "OrderCustomAttributes"
        ],
        "summary": "BulkDeleteOrderCustomAttributes",
        "operationId": "BulkDeleteOrderCustomAttributes",
        "description": "Deletes order [custom attributes](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) as a bulk operation.\n\nUse this endpoint to delete one or more custom attributes from one or more orders.\nA custom attribute is based on a custom attribute definition in a Square seller account.  (To create a\ncustom attribute definition, use the [CreateOrderCustomAttributeDefinition](https://developer.squareup.com/reference/square_2023-07-20/order-custo[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/orders/custom-attributes/bulk-upsert": {
      "post": {
        "tags": [
          "OrderCustomAttributes"
        ],
        "summary": "BulkUpsertOrderCustomAttributes",
        "operationId": "BulkUpsertOrderCustomAttributes",
        "description": "Creates or updates order [custom attributes](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) as a bulk operation.\n\nUse this endpoint to delete one or more custom attributes from one or more orders.\nA custom attribute is based on a custom attribute definition in a Square seller account.  (To create a\ncustom attribute definition, use the [CreateOrderCustomAttributeDefinition](https://developer.squareup.com/reference/square_2023-07-20/[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/orders/search": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "SearchOrders",
        "operationId": "SearchOrders",
        "description": "Search all orders for one or more locations. Orders include all sales,\nreturns, and exchanges regardless of how or when they entered the Square\necosystem (such as Point of Sale, Invoices, and Connect APIs).\n\n`SearchOrders` requests need to specify which locations to search and define a\n[SearchOrdersQuery](https://developer.squareup.com/reference/square_2023-07-20/objects/SearchOrdersQuery) object that controls\nhow to sort or filter the results. Your `SearchOrdersQue[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ORDERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/orders/{order_id}": {
      "get": {
        "tags": [
          "Orders"
        ],
        "summary": "RetrieveOrder",
        "operationId": "RetrieveOrder",
        "description": "Retrieves an [Order](https://developer.squareup.com/reference/square_2023-07-20/objects/Order) by ID.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ORDERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Orders"
        ],
        "summary": "UpdateOrder",
        "operationId": "UpdateOrder",
        "description": "Updates an open [order](https://developer.squareup.com/reference/square_2023-07-20/objects/Order) by adding, replacing, or deleting\nfields. Orders with a `COMPLETED` or `CANCELED` state cannot be updated.\n\nAn `UpdateOrder` request requires the following:\n\n- The `order_id` in the endpoint path, identifying the order to update.\n- The latest `version` of the order to update.\n- The [sparse order](https://developer.squareup.com/docs/orders-api/manage-orders/update-order[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/orders/{order_id}/custom-attributes": {
      "get": {
        "tags": [
          "OrderCustomAttributes"
        ],
        "summary": "ListOrderCustomAttributes",
        "operationId": "ListOrderCustomAttributes",
        "description": "Lists the [custom attributes](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) associated with an order.\n\nYou can use the `with_definitions` query parameter to also retrieve custom attribute definitions\nin the same call.\n\nWhen all response pages are retrieved, the results include all custom attributes that are\nvisible to the requesting application, including those that are owned by other applications\nand set to `VISIBILITY_READ_ON[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "ORDERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/orders/{order_id}/custom-attributes/{custom_attribute_key}": {
      "delete": {
        "tags": [
          "OrderCustomAttributes"
        ],
        "summary": "DeleteOrderCustomAttribute",
        "operationId": "DeleteOrderCustomAttribute",
        "description": "Deletes a [custom attribute](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) associated with a customer profile.\n\nTo delete a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_WRITE_VALUES`. Note that seller-defined custom attributes\n(also known as custom fields) are always set to `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "OrderCustomAttributes"
        ],
        "summary": "RetrieveOrderCustomAttribute",
        "operationId": "RetrieveOrderCustomAttribute",
        "description": "Retrieves a [custom attribute](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) associated with an order.\n\nYou can use the `with_definition` query parameter to also retrieve the custom attribute definition\nin the same call.\n\nTo retrieve a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`. Note that seller-defined custom attributes\nalso known as [...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "ORDERS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "OrderCustomAttributes"
        ],
        "summary": "UpsertOrderCustomAttribute",
        "operationId": "UpsertOrderCustomAttribute",
        "description": "Creates or updates a [custom attribute](https://developer.squareup.com/reference/square_2023-07-20/objects/CustomAttribute) for an order.\n\nUse this endpoint to set the value of a custom attribute for a specific order.\nA custom attribute is based on a custom attribute definition in a Square seller account. (To create a\ncustom attribute definition, use the [CreateOrderCustomAttributeDefinition](https://developer.squareup.com/reference/square_2023-07-20/order-custom-attr[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/orders/{order_id}/pay": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "PayOrder",
        "operationId": "PayOrder",
        "description": "Pay for an [order](https://developer.squareup.com/reference/square_2023-07-20/objects/Order) using one or more approved [payments](https://developer.squareup.com/reference/square_2023-07-20/objects/Payment)\nor settle an order with a total of `0`.\n\nThe total of the `payment_ids` listed in the request must be equal to the order\ntotal. Orders with a total amount of `0` can be marked as paid by specifying an empty\narray of `payment_ids` in the request.\n\nTo be used with[...]",
        "x-release-status": "BETA",
        "x-is-beta": true,
        "x-oauthpermissions": [
          "PAYMENTS_WRITE",
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE",
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/payments": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "ListPayments",
        "operationId": "ListPayments",
        "description": "Retrieves a list of payments taken by the account making the request.\n\nResults are eventually consistent, and new payments or changes to payments might take several\nseconds to appear.\n\nThe maximum results per page is 100.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "CreatePayment",
        "operationId": "CreatePayment",
        "description": "Creates a payment using the provided source. You can use this endpoint \nto charge a card (credit/debit card or    \nSquare gift card) or record a payment that the seller received outside of Square \n(cash payment from a buyer or a payment that an external entity \nprocessed on behalf of the seller).\n\nThe endpoint creates a \n`Payment` object and returns it in the response.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/payments/cancel": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "CancelPaymentByIdempotencyKey",
        "operationId": "CancelPaymentByIdempotencyKey",
        "description": "Cancels (voids) a payment identified by the idempotency key that is specified in the\nrequest.\n\nUse this method when the status of a `CreatePayment` request is unknown (for example, after you send a\n`CreatePayment` request, a network error occurs and you do not get a response). In this case, you can\ndirect Square to cancel the payment using this endpoint. In the request, you provide the same\nidempotency key that you provided in your `CreatePayment` request that you w[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/payments/{payment_id}": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "GetPayment",
        "operationId": "GetPayment",
        "description": "Retrieves details for a specific payment.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Payments"
        ],
        "summary": "UpdatePayment",
        "operationId": "UpdatePayment",
        "description": "Updates a payment with the APPROVED status.\nYou can update the `amount_money` and `tip_money` using this endpoint.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/payments/{payment_id}/cancel": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "CancelPayment",
        "operationId": "CancelPayment",
        "description": "Cancels (voids) a payment. You can use this endpoint to cancel a payment with \nthe APPROVED `status`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/payments/{payment_id}/complete": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "CompletePayment",
        "operationId": "CompletePayment",
        "description": "Completes (captures) a payment.\nBy default, payments are set to complete immediately after they are created.\n\nYou can use this endpoint to complete a payment with the APPROVED `status`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/payouts": {
      "get": {
        "tags": [
          "Payouts"
        ],
        "summary": "ListPayouts",
        "operationId": "ListPayouts",
        "description": "Retrieves a list of all payouts for the default location.\nYou can filter payouts by location ID, status, time range, and order them in ascending or descending order.\nTo call this endpoint, set `PAYOUTS_READ` for the OAuth scope.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v2/payouts/{payout_id}": {
      "get": {
        "tags": [
          "Payouts"
        ],
        "summary": "GetPayout",
        "operationId": "GetPayout",
        "description": "Retrieves details of a specific payout identified by a payout ID.\nTo call this endpoint, set `PAYOUTS_READ` for the OAuth scope.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v2/payouts/{payout_id}/payout-entries": {
      "get": {
        "tags": [
          "Payouts"
        ],
        "summary": "ListPayoutEntries",
        "operationId": "ListPayoutEntries",
        "description": "Retrieves a list of all payout entries for a specific payout.\nTo call this endpoint, set `PAYOUTS_READ` for the OAuth scope.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v2/refunds": {
      "get": {
        "tags": [
          "Refunds"
        ],
        "summary": "ListPaymentRefunds",
        "operationId": "ListPaymentRefunds",
        "description": "Retrieves a list of refunds for the account making the request.\n\nResults are eventually consistent, and new refunds or changes to refunds might take several\nseconds to appear.\n\nThe maximum results per page is 100.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Refunds"
        ],
        "summary": "RefundPayment",
        "operationId": "RefundPayment",
        "description": "Refunds a payment. You can refund the entire payment amount or a\nportion of it. You can use this endpoint to refund a card payment or record a \nrefund of a cash or external payment. For more information, see\n[Refund Payment](https://developer.squareup.com/docs/payments-api/refund-payments).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/refunds/{refund_id}": {
      "get": {
        "tags": [
          "Refunds"
        ],
        "summary": "GetPaymentRefund",
        "operationId": "GetPaymentRefund",
        "description": "Retrieves a specific refund using the `refund_id`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/sites": {
      "get": {
        "tags": [
          "Sites"
        ],
        "summary": "ListSites",
        "operationId": "ListSites",
        "description": "Lists the Square Online sites that belong to a seller. Sites are listed in descending order by the `created_at` date.\n\n\n__Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/online-api#early-access-program-for-square-online-apis).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ONLINE_STORE_SITE_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ONLINE_STORE_SITE_READ"
            ]
          }
        ]
      }
    },
    "/v2/sites/{site_id}/snippet": {
      "delete": {
        "tags": [
          "Snippets"
        ],
        "summary": "DeleteSnippet",
        "operationId": "DeleteSnippet",
        "description": "Removes your snippet from a Square Online site.\n\nYou can call [ListSites](https://developer.squareup.com/reference/square_2023-07-20/sites-api/list-sites) to get the IDs of the sites that belong to a seller.\n\n\n__Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/online-api#early-access-program-for-square-online-apis).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ONLINE_STORE_SNIPPETS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ONLINE_STORE_SNIPPETS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Snippets"
        ],
        "summary": "RetrieveSnippet",
        "operationId": "RetrieveSnippet",
        "description": "Retrieves your snippet from a Square Online site. A site can contain snippets from multiple snippet applications, but you can retrieve only the snippet that was added by your application.\n\nYou can call [ListSites](https://developer.squareup.com/reference/square_2023-07-20/sites-api/list-sites) to get the IDs of the sites that belong to a seller.\n\n\n__Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early [...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ONLINE_STORE_SNIPPETS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ONLINE_STORE_SNIPPETS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Snippets"
        ],
        "summary": "UpsertSnippet",
        "operationId": "UpsertSnippet",
        "description": "Adds a snippet to a Square Online site or updates the existing snippet on the site. \nThe snippet code is appended to the end of the `head` element on every page of the site, except checkout pages. A snippet application can add one snippet to a given site. \n\nYou can call [ListSites](https://developer.squareup.com/reference/square_2023-07-20/sites-api/list-sites) to get the IDs of the sites that belong to a seller.\n\n\n__Note:__ Square Online APIs are publicly available[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ONLINE_STORE_SNIPPETS_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "ONLINE_STORE_SNIPPETS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/subscriptions": {
      "post": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "CreateSubscription",
        "operationId": "CreateSubscription",
        "description": "Enrolls a customer in a subscription.\n\nIf you provide a card on file in the request, Square charges the card for\nthe subscription. Otherwise, Square sends an invoice to the customer\u0027s email\naddress. The subscription starts immediately, unless the request includes\nthe optional `start_date`. Each individual subscription is associated with a particular location.\n\nFor more information, see [Create a subscription](https://developer.squareup.com/docs/subscriptions-a[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ",
          "PAYMENTS_WRITE",
          "SUBSCRIPTIONS_WRITE",
          "ITEMS_READ",
          "ORDERS_WRITE",
          "INVOICES_WRITE"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ",
              "PAYMENTS_WRITE",
              "SUBSCRIPTIONS_WRITE",
              "ITEMS_READ",
              "ORDERS_WRITE",
              "INVOICES_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/subscriptions/search": {
      "post": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "SearchSubscriptions",
        "operationId": "SearchSubscriptions",
        "description": "Searches for subscriptions.\n\nResults are ordered chronologically by subscription creation date. If\nthe request specifies more than one location ID,\nthe endpoint orders the result\nby location ID, and then by creation date within each location. If no locations are given\nin the query, all locations are searched.\n\nYou can also optionally specify `customer_ids` to search by customer.\nIf left unset, all customers\nassociated with the specified locations are returned.\n[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "SUBSCRIPTIONS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "SUBSCRIPTIONS_READ"
            ]
          }
        ]
      }
    },
    "/v2/subscriptions/{subscription_id}": {
      "get": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "RetrieveSubscription",
        "operationId": "RetrieveSubscription",
        "description": "Retrieves a specific subscription.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "SUBSCRIPTIONS_READ"
        ],
        "x-sq-version": "2023-07-20",
        "security": [
          {
            "oauth2": [
              "SUBSCRIPTIONS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Subscriptions"
        ],
[...]
