name: Destination Plugin ClickHouse Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - plugins/destination/clickhouse/**
      - .github/workflows/dest_clickhouse.yml
  push:
    branches:
      - main
    paths:
      - plugins/destination/clickhouse/**
      - .github/workflows/dest_clickhouse.yml

permissions:
  contents: read

jobs:
  plugins-destination-clickhouse:
    name: 'plugins/destination/clickhouse'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: plugins/destination/clickhouse

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        id: setup-go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: plugins/destination/clickhouse/go.mod
          cache: false
      - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-test-destination-clickhouse-${{ hashFiles('plugins/destination/clickhouse/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-test-destination-clickhouse-
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: v2.12.2
          working-directory: plugins/destination/clickhouse
          args: "--config ../../.golangci.yml"
      - name: gen
        if: github.event_name == 'pull_request'
        run: make gen
      - name: Fail if generation updated files
        if: github.event_name == 'pull_request'
        run: test "$(git status -s | wc -l)" -eq 0 || (git status -s; exit 1)
      - name: Build
        run: go build .

      - uses: hoverkraft-tech/compose-action@077eccb7f2d44fc6806e4dcad31d4158381b9d18
        with:
          compose-file: docker-compose.yaml
          up-flags: "--wait"
          cwd: plugins/destination/clickhouse
      - name: Test ClickHouse
        run: make test
