name: Destination Plugin SQLite-Python Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "plugins/destination/sqlite-python/**"
      - ".github/workflows/dest_sqlite_python.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/destination/sqlite-python/**"
      - ".github/workflows/dest_sqlite_python.yml"

permissions:
  contents: read

jobs:
  plugins-destination-sqlite-python:
    timeout-minutes: 30
    name: "plugins/destination/sqlite-python"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/destination/sqlite-python
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: uv sync
      - name: Check formatting
        run: make fmt-check
      -
        # Required for the package command tests to work
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Run tests
        run: make test
  
