name: Release All PRs
on:
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write

jobs:
  add-automerge-labels:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Add token to config.yaml
        uses: jacobtomlinson/gha-find-replace@b19bfcb2a015af55fd6e160d1d1987e887f8c163
        with:
          find: GITHUB_TOKEN_VALUE
          replace: ${{ secrets.GITHUB_TOKEN }}
          regex: false
          include: config.yaml

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 'lts/*'

      - run: npm install -g @google/repo@6.1.2

      - name: Add to release PRs
        run: |
          repo "tag" "--title" "chore\(main\)\: Release" "automerge"