name: Source Plugin Square Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "plugins/source/square/**"
      - ".github/workflows/source_square.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/source/square/**"
      - ".github/workflows/source_square.yml"

permissions:
  contents: read

jobs:
  plugins-source-square:
    timeout-minutes: 30
    name: "plugins/source/square"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/source/square
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: uv sync
      - name: Check formatting
        run: make fmt-check

      -
        # Required for the package command tests to work
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Run tests
        run: make test
