name: Source Plugin Airtable Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "plugins/source/airtable/**"
      - ".github/workflows/source_airtable.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/source/airtable/**"
      - ".github/workflows/source_airtable.yml"

permissions:
  contents: read

jobs:
  plugins-source-airtable:
    timeout-minutes: 30
    name: "plugins/source/airtable"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/source/airtable
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
        with:
          package_json_file: './plugins/source/airtable/package.json'
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24'
          cache: 'pnpm'
          cache-dependency-path: './plugins/source/airtable/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: |
          pnpm run lint

      - name: Build
        run: |
          pnpm run build

      -
        # Required for the package command tests to work
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

      - name: Test
        run: |
          pnpm run test
