name: Transformer Plugin JSON Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "plugins/transformer/jsonflattener/**"
      - ".github/workflows/transf_jsonflattener.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/transformer/jsonflattener/**"
      - ".github/workflows/transf_jsonflattener.yml"

permissions:
  contents: read

jobs:
  plugins-transformer-json:
    timeout-minutes: 30
    name: "plugins/transformer/jsonflattener"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/transformer/jsonflattener
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        id: setup-go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: plugins/transformer/jsonflattener/go.mod
          cache: false
      - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-test-transformer-jsonflattener-${{ hashFiles('plugins/transformer/jsonflattener/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-test-transformer-jsonflattener-
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: v2.12.2
          working-directory: plugins/transformer/jsonflattener
          args: "--config ../../.golangci.yml"
      - name: Build
        run: go build .
      - name: Test
        run: make test
  