// Code generated by codegen2; DO NOT EDIT.
package sql

import (
	"github.com/cloudquery/plugin-sdk/schema"
)

func database_blob_auditing_policies() *schema.Table {
	return &schema.Table{
		Name:     "azure_sql_database_blob_auditing_policies",
		Resolver: fetchDatabaseBlobAuditingPolicies,
		Columns: []schema.Column{
			{
				Name:     "properties",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Properties"),
			},
			{
				Name:     "id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ID"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "kind",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Kind"),
			},
			{
				Name:     "name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Name"),
			},
			{
				Name:     "type",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Type"),
			},
		},
	}
}
