{
 "title": "GCP Asset Inventory",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_ids",
    "query": "select distinct(project_id) from gcp_resources"
   },
   {
    "name": "regions",
    "query": "select distinct(region) from gcp_resources;"
   },
   {
    "name": "cq_tables",
    "query": "select distinct(cq_table) from gcp_resources;"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Resources",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from gcp_resources where project_id in (${project_ids}) and region in (${regions}) and cq_table in (${cq_tables}) ;"
    }
   ]
  },
  {
   "title": "Total Resource by Project",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select project_id, count(*) from gcp_resources where region in (${regions}) and cq_table in (${cq_tables}) group by project_id order by count desc;"
    }
   ]
  },
  {
   "title": "Resources by Region",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "select region, count(*) from gcp_resources where project_id in (${project_ids}) group by region order by count desc;"
    }
   ]
  },
  {
   "title": "GCP Resources",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select cq_id, cq_table, project_id, region, id, fetch_date from gcp_resources where project_id in (${project_ids}) and region in (${regions}) and cq_table in (${cq_tables}) ;"
    }
   ]
  },
  {
   "title": "Count by Resource Type",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "select cq_table, count(*) from gcp_resources where project_id in (${project_ids}) and region in (${regions}) group by cq_table order by count desc;"
    }
   ]
  },
  {
   "title": "Resources by Region",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 6, "y": 21 },
   "targets": [
    {
     "rawSql": "select region, count(*) from gcp_resources where project_id in (${project_ids}) group by region order by count desc;"
    }
   ]
  }
 ]
}