{
 "title": "GCP Compliance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_id",
    "query": "select project_id from gcp_policy_results"
   },
   {
    "name": "framework",
    "query": "select framework from gcp_policy_results"
   },
   {
    "name": "status",
    "query": "select status from gcp_policy_results"
   }
  ]
 },
 "panels": [
  { "title": "CloudQuery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Source",
   "type": "stat",
   "description": "This panel will show OK if the gcp_resources view has been created and is accessible to the current Postgres user. See https://github.com/cloudquery/dashboards#gcp for more information.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM information_schema.tables\n     WHERE  table_schema = 'public'\n     AND    table_name   = 'gcp_policy_results'"
    }
   ]
  },
  {
   "title": "Last Sync",
   "type": "stat",
   "description": "Time since the most recent CloudQuery sync happened.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select _cq_sync_time as time, 1 from gcp_compute_instances order by time desc limit 1;"
    }
   ]
  },
  {
   "title": "Last Policy Execution",
   "type": "stat",
   "description": "Time since the most recent policy execution happened.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select execution_time as time, 1 from gcp_policy_results order by execution_time desc limit 1;"
    }
   ]
  },
  { "title": "Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Policy Pass/Fail Distribution",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select\n  -- execution_time as time,\n  framework,\n  count(case when status = 'fail' then 1 else null end) as fail,\n  -- count(*)\n  count(case when status = 'pass' then 1 else null end) as pass\nfrom gcp_policy_results where project_id in (${project_id}) and framework in (${framework}) group by framework;"
    }
   ]
  },
  {
   "title": "Failed Checks",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select execution_time as time, count(*) from gcp_policy_results where project_id in (${project_id}) and framework in (${framework}) and status = 'fail' and $__timeFilter(execution_time) group by execution_time;"
    }
   ]
  },
  {
   "title": "Passed Checks",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  execution_time as time,\n  count(*)\nfrom gcp_policy_results where project_id in (${project_id}) and framework in (${framework}) and status = 'pass' and $__timeFilter(execution_time) group by execution_time;"
    }
   ]
  },
  {
   "title": "Policy Results",
   "type": "table",
   "description": "All policies, benchmarks results.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select * from gcp_policy_results where project_id in (${project_id}) and framework in (${framework}) and status in (${status}) ;"
    }
   ]
  }
 ]
}